### ISSUE TITLE
K8S on Windows server 2019: example not working

### ISSUE THREAD

**Issue by GOVYANSONG** [MicrosoftDocs/Virtualization-Documentation#1010]
Trying to follow instructions given at https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/getting-started-kubernetes-windows. I was able to setup master on ubuntu. While the Windows server 2019 (v1809) VM was trying to start up, I got following error: 

E0312 16:51:54.394060    1808 server.go:730] Kubelet needs to run as uid `0`. It is being run as -1
**E0312 16:51:58.265321    1808 remote_runtime.go:96] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-proxy-98n6n": Error response from daemon: network host not found**
E0312 16:51:58.267295    1808 kuberuntime_sandbox.go:65] CreatePodSandbox for pod "kube-proxy-98n6n_kube-system(3584b070-4519-11e9-adc8-00155d64ad0d)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-proxy-98n6n": Error response from daemon: network host not found
E0312 16:51:58.268293    1808 kuberuntime_manager.go:662] createPodSandbox for pod "kube-proxy-98n6n_kube-system(3584b070-4519-11e9-adc8-00155d64ad0d)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-proxy-98n6n": Error response from daemon: network host not found
E0312 16:51:58.270281    1808 pod_workers.go:190] Error syncing pod 3584b070-4519-11e9-adc8-00155d64ad0d ("kube-proxy-98n6n_kube-system(3584b070-4519-11e9-adc8-00155d64ad0d)"), skipping: failed to "CreatePodSandbox" for "kube-proxy-98n6n_kube-system(3584b070-4519-11e9-adc8-00155d64ad0d)" with CreatePodSandboxError: "CreatePodSandbox for pod \"kube-proxy-98n6n_kube-system(3584b070-4519-11e9-adc8-00155d64ad0d)\" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod \"kube-proxy-98n6n\": Error response from daemon: network host not found"
E0312 16:52:11.767641    1808 remote_runtime.go:96] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to create a sandbox for pod "kube-proxy-98n6n": Error response from daemon: Conflict. The container name "/k8s_POD_kube-proxy-98n6n_kube-system_3584b070-4519-11e9-adc8-00155d64ad0d_0" is already in use by container "b23cadfb1461d3a3ecf1a19272c674c039e6e3b484ce11522f9c0233a44f0916". You have to remove (or rename) that container to be able to reuse that name.
E0312 16:52:25.335342    1808 kuberuntime_sandbox.go:65] CreatePodSandbox for pod "kube-proxy-98n6n_kube-system(3584b070-4519-11e9-adc8-00155d64ad0d)" failed: rpc error: code = Unknown desc = failed to create a sandbox for pod "kube-proxy-98n6n": Error response from daemon: Conflict. The container name "/k8s_POD_kube-proxy-98n6n_kube-system_3584b070-4519-11e9-adc8-00155d64ad0d_0" is already in use by container "b23cadfb1461d3a3ecf1a19272c674c039e6e3b484ce11522f9c0233a44f0916". You have to remove (or rename) that container to be able to reuse that name.
E0312 16:52:25.337439    1808 kuberuntime_manager.go:662] createPodSandbox for pod "kube-proxy-98n6n_kube-system(3584b070-4519-11e9-adc8-00155d64ad0d)" failed: rpc error: code = Unknown desc = failed to create a sandbox for pod "kube-proxy-98n6n": Error response from daemon: Conflict. The container name "/k8s_POD_kube-proxy-98n6n_kube-system_3584b070-4519-11e9-adc8-00155d64ad0d_0" is already in use by container "b23cadfb1461d3a3ecf1a19272c674c039e6e3b484ce11522f9c0233a44f0916". You have to remove (or rename) that container to be able to reuse that name.
E0312 16:52:25.346330    1808 pod_workers.go:190] Error syncing pod 3584b070-4519-11e9-adc8-00155d64ad0d ("kube-proxy-98n6n_kube-system(3584b070-4519-11e9-adc8-00155d64ad0d)"), skipping: failed to "CreatePodSandbox" for "kube-proxy-98n6n_kube-system(3584b070-4519-11e9-adc8-00155d64ad0d)" with CreatePodSandboxError: "CreatePodSandbox for pod \"kube-proxy-98n6n_kube-system(3584b070-4519-11e9-adc8-00155d64ad0d)\" failed: rpc error: code = Unknown desc = failed to create a sandbox for pod \"kube-proxy-98n6n\": Error response from daemon: Conflict. The container name \"/k8s_POD_kube-proxy-98n6n_kube-system_3584b070-4519-11e9-adc8-00155d64ad0d_0\" is already in use by container \"b23cadfb1461d3a3ecf1a19272c674c039e6e3b484ce11522f9c0233a44f0916\". You have to remove (or rename) that container to be able to reuse that name."

The part highlighted in bold was the root cause IMHO. I installed Docker for Windows on the server. I am at loss what the cause would be and hopefully be given guidance on a possible resolution. Thanks in advance.

**Comment by GOVYANSONG** [comment]
Rebuild K8S cluster

Note: to eliminate any incompatibility among docker, kubernetes, linux/windows, Hyper-V.

Host

Windows 10 v1809 
Azure VM size: D8_v3

VM#1

Windows Server 2019 Standard Evaluation v1809 build 17763
Architecture: amd64
docker: Docker CE for Windows v18.09.2 (bundled k8s: not installed, swarm: inactive, experimental: false)
K8S binaries for node: v1.13.4
Feature Hyper-V: enabled with CPU extensions
Feature Container: enabled


VM#2

Ubuntu 18.04.2 LTS
Kernel: 4.15.0-32-generic
Architecture: amd64
docker: Docker CE for Linux v18.09.3
K8S: v1.13.4
Once I rebuilt kubernetes cluster with following specs, the windows node was successfully registered on the master and all looked normal.

=================
K8S Networking

CNI: Flannel Host-Gateway (e.g. host-gw)

**Comment by GOVYANSONG** [comment]
But, I got following error in the powershell output screen for kube-proxy:

E0313 12:25:55.321446    7684 proxier.go:1041] Endpoint information not available for service default/win-webserver:. Not applying any policy

**Comment by GOVYANSONG** [comment]
after a restart, now i received the same error posted originally:

E0312 16:51:54.394060 1808 server.go:730] Kubelet needs to run as uid 0. It is being run as -1
E0312 16:51:58.265321 1808 remote_runtime.go:96] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-proxy-98n6n": Error response from daemon: network host not found

**Comment by GOVYANSONG** [comment]
I run docker network ls and saw the entry for cbr0 l2bridge

**Comment by raymak23** [comment]
I was able to successfully join windows node to join Kubernetes 1.14 cluster. Check this tutorial out: https://blog.tekspace.io/setup-windows-node-with-kubernetes-1-14/

**Comment by GOVYANSONG** [comment]
although I still saw error messages in kubelet PowerShell window, the cluster itself with windows node actually works fine. I can run the sample win web server without any issue. Just remember to use docker enterprise on win2019 server.

**Comment by GOVYANSONG** [comment]
Closing
