### ISSUE TITLE
UAC vs. Authenticode(?) issue

### ISSUE THREAD

**Issue by alfredmyers** [MicrosoftDocs/Virtualization-Documentation#1012]
For some reason I still haven't figured out, following the steps outlined in the article brings up an UAC consent dialog bot that states VMCreatee.exe is from an unknown publisher.
I did some digging (signtool.exe, CAPI2 event logs) and found out that timestamp used for signing has since gone outdated.
From what I understood from "signtool verify /v VMCreate.exe" output the file is correctly signed by Microsoft, so why das UAC show Unknown Publisher?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10344c5d-274e-de75-ecb6-11d53a377986
* Version Independent ID: 4cea53b8-1864-f12b-f0d9-f208743475c8
* Content: [Create a Virtual Machine with Hyper-V](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/quick-create-virtual-machine#before-windows-10-creators-update)
* Content Source: [virtualization/hyper-v-on-windows/quick-start/quick-create-virtual-machine.md](https://github.com/Microsoft/Virtualization-Documentation/blob/master/virtualization/hyper-v-on-windows/quick-start/quick-create-virtual-machine.md)
* Product: **windows-10-hyperv**
* GitHub Login: @scooley

**Comment by yegle** [comment]
Just FYI I also got hit by this exact issue (VMCreate.exe is signed by unknown publisher).
