### ISSUE TITLE
Log in as User in container

### ISSUE THREAD

**Issue by MythreyaK** [MicrosoftDocs/Virtualization-Documentation#1015]
With either LCOW or with containers using MobyVM, how does one login as a user instead of the default root user?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87364a28-e1df-eda3-2480-11556ac578be
* Version Independent ID: eebcf9e0-2ff4-d3b5-687f-682adf0b005b
* Content: [Linux Containers on Windows](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/linux-containers)
* Content Source: [virtualization/windowscontainers/deploy-containers/linux-containers.md](https://github.com/Microsoft/Virtualization-Documentation/blob/master/virtualization/windowscontainers/deploy-containers/linux-containers.md)
* Service: **windows-containers**
* Product: **windows-containers**
* GitHub Login: @scooley

**Comment by alexhiggins732** [comment]
You don't. Docker supports the USER command while building an image. You can also run the container as an image (https://stackoverflow.com/questions/35734474/connect-to-docker-container-as-user-other-than-root). You cannot however login as a user which means if you want to run an using a windows account you actually use a built-in windows account and set up GMSAs (https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/manage-serviceaccounts) which are used as the identity to communicate with network resources, which of course has caveats (including not working/partially working with all but the absolute latest windows releases, requiring the container host being part of AD, making some custom AD configurations for those hosts, creating custom GSMA accounts, etc).

**Comment by MythreyaK** [comment]
Ahh yes, that makes sense. Thank you for clearing that up!
