### ISSUE TITLE
Totally messes up networking

### ISSUE THREAD

**Issue by LesF** [MicrosoftDocs/Virtualization-Documentation#1048]
This page needs to explain what to do when Hyper-v hijacks your ethernet connection as in internal network and doesn't allow you to change it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1df65b2d-24ba-71b0-0648-14c21f5b1b26
* Version Independent ID: a89c84df-6ef7-66a9-eec1-35ba94afdb1b
* Content: [Enable Hyper-V on Windows 10](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v#feedback)
* Content Source: [virtualization/hyper-v-on-windows/quick-start/enable-hyper-v.md](https://github.com/Microsoft/Virtualization-Documentation/blob/master/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v.md)
* Product: **windows-10-hyperv**
* GitHub Login: @scooley

**Comment by JeevanKulkarniMS** [comment]
If you're talking about the internet speed affected after you create the virtual switch, a simple reboot of the host machine should set it right. After you create the virtual switch, close Hyper-V manager and reboot.
