### ISSUE TITLE
Docker Engine 19.03 is error?

### ISSUE THREAD

**Issue by zhongjixiuxing** [MicrosoftDocs/Virtualization-Documentation#1054]
According docker engine office release docs, docker engine newest version is 18.09.5. docker engine 19.03 where can get ?

https://docs.docker.com/engine/release-notes/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e6c2025-a694-e5cb-f921-537017b62b93
* Version Independent ID: 81d77710-88ee-239f-e130-02272ff9b48d
* Content: [GPU Acceleration in Windows Containers](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/gpu-acceleration#feedback)
* Content Source: [virtualization/windowscontainers/deploy-containers/gpu-acceleration.md](https://github.com/Microsoft/Virtualization-Documentation/blob/master/virtualization/windowscontainers/deploy-containers/gpu-acceleration.md)
* GitHub Login: @cwilhit

**Comment by cwilhit** [comment]
@zhongjixiuxing 19.03 has not been released yet. As the docs point out in the `important` section:

"Formal Docker support is scheduled for the **upcoming** Docker EE Engine 19.03 release. Until then, the upstream source for Docker contains the necessary bits."

**Comment by zhongjixiuxing** [comment]
Soga ~~
