### ISSUE TITLE
Document ports 839 and 88 as required to be opened in firewall on the host

### ISSUE THREAD

**Issue by ivansharamok** [MicrosoftDocs/Virtualization-Documentation#1076]
**Description**

When running a firewall on the host that automatically blocks all traffic, it's mandatory to open ports 389 and 88 for containers hooked up with gMSA be able to talk to domain controllers and pass Kerberos tokens.
Please list these ports in the gMSA related documentation.

**Comment by rpsqrd** [comment]
We just published a troubleshooting section for firewall configuration. It should be live on https://aka.ms/containers/identity shortly.

Thanks for the suggestion!
