### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by sapatelbaps** [MicrosoftDocs/Virtualization-Documentation#1127]
Please update the URLs of this page.

Thanks.
Sandip

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07e835b4-908e-4566-7420-b5f3cefffa91
* Version Independent ID: 19a908fc-3526-eec2-85c6-d9c7a04e97db
* Content: [Hyper-V on Windows 10](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/#feedback)
* Content Source: [virtualization/hyper-v-on-windows/index.md](https://github.com/Microsoft/Virtualization-Documentation/blob/master/virtualization/hyper-v-on-windows/index.md)
* Service: **windows-10-hyperv**
* Product: **windows-10-hyperv**
* GitHub Login: @scooley

**Comment by cwilhit** [comment]
Thanks, fixed!
