### ISSUE TITLE
Misleading information given regarding use of overlay networks. 

### ISSUE THREAD

**Issue by mrhockeymonkey** [MicrosoftDocs/Virtualization-Documentation#1148]
** Description**
In the table (link below), under th e"overlay" row its states that for container-to-external connectivity one should attach a second container endpoint connected to a NAT network. However this is not possible as overlay networks and nat networks have a different scope that cannot be mixed

```powershell
PS D:\> docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
klxp794bx1dz        ingress             overlay             swarm
250269d47835        nat                 nat                 local
```

If you try to attach a net network to a swarm service you will get the below error:

```powershell
failed to create service ds_factory_test: Error response from daemon: could not find the corresponding predefined swarm network: network nat not found
```

I beleive this is by design and that this document is mistaken in suggesting this can be done. I would love to be able to do this though so if I'm missing something here please do let me know. 

Link to doc: https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/live/virtualization/windowscontainers/container-networking/network-drivers-topologies.md#network-topologies-and-ipam

**Comment by pjh1974** [comment]
I take it from the lack of replies that there is still no solution to container-to-external connectivity.  This, in my opinion, makes stacks and services unusable in many scenarios e.g. migration of a brownfield to containerization or new services that are dependent on external data sources.  This is either a massive oversight or a deal-breaking technical limitation.

**Comment by mrhockeymonkey** [comment]
Hey @pjh1974 I actually recently patched windows up to the August Cumulative update and updated Docker EE to 19.03.2 and it seems to have fixed the issue for me. I can now talk to external services from within my overlay network. Its worth noting that ping does not work but api calls do. 

Hope that helps.

**Comment by pjh1974** [comment]
@mrhockeymonkey Thanks for the response.  It seems that relying on ping was my downfall.  How studpid of me to rely on a network diagnostic tool to diagnose a network problem! For the record, this is also working on Windows 10 (1903).
