### ISSUE TITLE
Problem with service account ServicePrincipals 

### ISSUE THREAD

**Issue by JamieTemple** [MicrosoftDocs/Virtualization-Documentation#1156]
Hello,

First of all - thanks - this is by far the most comprehensive documentation that exists on this subject :)

So I have a particularly complex legacy application that I am (trying) to run in Windows containers on a Service Fabric cluster.

I have set up Azure Active Directory Domain Services to allow users to log in. The SF cluster ARM template includes scripts for joining the domain, and setting up AD (GMSA) service accounts, then creating the credentialspecs.

`nltest /sc_verify:mydomain.com` and `klist get krbtgt` report that the container is connected to the domain, and `Test-ADServiceAccount -Identity myGMSAAccountName` comes back with `True`.

Additionally, looking in the Security event logs, just after my WCF service starts up, I can see "An account was successfully logged on" and "Special privileges assigned to new logon" - which suggests to me that my WCF service (running under IIS) is correctly using the LocalSystem account.

The problem arises when the client application attempts to log-in to the server.

After the user tries to log in, it returns a message "Unable to log in to the system. The server has rejected the client credentials."

If I then look in the Security event logs on my container again, I can see the rejected login from Microsoft-Windows-Security-Auditing:

```
An account failed to log on....

Subject:
  Security ID:            S-1-0-0
  Account Name:           -
  Account Domain:         -
  Logon ID:               0x0

Logon Type:                        3

Account For Which Logon Failed:
  Security ID:            S-1-0-0
  Account Name:           myclientusername
  Account Domain:         mydomain.com

Failure Information:
  Failure Reason:         %%2313
  Status:                 0xc000006d
  Sub Status:             0xc0000064

Process Information:
  Caller Process ID:      0x0
  Caller Process Name:    -

Network Information:
  Workstation Name:       myclientpcname
  Source Network Address: -
  Source Port:            -

Detailed Authentication Information:
  Logon Process:          NtLmSsp
  Authentication Package: NTLM
  Transited Services:     -
  Package Name (NTLM only):       -
  Key Length:             0
```

... I guess the part that particularly bothers me here is the "Subject" section. From what I can tell, I would expect this to be populated with the GMSA account details (although I might be wrong).

... so I've been exploring the very last point in this article (as my SF cluster certainly has a load balancer in front of it).

Unfortunately, I'm no AD expert, and so have been struggling to figure out the meaning of **"Clients will locate the gMSA account by the name at which they reach your application."**.

From what I can tell, I need to ensure that when I create the service account, the Service Principals list I provide when setting up the GMSA needs to include the endpoint that my client tries to connect to my server on.

The list currently looks like this:
  http/containerhost
  http/containerhost.mydomain.com
  http/containerhost.mydomain.com/mydomain.com
  http/containerhost/mydomain.com
  net.tcp/containerhost
  net.tcp/containerhost.mydomain.com
  net.tcp/containerhost.mydomain.com/mydomain.com
  net.tcp/containerhost/mydomain.com

The credentialspec file used by docker contains 2 GMSA records:
{
  "Name": "containerhost",
  "Scope": "mydomain.com"
},
{
  "Name": "containerhost",
  "Scope": "MYDOMAIN"
}

... it might be the fact that I've just spent 12 hours straight working on this, but I've run out of ideas, and would really appreciate some pointers on how to get to the bottom of this.

Thanks in advance - Jamie.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6cbabcb-0910-3082-fe93-bafef68f2faa
* Version Independent ID: 6efd7af0-a3f2-9d4a-cee1-722caf001cdd
* Content: [Group Managed Service Accounts for Windows containers](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/manage-serviceaccounts#feedback)
* Content Source: [virtualization/windowscontainers/manage-containers/manage-serviceaccounts.md](https://github.com/Microsoft/Virtualization-Documentation/blob/master/virtualization/windowscontainers/manage-containers/manage-serviceaccounts.md)
* Service: **windows-containers**
* Product: **windows-containers**
* GitHub Login: @rpsqrd

**Comment by rpsqrd** [comment]
Hey Jamie,

Thanks for all your awesome troubleshooting details. I think the best place for us to start is to look at why it isn't using Kerberos.

> Unfortunately, I'm no AD expert, and so have been struggling to figure out the meaning of "Clients will locate the gMSA account by the name at which they reach your application."

By this statement, we mean that for Kerberos to work, a client has to know which resource it needs to obtain a ticket for. The SPN defines the protocol and DNS name at which you may reach an application. If you access your container at https://mywebsite.com/ (even if it's hosted on containerhost.mydomain.com internally, behind a load balancer), you need an `http/mywebsite.com` SPN on the gMSA so the client can find it when querying AD for the resource.

It looks like your gMSA is configured to work if the client accesses the IIS app at https://containerhost or https://containerhost.mydomain.com -- is that how your client is configured?

It would also help to confirm the IIS app pool settings in the container to ensure the app pool is set to Network Service or Local System. You'd want to have a [RUN command in your Dockerfile that configures this](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/manage-serviceaccounts#run-an-iis-app-pool-as-network-service).

**Comment by JamieTemple** [comment]
Hey Ryan - thanks for coming back to me.

I wouldn't quite say that I've "figured it out", but I do now have things working.

... so the client connects to a .net TCP endpoint ... it goes:

```
local client
  => Azure DNS
    => Azure IP
      => Azure Load Balancer
        => Service Fabric node
          => Container
            => My legacy WCF services hosted in IIS.
```
Here is what was required:

* Register a real domain name (matching what was already set up on AADDS)
* Set up Azure DNS - point it at the load balancer IP address of the SF cluster
* Make sure the cluster is deployed using a 2019 server image (so I can have 1 GMSA rather than 1 per host)
* Update my cluster deployment custom scripts to ensure that this single GMSA exists (and creates it if its missing)

```
try {
	Get-ADServiceAccount `
		-Identity $GMSAAccountName `
		-Credential $psCred
}
catch {
	$acPrincipals = @(
	  "Domain Controllers",
	  "CN=AAD DC Administrators,OU=AADDC Users,${adDomainDesc}",
	  "CN=${containerHostName},OU=AADDC Computers,${adDomainDesc}"
	  $containerHostDistinguishedName
	)

	# These are all of the different "Service Principal Name"s that this service account can be recognised by.
	# Note - this list assumes that the domain name consists of 2 elements - e.g. mydomain.com
	$servicePrincipalNames = @(
	  "host/${GMSAAccountName}",
	  "host/${GMSAAccountName}.${domain}"
	)

	New-ADServiceAccount `
		-Name $GMSAAccountName `
		-DNSHostName "${GMSAAccountName}@${domain}" `
		-ServicePrincipalNames $servicePrincipalNames `
		-PrincipalsAllowedToRetrieveManagedPassword $acPrincipals `
		-Credential $psCred
}

```

* Also update this script to create a credential spec using this "shared by all containers" GMSA.

... once this was done, I just needed to update the `Hostname` attribute of the `ContainerHostPolicies` in my Service Fabric `ApplicationManifest.xml`, and we were up and running :)

... on reflection, I suspect that part of my problem was my debugging technique - I was installing the client app on the SF node running the container, and configuring it to connect to `net.tcp:/172.x.xx:808/MyServiceName` (where MyServiceName was the application running in IIS.

I now have things working, having installed the client on my pc, and configured it to connect to `net.tcp:/myservice.mydomain.com:808/MyServiceName`.

... even though we're all good now, I'm still not sure how I would configure the SPNs to allow the client to be installed on the node and connect using `net.tcp:/172.x.xx:808/MyServiceName` ... I suspect that it looks something like `host/MyService/172.x.x.x:808.mydomain.com` ... but (again) I'm probbably wrong!

... anyway - thanks for coming back to me - hopefully these notes might help someone else.

  Jamie.

**Comment by rpsqrd** [comment]
Awesome, good to hear. The default config in Windows prevents the use of Kerberos when communicating with an IP address, so it's definitely recommended to use DNS names where possible, even if that means using a HOSTS file on your client to mock it during quick tests.

As a tip for future SPN configuration, it only cares about the protocol, hostname and port. You don't have to register specific entries for the subdirectories like MyServiceName, so `host/myservice:808` and `host/myservice.mydomain.com:808` should be sufficient.

Hope this helps! Thanks for sharing your steps for others to learn from.

**Comment by JamieTemple** [comment]
Ryan,

Thanks for the clarification - it really helped.

I've just had a "lightbulb" moment, that has resulted in me modifying my cluster deployment script from:

```
	# These are all of the different "Service Principal Name"s that this service account can be recognised by.
	$servicePrincipalNames = @(
	  "host/${$GMSAAccountName}",
	  "host/${$GMSAAccountName}.${domain}"
	)
```

to:

```
	# The container name will be set by ServiceFabric, according to `Hostname`, which MUST match The
	# GMSA account that the container runs under.
	# See: https://docs.microsoft.com/en-gb/azure/service-fabric/service-fabric-setup-gmsa-for-windows-containers
	$containerName = $GMSAAccountName;

	# These are all of the different "Service Principal Name"s that this service account can be recognised by.
	$servicePrincipalNames = @(
	  "host/${$containerName}",
	  "host/${$containerName}.${domain}"
	)
```

... functionally identical, but if anyone (like me!) was confused by sticking a GMSA into an SPN, then I think this clears things up :)

  Jamie.

**Comment by rpsqrd** [comment]
Makes perfect sense.

Just remember as you scale your containers out and have multiple containers using the same gMSA, you'll want to add SPNs for each container name. If you add a load balancer / reverse proxy in front of the containers, you'd drop the individual container names and add an SPN for the load balancer instead.

**Comment by JamieTemple** [comment]
Ryan,

In which case, I think things are working by fluke - I already have 5 containers running on 5 nodes behind my load balancer :)

The DNS record routes requests from `service.mydomain.com` to the load balancer.

The load balancer then routes all incoming requests on port 808 to my nodes (that have containers with port 808 open).

I have set up a GMSA - let's call it `mycontainerserviceaccount`.

So each of the containers appear as `mycontainerserviceaccount.mydomain.com`

This is also the details that appear in my credentials spec (obviously!).

Now, the (currently working) clients access things use an endpoint of: `net.tcp://service.mydomain.com:808/MyWCFService`

According to your previous post, I'm thinking that in this setup, I should specify the SPN on the GMSA as `host/service.mydomain.com` - i.e. the name by which clients will be accessing my services.

This makes perfect sense ... but is not how I have them set up ... but they still work !?!?!

Currently, my SPNs look like:

```
"host/mycontainerserviceaccount", 
"host/mycontainerserviceaccount.mydomain.com"
```

So I'm going to guess here that the first of my SPNs is not used, but the second one is 'close-enough' to `host/service.mydomain.com` for things to work

Is that a good guess? ;)

  Jamie.

**Comment by rpsqrd** [comment]
I bet you’re right — there’s fuzzy matching logic with SPNs so it might’ve just been close enough to work. Ah, the fun of identity systems!

________________________________
