### ISSUE TITLE
Does it need any other settings? I followed this page to have a try, but it failed.

### ISSUE THREAD

**Issue by SoldierProgrammer** [MicrosoftDocs/Virtualization-Documentation#1157]
When I do the commond below:
docker run --isolation process --device class/5B45201D-F2F2-4F3B-85BB-30FF1F953599 mcr.microsoft.com/windows:1903

The powershell echo nothing and the powershell is blocked.
Then I open a new powershell to look the container status is Created. 
CONTAINER ID        IMAGE                            COMMAND                    CREATED              STATUS              PORTS               NAMES
32893f14ec18        mcr.microsoft.com/windows:1903   "c:\\windows\\system32…"   About a minute ago   Created                                 friendly_dirac

My environment is :
Host OS: Windows 10 Professional 1903
Driver Model: 2.6 WDDM
Driver: NVIDIA GeForce GTX 1070

Client: Docker Engine - Community
 Version:           19.03.0-beta3
 API version:       1.40
 Go version:        go1.12.4
 Git commit:        c55e026
 Built:             Thu Apr 25 19:05:10 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.0-beta3
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.4
  Git commit:       c55e026
  Built:            Thu Apr 25 19:06:34 2019
  OS/Arch:          windows/amd64
  Experimental:     true

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e6c2025-a694-e5cb-f921-537017b62b93
* Version Independent ID: 81d77710-88ee-239f-e130-02272ff9b48d
* Content: [GPU Acceleration in Windows Containers](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/gpu-acceleration#feedback)
* Content Source: [virtualization/windowscontainers/deploy-containers/gpu-acceleration.md](https://github.com/Microsoft/Virtualization-Documentation/blob/master/virtualization/windowscontainers/deploy-containers/gpu-acceleration.md)
* GitHub Login: @cwilhit

**Comment by cwilhit** [comment]
The command you're executing right now should enter a terminal and immediately exit. This is not happening? Have you tried running the container interactively? Execute the following command:

`docker run -it --isolation process --device class/5B45201D-F2F2-4F3B-85BB-30FF1F953599 mcr.microsoft.com/windows:1903 powershell.exe`

**Comment by SoldierProgrammer** [comment]
https://github.com/moby/moby/issues/38306

That's the problem!!

**Comment by cwilhit** [comment]
Glad you found the solution! Thanks for linking to it.
