### ISSUE TITLE
How do I switch documentation language back to English?

### ISSUE THREAD

**Issue by prob1995** [MicrosoftDocs/Virtualization-Documentation#1173]
[請在此輸入您的意見]
How do I switch documentation language back to English?

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 87364a28-e1df-eda3-2480-11556ac578be
* Version Independent ID: eebcf9e0-2ff4-d3b5-687f-682adf0b005b
* Content: [Windows 上的 Linux 容器](https://docs.microsoft.com/zh-tw/virtualization/windowscontainers/deploy-containers/linux-containers#feedback)
* Content Source: [virtualization/windowscontainers/deploy-containers/linux-containers.md](https://github.com/MicrosoftDocs/Virtualization-Documentation-Private.zh-tw/blob/live/virtualization/windowscontainers/deploy-containers/linux-containers.md)
* Service: **windows-containers**
* Product: **windows-containers**
* GitHub Login: @scooley

**Comment by scooley** [comment]
The easiest way is to change language in the URL.  replace language section with "en-us".
