### ISSUE TITLE
You sure that Install-WindowsCapability is a valid powershell command?

### ISSUE THREAD

**Issue by Vaccano** [MicrosoftDocs/Virtualization-Documentation#1178]
I tried to run Install-WindowsCapability as indicated under "Create a credential spec", point #1, bullet 2.

My powershell does not recognize that command.  I googled it to find out what I needed to do to get the command.  The command only had 3 results.  This page was one of them.  

There is an "Add-WindowsCapability".  Did you mean that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6cbabcb-0910-3082-fe93-bafef68f2faa
* Version Independent ID: 6efd7af0-a3f2-9d4a-cee1-722caf001cdd
* Content: [Group Managed Service Accounts for Windows containers](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/manage-serviceaccounts)
* Content Source: [virtualization/windowscontainers/manage-containers/manage-serviceaccounts.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/manage-containers/manage-serviceaccounts.md)
* Service: **windows-containers**
* Product: **windows-containers**
* GitHub Login: @rpsqrd

**Comment by rpsqrd** [comment]
Great catch! The correct syntax is:

```powershell
Add-WindowsCapability -Online -Name 'Rsat.ActiveDirectory.DS-LDS.Tools~~~~0.0.1.0'
```

I've submitted a PR to get the doc updated.
