### ISSUE TITLE
Run Linux Images

### ISSUE THREAD

**Issue by kolexinfos** [MicrosoftDocs/Virtualization-Documentation#1223]
Is there a way to switch to running a Linux Container on the Windows Server 2016? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a1c4c54-7721-58ce-f77d-be0ef0c687bf
* Version Independent ID: 70e52446-1c7b-78ff-67f2-1f6c0d058788
* Content: [Windows and Linux Containers on Windows 10](https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/run-your-first-container)
* Content Source: [virtualization/windowscontainers/quick-start/run-your-first-container.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/quick-start/run-your-first-container.md)
* Service: **windows-containers**
* Product: **windows-containers**
* GitHub Login: @cwilhit

**Comment by cwilhit** [comment]
There is not. We do support running Linux containers on Windows 10 through Docker Desktop for Windows (more info here: https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-10-linux)

**Comment by kolexinfos** [comment]
I had to install a Windows 10(1903) D2s_v3 machine, enabled Hyper-V and Containers Windows Features, then installed Docker Desktop for Windows to this to work.

**Comment by cwilhit** [comment]
Yep, glad you found a solution!
