### ISSUE TITLE
Unable to pull nano server images

### ISSUE THREAD

**Issue by saeedonweb** [MicrosoftDocs/Virtualization-Documentation#1239]
I tried following the steps outlined here but was unable to pull a nanoserver image. Keep getting this error: docker : no matching manifest for windows/amd64 10.0.14393 in the manifest list entries

When I searched online, I found that Nano server is no longer supported by dockers. This page should also be updated

Saeed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a1c4c54-7721-58ce-f77d-be0ef0c687bf
* Version Independent ID: 70e52446-1c7b-78ff-67f2-1f6c0d058788
* Content: [Windows and Linux Containers on Windows 10](https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/run-your-first-container#feedback)
* Content Source: [virtualization/windowscontainers/quick-start/run-your-first-container.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/quick-start/run-your-first-container.md)
* Service: **windows-containers**
* Product: **windows-containers**
* GitHub Login: @cwilhit

**Comment by cwilhit** [comment]
Nanoserver is definitely a supported container image and we are publishing monthly updates. What is your host OS version? Based on the error you saw from Docker, I suspect you're running a host OS version that we no longer support Nanoserver version for.

Check out the image repo on Docker Hub: https://hub.docker.com/_/microsoft-windows-nanoserver

There is a table of the supported tag listings and the associated OS versions they pair to.

**Comment by saeedonweb** [comment]
I am using Windows Server 2016 Datacenter build 14393

**Comment by cwilhit** [comment]
Ok, thanks. If you look at the table [here](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility#windows-server-2016-host-os-compatibility) and compare it to the table [here](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/base-image-lifecycle), you'll see the "Nanoserver, OS version 14393" reached end of life on 10/09/2018.

There are a few options for you:

1. (recommended) run Windows Server Core container image instead.
2. Update your server host to a newer edition such as Windows Server 2019
3. Create a Windows Server guest VM with a newer edition and run the container there instead.

**Comment by saeedonweb** [comment]
Thank you for your assistance!

**Comment by cwilhit** [comment]
You're welcome!
