### ISSUE TITLE
where the '<source-vip>' defined

### ISSUE THREAD

**Issue by wangrong2012** [MicrosoftDocs/Virtualization-Documentation#1240]
PS C:\k&gt; nssm set kube-proxy AppParameters --v=4 --proxy-mode=kernelspace --feature-gates="WinOverlay=true" --hostname-override=&lt;hostname&gt; --kubeconfig=c:\k\config --network-name=vxlan0 --source-vip=&lt;source-vip&gt; --enable-dsr=false --log-dir=&lt;log directory&gt; --logtostderr=false

where the '&lt;source-vip&gt;' defined? 

Following are content of my two json files:
PS C:\k> cat .\sourceVipRequest.json                                                                                                                                      
        {"cniVersion": "0.2.0", "name": "vxlan0", "ipam":{"type":"host-local","ranges":[[{"subnet":"10.244.5.0/24"}]],"dataDir":"/var/lib/cni/networks"}}                    

PS C:\k> cat .\sourceVip.json                                                                                                                                             
{                                                                                                                                                                         
    "code": 100,                                                                                                                                                          
    "msg": "error reading network config: invalid character '茂' looking for beginning of value"                                                                          
} 
I don't understand why the 'sourceVip.json' failed?
thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fb2c058-d023-3593-d9b3-65dca40d0fc9
* Version Independent ID: 21403afc-9338-597b-8a69-63c20b73bd05
* Content: [Running Kubernetes as a Windows Service](https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/kube-windows-services?tabs=ManagementIP#feedback)
* Content Source: [virtualization/windowscontainers/kubernetes/kube-windows-services.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/kubernetes/kube-windows-services.md)
* Product: **containers**
* GitHub Login: @daschott
* Microsoft Alias: **daschott**

**Comment by wangrong2012** [comment]
Anyone can help?

**Comment by daschott** [comment]
This is generated by the host-local.exe IPAM plugin, if I am not mistaken. It is generated by the scripts here: https://github.com/microsoft/SDN/blob/master/Kubernetes/windows/helper.psm1#L176

**Comment by wangrong2012** [comment]
Solved the problem by "#  chcp 437".
