### ISSUE TITLE
The command line for Windows 10 that is provided does not appear to do anything

### ISSUE THREAD

**Issue by KirkMunro** [MicrosoftDocs/Virtualization-Documentation#1255]
When I run this locally, and then click on the Docker icon in my system tray, the "Switch to..." menu item does not change:

`& $Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchDaemon .`

Having commands that allow you to identify the current daemon that the CLI is pointing to along with a working command that allows you to point the CLI to a different daemon is essential for automation. If you could provide these details in this article, it would be really helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e09e1b22-1344-d7b9-9462-dc4c2e160e86
* Version Independent ID: f6411e97-4419-1209-56ad-9140ceb37329
* Content: [Windows and Linux Containers on Windows 10](https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=Windows-10-Client#feedback)
* Content Source: [virtualization/windowscontainers/quick-start/set-up-environment.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/quick-start/set-up-environment.md)
* Service: **windows-containers**
* Product: **windows-containers**
* GitHub Login: @cwilhit

**Comment by cwilhit** [comment]
That looks like a bug in Docker CLI: https://github.com/docker/for-win/issues/1269. That issue got stale and was closed by a bot, but I don't think it's been fixed. I'd suggest poking there.

As for telling which daemon the docker client is currently pointing at, you can determine this by querying `docker version` and looking for the OS/arch displayed under the `server` print out. It'll say whether it's Windows or Linux.

**Comment by KirkMunro** [comment]
Thanks @cwilhit, that resolves this issue, and I've moved my discussion over to the stale/closed issue and re-opened it.
