### ISSUE TITLE
this doc seems out of date,

### ISSUE THREAD

**Issue by scyto** [MicrosoftDocs/Virtualization-Documentation#1257]
when i run docker network ls (in linux conatiner mode) it appears that the nat is now called bridge with driver bridge.

also it appears that any container bound to the host network is not actually NAT'd to outside and thus host network doesn;t work like a true host on linux as it is unreachable?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3be8120-7fc1-9818-53d4-61e7d3f36175
* Version Independent ID: 38825f46-278d-7da0-d538-a1c7d1d96557
* Content: [Windows container networking](https://docs.microsoft.com/en-us/virtualization/windowscontainers/container-networking/architecture#feedback)
* Content Source: [virtualization/windowscontainers/container-networking/architecture.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/container-networking/architecture.md)
* Service: **windows-containers**
* Product: **windows-containers**
* GitHub Login: @JMesser81

**Comment by daschott** [comment]
This doc is for Windows Containers, not Linux containers. Windows containers use NAT network mode.

Host networking mode is not supported on Windows, I am adding this to the doc. Thanks for the pointer!

**Comment by scyto** [comment]
ha i missed that, sorry, closing :-) (and thanks for the doc update too!)
(perhaps a good article in same area detailing the different containers modes different network architectures would be good one day?)

**Comment by daschott** [comment]
Yes, that is a good suggestion and will be added under "Network topologies and drivers" page. Hoping to add this by the end of the year, please check back then again or open up an issue otherwise!
