### ISSUE TITLE
Outdated article?

### ISSUE THREAD

**Issue by JerrelAjoeb** [MicrosoftDocs/Virtualization-Documentation#1259]
The date of this blog is 03/20/2019 and High Availability is related to MS Hyper-V Server 2008 R2?
Is this correct or an outdated article?
Furthermore it would be clear to add the year to "calendar Q4".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a399fc7d-bea5-6672-443b-9da44a261463
* Version Independent ID: fd9510c6-d0de-4789-7f7c-db271b6c8aa0
* Content: [Microsoft’s new VDI licensing: VDI Suites](https://docs.microsoft.com/en-us/virtualization/community/team-blog/2009/20090713-microsofts-new-vdi-licensing-vdi-suites#feedback)
* Content Source: [virtualization/community/team-blog/2009/20090713-microsofts-new-vdi-licensing-vdi-suites.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/community/team-blog/2009/20090713-microsofts-new-vdi-licensing-vdi-suites.md)
* GitHub Login: @scooley

**Comment by JerrelAjoeb** [comment]
Apologies for the fact I've overlooked that this is a blog from 2009. Please remove my feedback.

**Comment by BenjaminArmstrong** [comment]
Closing
