### ISSUE TITLE
mcr.microsoft.com/windows:1809 URL is change

### ISSUE THREAD

**Issue by kkbruce** [MicrosoftDocs/Virtualization-Documentation#1265]
Old URL: https://hub.docker.com/_/microsoft-windowsfamily-windows and get HTTP 404.
New URL: https://hub.docker.com/_/microsoft-windows-base-os-images

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e6c2025-a694-e5cb-f921-537017b62b93
* Version Independent ID: 81d77710-88ee-239f-e130-02272ff9b48d
* Content: [GPU Acceleration in Windows Containers](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/gpu-acceleration#feedback)
* Content Source: [virtualization/windowscontainers/deploy-containers/gpu-acceleration.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/deploy-containers/gpu-acceleration.md)
* GitHub Login: @cwilhit

**Comment by cwilhit** [comment]
Good catch. It should redirect to https://hub.docker.com/_/microsoft-windows

We'll get a fix in for this soon. Thank you!

**Comment by cwilhit** [comment]
Fixed.
