### ISSUE TITLE
Windows version 1607 won't work

### ISSUE THREAD

**Issue by jwbeck** [MicrosoftDocs/Virtualization-Documentation#1268]
According to Docker's current documentation ( https://docs.docker.com/docker-for-windows/install/ ), the minimum Windows 10 build to install Docker Desktop for Windows is build 15063, which I believe is version 1703. So I don't there is any way to run Docker on Windows version 1607, and therefore you cannot run windows containers either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9682caf3-5fc4-54e6-d841-8cb6c16bbc4f
* Version Independent ID: 6c99e2e3-eafe-a91e-9c26-8d5845cc0b7f
* Content: [Windows Container Requirements](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/system-requirements#feedback)
* Content Source: [virtualization/windowscontainers/deploy-containers/system-requirements.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/deploy-containers/system-requirements.md)
* Product: **windows-containers**
* GitHub Login: @taylorb-microsoft
* Microsoft Alias: **taylorb**

**Comment by ashenm** [comment]
Technically, the Docker Community Edition [2.0.0.2 2019-01-16](https://docs.docker.com/docker-for-windows/#docker-desktop-community-2101) or [prior](https://docs.docker.com/docker-for-windows/#stable-releases-of-2018) should work with Windows Anniversary Update (14393) x64 Pro, Enterprise, or Education.

However, if you prefer an actively maintained version of Docker, the [Docker Toolbox](https://docs.docker.com/toolbox/overview/) would be premier option for depreciated versions and previous generations of Windows.

**Comment by jwbeck** [comment]
I think the Docker Toolbox runs docker in a linux VM, which means no Windows containers.

**Comment by ashenm** [comment]
@jwbeck Yes, that would the price you would have to bear, in which case you could either:
- Use the Community Edition(s) I have mentioned in the [previous](https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/1268#issuecomment-548771855) comment, or
- Simply upgrade Windows to a more recent supported version

**Comment by jwbeck** [comment]
Thank you @ashenm for the info, it was more clear after your comments. Docker and Microsoft are coming out with new versions frequently, we should make sure that the two are in sync.
