### ISSUE TITLE
Need to "SetSPN" or servicePrincipalName on gMSA account.

### ISSUE THREAD

**Issue by RobertLivermore** [MicrosoftDocs/Virtualization-Documentation#1341]
I encountered container bound to a transparent network encounted runtime problems when the program interacts with SSPI/Integrated Security/Kerberos token. This results in LSA Trust errors. The cause being new service accounts are not assigned a servicePrincipalName. 

Transparent networking uses DHCP/DNS to register the gMSA as the computer account. Adding the matching SPN HOST entries to Active directory corrects security.

Recommend adding a step to the documentation to configure the service principal name.

```` powershell
setspn -R $gMSAName
```` 
Reference
[Explanation of Service Principal Names in Active Directory](https://thebackroomtech.com/2018/08/21/explanation-of-service-principal-names-in-active-directory/)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6cbabcb-0910-3082-fe93-bafef68f2faa
* Version Independent ID: 6efd7af0-a3f2-9d4a-cee1-722caf001cdd
* Content: [Create gMSAs for Windows containers](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/manage-serviceaccounts?f=255&MSPPError=-2147217396#feedback)
* Content Source: [virtualization/windowscontainers/manage-containers/manage-serviceaccounts.md](https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/live/virtualization/windowscontainers/manage-containers/manage-serviceaccounts.md)
* Service: **windows-containers**
* Product: **windows-containers**
* GitHub Login: @rpsqrd

**Comment by rpsqrd** [comment]
Thanks for sharing this feedback! We do call out in the [Create a group Managed Service Account](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/manage-serviceaccounts?f=255&MSPPError=-2147217396#create-a-group-managed-service-account) section that the SPNs are not automatically set and suggest adding a `host/gMSAFQDN` SPN when you create the account. Is this what you're referring to? Or do you think we need to add this content elsewhere?

**Comment by RobertLivermore** [comment]
Correct. The SPN is not automatically set. I discovered a day or so later there is a parameter in the powershell 5.1 commandlet New-ADServiceAccount equivalent to SETSPN -R command line. Unless the parameter is specified, the AD gMSA object has an empty servicePrincipalNames attribute.

Recommend  adding the following attribute to the New-ADServiceAccount  commandlet

-ServicePrincipalNames @("HOST/$accountName","HOST/$($accountName).$DnsZone")

Where $accountName is the gMSA account Name  and $DnsZone matches the DNS Zone the gMSA will be uses. You need both the Netbios and the DNS qualified to be equivalent to SETSPN.exe -R

I found the content when searching for docker and gMSA and virtualization. No sure if there are other spots needed in MSDN library. If you are missing the AD service principal name, and your app uses LSA with Kerberos, the errors are nasty. Just want to help other avoid the pain.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by pronichkin** [comment]
I would never assign a "HOST" service class to any custom service account. HOST is very special thing, basically a placeholder for multiple common service classes. It's not always easy to see what service classes are included in HOST, so it's harder to troubleshoot (and can also potentially lead to misuse, either malicious or not.)

As a best practice, one should be as specific as possible, i.e. provide the exact service class that's needed for this service. (E.g. HTTP or MSSQLSVC.)

**Comment by smhmhmd** [comment]
>I would never assign a "HOST" service class to any custom service account.

[MS docs](https://learn.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/manage-serviceaccounts#create-a-group-managed-service-account) say:
"Set at least the host SPN, add other protocols as necessary."
