### ISSUE TITLE
Pb building the container file

### ISSUE THREAD

**Issue by nicopowergo** [MicrosoftDocs/Virtualization-Documentation#1359]
I have this issue using the above command line. Can someone pls tell me where I need to check?
 
PS D:\DockerDesktop\Virtualization-Documentation\windows-container-samples\asp-net-getting-started&gt; docker build -t my-asp-app
"docker build" requires exactly 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e38de4f3-3343-74cd-103a-fe12846ce7c3
* Version Independent ID: 6bf65efb-13eb-15d9-5aac-9d5cf9c1aa96
* Content: [Containerize a .NET Core App](https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/building-sample-app#feedback)
* Content Source: [virtualization/windowscontainers/quick-start/building-sample-app.md](https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/live/virtualization/windowscontainers/quick-start/building-sample-app.md)
* Service: **windows-containers**
* Product: **windows-containers**
* GitHub Login: @cwilhit
* Microsoft Alias: **crwilhit**

**Comment by cwilhit** [comment]
You're missing the path argument. In the docs we use `.` to mean the current directory opened in the terminal. If you're following the tutorial you should be able to do that same.

**Comment by nicopowergo** [comment]
Thanks a lot
