### ISSUE TITLE
Error while docker desktop for Windows 10 running as Windows

### ISSUE THREAD

**Issue by krchome** [MicrosoftDocs/Virtualization-Documentation#1391]
[Enter feedback here]
I have docker desktop for windows 10 installed with: Docker version 19.03.8, build afacb8b. Further, I have The 'experimental features' option in Docker Settings enabled and restarted the app 
Now then, following this document, however, if I issue the command : docker run --rm --platform linux busybox echo hello_world, it still gives me the error ""--platform" is only supported on a Docker daemon with experimental features enabled" 
![Error](https://user-images.githubusercontent.com/8474855/80035076-7cb8a480-8543-11ea-8be0-6cc2ea90dfa5.JPG)
My desktop also has Hyper V enabled which I confirmed on command window by typing system info that gives me output : Hyper-V Requirements: A hypervisor has been detected. Features required for Hyper-V will not be displayed.
However, if I switch to using Linux container mode, then it works fine and gives me the echoed output. 
Can someone advice on this ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51faeed1-77c1-c8c6-c097-6806a3bbdf85
* Version Independent ID: 84597429-d2e1-71ed-ee5d-fd2d66dcbff7
* Content: [Windows and Linux Containers on Windows 10](https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-10-linux)
* Content Source: [virtualization/windowscontainers/quick-start/quick-start-windows-10-linux.md](https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/live/virtualization/windowscontainers/quick-start/quick-start-windows-10-linux.md)
* Service: **windows-containers**
* Product: **windows-containers**
* GitHub Login: @taylorb-microsoft

**Comment by mupetmower** [comment]
You need to go under the Docker Engine tab and change the json element "experimental": false to true. I was confused by this at first as well. Once I changed that to true, it worked fine.

**Comment by krchome** [comment]
Hi mupetpower. Thanks very much for your advice. Yes it worked no problems

**Comment by StefanD986** [comment]
I had the weird behaviour that it still wouldn't work after enabling it both in the json and in the "engine" tab. 

What I did to resolve it was to disable experimental features on the engine tab (keep it enabled in the json), then restart docker and then enable experimental features on the engine tab again.
