### ISSUE TITLE
Upgrade script to create Generation 2 VMs

### ISSUE THREAD

**Issue by nebula-it** [MicrosoftDocs/Virtualization-Documentation#1399]
Hey @scooley,
Would it be possible to upgrade the VM Creation script [here](https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/master/hyperv-samples/benarm-powershell/Ubuntu-VM-Build/BaseUbuntuBuild.ps1) to create Generation 2 VMs. I tried to just switch the Generation Parameter in line 80 to 2, with that I was able to create the VM  but its gets stuck on this.
![image](https://user-images.githubusercontent.com/40148908/81494013-0366c480-925a-11ea-8a35-95fd0e2fe052.png)

**Comment by scooley** [comment]
Ben might be able to help - it's his script.

**Comment by nebula-it** [comment]
I think this issue can be closed. I've managed to create a PoSH function for this. [Here ](https://github.com/nebula-it/New-UnixVM)it is if anyone comes looking for the same,
