### ISSUE TITLE
Typo in "Check the container", step 4

### ISSUE THREAD

**Issue by PlymouthUniversitySolDev** [MicrosoftDocs/Virtualization-Documentation#1414]
The text reads : Check if the container can obtain a valid Kerberos Ticket Granting Ticket (TGT):
run "Klist get krbtgt"
This doesn't work for me. I Googled this command and found the Github page [https://github.com/MicrosoftDocs/Virtualization-Documentation/pull/1280/files](url) which indicates that "krbtgt" should be replaced with the name of the application.
I re-ran the command "klist get myapp" and the command succeeds.
Please update this page accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e73f574-a1a7-bf20-5c41-8af0cd64e933
* Version Independent ID: 51994784-e115-d0e9-ea77-69941cecfb40
* Content: [Troubleshoot gMSAs for Windows containers](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/gmsa-troubleshooting)
* Content Source: [virtualization/windowscontainers/manage-containers/gmsa-troubleshooting.md](https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/live/virtualization/windowscontainers/manage-containers/gmsa-troubleshooting.md)
* Service: **windows-containers**
* Product: **windows-containers**
* GitHub Login: @rpsqrd

**Comment by vrapolinario** [comment]
I apologize for taking so long to answer this, however, there is no typo here. The command klist get krbtgt works as expected and has been documented.
