### ISSUE TITLE
Typo in example setting storage options for Docker in daemon.json

### ISSUE THREAD

**Issue by seffyroff** [MicrosoftDocs/Virtualization-Documentation#1449]
[Enter feedback here]

For the daemon.json Docker configuration file, the syntax for setting storage options is "storage-opts":[], NOT "storage-opt":[] as stated on this page.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f436768e-3d52-102f-efd3-847e11f31317
* Version Independent ID: 2193c169-7f90-fa47-8cad-0ecb233bcd2a
* Content: [Container Storage Overview](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-storage#storage-limits)
* Content Source: [virtualization/windowscontainers/manage-containers/container-storage.md](https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/live/virtualization/windowscontainers/manage-containers/container-storage.md)
* Product: **windows-server**
* Technology: **windows-containers**
* GitHub Login: @cwilhit

**Comment by forderud** [comment]
I'm also observing the same issue. Configuring  `"storage-opt": [ "size=50GB"],` in daemon.json does _not_ seem to affect the free disk space, whereas `"storage-opts": ["size=50GB"],` does affect the free space.

Steps to  reproduce:
* Add `"storage-opts": ["size=50GB"],` to daemon.json 
* Switch to Windows-based containers, then restart docker
* Build a container that contains a `RUN "fsutil volume diskfree c:"` command
* Verify that approx. 50GB free space is reported

**Comment by cwilhit** [comment]
The fix has been merged, so closing this.
