### ISSUE TITLE
Switching to Windows containers

### ISSUE THREAD

**Issue by sshushliapin** [MicrosoftDocs/Virtualization-Documentation#1484]
The page describes how to install Docker but there is not any info how to switch to Windows containers. So, how to do that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e09e1b22-1344-d7b9-9462-dc4c2e160e86
* Version Independent ID: f6411e97-4419-1209-56ad-9140ceb37329
* Content: [Prep Windows operating system containers](https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=Windows-Server)
* Content Source: [virtualization/windowscontainers/quick-start/set-up-environment.md](https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/live/virtualization/windowscontainers/quick-start/set-up-environment.md)
* Product: **windows-server**
* Technology: **windows-containers**
* GitHub Login: @cwilhit
* Microsoft Alias: **crwilhit**

**Comment by ashenm** [comment]
Hey @sshushliapin,
The instructions outlined in the [Windows 10 tab](https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=Windows-10-Client) shall guide you through switching to Windows containers and vice versa.
Please do aid the community to keep the documentation competent by imparting any further inadequacies of the aforementioned documentation.
