### ISSUE TITLE
Link to the HNS module

### ISSUE THREAD

**Issue by davinci26** [MicrosoftDocs/Virtualization-Documentation#1539]
@daschott  should this page contain a link to the [HNS module](https://www.powershellgallery.com/packages/HNS/0.2.4)?

 I can push a PR if you think it adds value. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3be8120-7fc1-9818-53d4-61e7d3f36175
* Version Independent ID: 38825f46-278d-7da0-d538-a1c7d1d96557
* Content: [Windows container networking](https://docs.microsoft.com/en-us/virtualization/windowscontainers/container-networking/architecture#container-network-management-with-host-network-service)
* Content Source: [virtualization/windowscontainers/container-networking/architecture.md](https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/live/virtualization/windowscontainers/container-networking/architecture.md)
* Product: **windows-server**
* Technology: **windows-containers**
* GitHub Login: @daschott
* Microsoft Alias: **jgerend**

**Comment by daschott** [comment]
Thanks, I didn't realize this was created already. 
Yes, we should add a link or PowerShellGet command. If you have a PR ready to go feel free to raise it. If you don't no worries I can take a look at adding it next week
