### ISSUE TITLE
Update documentation - Virtualized container hosts: Nested virtualization available for AMD host machines

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftDocs/Virtualization-Documentation#1571]
The document reads:

> ### Virtualized container hosts
>
> Nested virtualization has the following requirements:
> - A processor with Intel VT-x (this feature is currently only available for Intel processors).

According to [this microsoft blog](https://techcommunity.microsoft.com/t5/virtualization/amd-nested-virtualization-support/ba-p/1434841), nested virtualization support is available for **AMD** processors since mid 2020.

May I humbly suggest to verify and update the documentation accordingly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9682caf3-5fc4-54e6-d841-8cb6c16bbc4f
* Version Independent ID: 6c99e2e3-eafe-a91e-9c26-8d5845cc0b7f
* Content: [Windows Container Requirements](https://docs.microsoft.com/virtualization/windowscontainers/deploy-containers/system-requirements#virtualized-container-hosts)
* Content Source: [virtualization/windowscontainers/deploy-containers/system-requirements.md](https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/live/virtualization/windowscontainers/deploy-containers/system-requirements.md)
* Product: **windows-server**
* Technology: **windows-containers**
* GitHub Login: @v-susbo
* Microsoft Alias: **v-susbo**

**Comment by v-susbo** [comment]
Topic is now updated. https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/system-requirements
Thanks for the heads up.

**Comment by SetTrend** [comment]
Thank you 👍
