### ISSUE TITLE
TLFS v6.0b, Section 3.7 'Is Nested' field location is inconsistent

### ISSUE THREAD

**Issue by tandasat** [MicrosoftDocs/Virtualization-Documentation#1574]
** Description**
`Is Nested` field's position is inconsistent across two tables in the Section 3.7 of the TLFS v6.0b.

In the first table, it is documented that it is before `RsvdZ`, at bit 26.
![image](https://user-images.githubusercontent.com/1620923/117699146-55963a80-b179-11eb-971d-da5d00b901fd.png)

In the next table, it is documented that it is after `RsvdZ`, at bit 31.
![image](https://user-images.githubusercontent.com/1620923/117699183-62b32980-b179-11eb-8479-0ff325903971.png)

Link to doc:
https://github.com/MicrosoftDocs/Virtualization-Documentation/raw/master/tlfs/Hypervisor%20Top%20Level%20Functional%20Specification%20v6.0b.pdf

**Comment by alexgrest** [comment]
The TLFS document 6 was replaced by this page: https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/tlfs/hypercall-interface
