### ISSUE TITLE
single gMSA with multiple containers on multiple machines

### ISSUE THREAD

**Issue by bleissem** [MicrosoftDocs/Virtualization-Documentation#1603]
Hello, 
I want to clarify the content from this text from your documentation:
"
When multiple containers are assigned the same identity and hostname, a race condition may occur when two containers talk to the same domain controller simultaneously. When another container talks to the same domain controller, it will cancel communication with any prior containers using the same identity. This can lead to intermittent authentication failures and can sometimes be observed as a trust failure when you run nltest /sc_verify:contoso.com inside the container.

We changed the behavior in Windows Server 2019 to separate the container identity from the machine name, allowing multiple containers to use the same gMSA simultaneously.
"
For Windows Server 2019:
Does this mean that it is a supported scenario to run multiple containers with the same gMSA on multiple machines or does it mean to only have one gMSA identity per machine to run multiple docker container ? 
Regards
Alexander Bleissem

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e73f574-a1a7-bf20-5c41-8af0cd64e933
* Version Independent ID: 51994784-e115-d0e9-ea77-69941cecfb40
* Content: [Troubleshoot gMSAs for Windows containers](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/gmsa-troubleshooting)
* Content Source: [virtualization/windowscontainers/manage-containers/gmsa-troubleshooting.md](https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/live/virtualization/windowscontainers/manage-containers/gmsa-troubleshooting.md)
* Product: **windows-server**
* Technology: **windows-containers**
* GitHub Login: @rpsqrd
* Microsoft Alias: **jgerend**

**Comment by rpsqrd** [comment]
On WS2019 it's supported to run multiple containers with the same identity, whether on the same or multiple hosts. Hope that helps clarify things!
