### ISSUE TITLE
User mode api or kernel mode api - details and samples will be helpful

### ISSUE THREAD

**Issue by gokultv-private** [MicrosoftDocs/Virtualization-Documentation#1615]
Hi,

Is it a user mode API or kernel mode API? If it is kernel mode API - can you add the details of IRQL restrictions?
Also, can you add some samples for reference?

Thanks,
Gokul T V

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 870f822d-146a-b138-0e23-c20d97d1a0de
* Version Independent ID: dc7104fd-8138-8acf-815e-036079a869cd
* Content: [WHvCreatePartition](https://docs.microsoft.com/en-us/virtualization/api/hypervisor-platform/funcs/whvcreatepartition)
* Content Source: [virtualization/api/hypervisor-platform/funcs/WHvCreatePartition.md](https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/live/virtualization/api/hypervisor-platform/funcs/WHvCreatePartition.md)
* GitHub Login: @Juarezhm

**Comment by Zero-Tang** [comment]
Hi,

This WHP is a set of user mode APIs.
You may take a look at [my demo of using WHP](https://github.com/Zero-Tang/SimpleWhpDemo) to run a real-mode DOS program in a virtualized environment, albeit my code is not well commented, and though the test case is not even a real DOS program that can run in a real DOS system.

Kind Regards,
Zero Tang

**Comment by gokultv-private** [comment]
Thank you @Zero-Tang for clarification and sharing your samples. I'll go through it and in case if I get any additional questions, I'll get back you.
