### ISSUE TITLE
Documentation Should Be Updated To Specify That Docker Desktop Is No Longer Free For Commercial Users

### ISSUE THREAD

**Issue by AlexWilson-GIS** [MicrosoftDocs/Virtualization-Documentation#1639]
[As of August 31st, Docker Desktop requires a paid license for commercial users](https://www.docker.com/blog/updating-product-subscriptions/), so I recommend the documentation be revised to include this detail when instructing Windows 10 users on downloading the product and creating an account, since the free Docker account is now only good for personal, educational, or small business use, according to their definition of small.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e09e1b22-1344-d7b9-9462-dc4c2e160e86
* Version Independent ID: f6411e97-4419-1209-56ad-9140ceb37329
* Content: [Prep Windows operating system containers](https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=Windows-Server)
* Content Source: [virtualization/windowscontainers/quick-start/set-up-environment.md](https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/live/virtualization/windowscontainers/quick-start/set-up-environment.md)
* Product: **windows-server**
* Technology: **windows-containers**
* GitHub Login: @v-susbo
* Microsoft Alias: **viniap**

**Comment by v-susbo** [comment]
Thanks for your input on this topic. I'll look into the new requirement for a Docker Desktop paid license, and update it accordingly.

**Comment by MarkIannucci** [comment]
Similar issue as #1643 .

**Comment by AlexWilson-GIS** [comment]
Great thanks

**Comment by slonopotamus** [comment]
I'd like to announce [Stevedore](https://github.com/slonopotamus/stevedore) project. It aims to provide a free and convenient way to use Docker on Windows (both client and server). Currently, it only supports Windows containers. Stevedore is distributed as an MSI installer. Chocolatey.org package is planned but not there yet.

Installation
* Download [MSI installer](https://github.com/slonopotamus/stevedore/releases/latest)
* Double-click on it
* Next-next-next
* Reboot your computer
* Profit! `docker` command is now available on your PATH and `dockerd` daemon is already running.
