### ISSUE TITLE
PowerShell :: Tar command seems not working 

### ISSUE THREAD

**Issue by francesco1119** [MicrosoftDocs/Virtualization-Documentation#1656]
I have recently discovered that Windows10 is supporting `Tar `and `Curl`.

I give it a try and it doesn't looks like it is working for me. 

I run the command `tar -tvf '.\Funziona - fullRAcsv_ak510_99999999.csv.tar'` used to list all files inside a .tar and it has bee running for more than 10 minutes now. 

![Tar list](https://user-images.githubusercontent.com/3397477/133407222-059936bc-728d-4f7c-8a90-0027ddcefbad.png)

the same goes when I try to deflate a tar.gz file with the command `tar -xvzf .\fullRAcsv_ak510_99999999.csv.gz -C E:\CCIH\UPI`, the terminal is looking at me without doing nothing. 

![Tar bomba](https://user-images.githubusercontent.com/3397477/133407512-88b41098-f5a3-4c76-9d31-d6be299f984a.png)

But if I use the `gzip `library this way `"E:\CCIH\UPI\gzip-1.3.12-1-bin\bin\gzip" -d E:\CCIH\UPI\*.gz --force`  it takes only 1 minute to deflate the whole thing. 

Let me know if you need any other info 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c1b9a06-b0b3-22b9-1bfb-5839c7647225
* Version Independent ID: 450e75ed-b1c3-9593-26f6-866947fc2e50
* Content: [Tar and Curl Come to Windows!](https://docs.microsoft.com/en-us/virtualization/community/team-blog/2017/20171219-tar-and-curl-come-to-windows)
* Content Source: [virtualization/community/team-blog/2017/20171219-tar-and-curl-come-to-windows.md](https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/live/virtualization/community/team-blog/2017/20171219-tar-and-curl-come-to-windows.md)
* Product: **windows**
* GitHub Login: @scooley

**Comment by francesco1119** [comment]
User error

**Comment by ScorpJ** [comment]
tar.exe: Couldn't open tools.tar.gz: Permission denied
