### ISSUE TITLE
Date incorrectly stated

### ISSUE THREAD

**Issue by dalehhirt** [MicrosoftDocs/Virtualization-Documentation#1669]
In the Install Docker section, the note is unclear:

_At the end of September 2022, Microsoft announced updates to the Windows Container Runtime support to notify customers that we'll no longer produce builds of Docker EE for the DockerMsftProvider API._

Nothing can have been announced at the end of September 2022, since that date has not happened yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e09e1b22-1344-d7b9-9462-dc4c2e160e86
* Version Independent ID: f6411e97-4419-1209-56ad-9140ceb37329
* Content: [Prep Windows operating system containers](https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=Windows-Server)
* Content Source: [virtualization/windowscontainers/quick-start/set-up-environment.md](https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/live/virtualization/windowscontainers/quick-start/set-up-environment.md)
* Product: **windows-server**
* Technology: **windows-containers**
* GitHub Login: @v-susbo
* Microsoft Alias: **viniap**

**Comment by v-susbo** [comment]
Date is fixed: https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=Windows-Server#install-docker

**Comment by dalehhirt** [comment]
Thank you.  Closing issue.
