### ISSUE TITLE
Elaborate more on `Additional credential spec configuration for non-domain-joined container host use case`

### ISSUE THREAD

**Issue by rrmistry** [MicrosoftDocs/Virtualization-Documentation#1680]
Need help as documentation is not quite clear.

Can you elaborate more on:
> ### Additional credential spec configuration for non-domain-joined container host use case
>
> When using gMSA with non-domain-joined container hosts, information about the ccg.exe plug-in that you will be using needs to be added to the credential spec. This will be added to a section of the credential spec called HostAccountConfig. The HostAccountConfig section has three fields that need to be populated:
> 
> * PortableCcgVersion: This should be set to "1".
> * PluginGUID: The COM CLSID for the ccg.exe plug-in. This is unique to the plug-in being used.
> * PluginInput: Plug-in specific input for retrieving the user account information from the secret store.
>
> This is an example of a credential spec with the HostAccountConfig section added:

It is not clear what the `<password>` should be for the `HostAccountConfig` in the Credential Spec Config:

```jsonc
{
    //...
        "HostAccountConfig": {
            "PortableCcgVersion": "1",
            "PluginGUID": "{GDMA0342-266A-4D1P-831J-20990E82944F}",
            "PluginInput": "contoso.com:gmsaccg:<password>"  // <--- What password to use?
        }
    //...
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6cbabcb-0910-3082-fe93-bafef68f2faa
* Version Independent ID: 6efd7af0-a3f2-9d4a-cee1-722caf001cdd
* Content: [Create gMSAs for Windows containers](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/manage-serviceaccounts)
* Content Source: [virtualization/windowscontainers/manage-containers/manage-serviceaccounts.md](https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/live/virtualization/windowscontainers/manage-containers/manage-serviceaccounts.md)
* Product: **windows-server**
* Technology: **windows-containers**
* GitHub Login: @rpsqrd
* Microsoft Alias: **jgerend**

**Comment by vrapolinario** [comment]
I checked internally and confirmed that this is a sample file that will vary based on the implementation of the plug-in. For example, the Azure Key Vault plug in that has been open sourced, has a different implementation following this guidance:

```
{
  "CmsPlugins": [
      "ActiveDirectory"
    ],
    "DomainJoinConfig": {
        "DnsName": "testing.com",
        "DnsTreeName": "testing.com",
        "Guid": guid of domain (use Get-ADDomain),
        "MachineAccountName": "test",
        "NetBiosName": "testing",
        "Sid": sid of domain (use Get-ADDomain)
    },
   "ActiveDirectoryConfig": {
        "GroupManagedServiceAccounts": [
            {
                "Name": "test",
                "Scope": "testing.com"
            },
            {
                "Name": "test",
                "Scope": "testing"
            }
        ],
        "HostAccountConfig": {
            "PluginGUID": "{CCC2A336-D7F3-4818-A213-272B7924213E}",
            "PluginInput": "ObjectId="objectid of managed identity";SecretUri="url of secret stored in keyvault",
            "PortableCcgVersion": "1"
        }
    }
}
```

So the answer to your question is that this will vary - which is why we implemented this documentation as a sample. You can refer to the AKV plug in here: https://github.com/microsoft/Azure-Key-Vault-Plugin-gMSA
