### ISSUE TITLE
Typo In Last Paragraph of Doc

### ISSUE THREAD

**Issue by jlhs1001** [MicrosoftDocs/Virtualization-Documentation#1752]
Under the "**Wrap up and References**" section, 'explore' was misspelled as 'explorer'.

```
This document has shown some simple steps to explorer the Hyper-V PowerShell module...
```
[link to doc section](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/try-hyper-v-powershell#wrap-up-and-references)

**Comment by anubha-v-ardhan** [comment]
I'd like to fix this. Can I be assigned this issue.
