### ISSUE TITLE
Grammar

### ISSUE THREAD

**Issue by DiskCrasher** [MicrosoftDocs/Virtualization-Documentation#1827]
It's "its", not "it's".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c1b9a06-b0b3-22b9-1bfb-5839c7647225
* Version Independent ID: 450e75ed-b1c3-9593-26f6-866947fc2e50
* Content: [Tar and Curl Come to Windows!](https://learn.microsoft.com/en-us/virtualization/community/team-blog/2017/20171219-tar-and-curl-come-to-windows)
* Content Source: [virtualization/community/team-blog/2017/20171219-tar-and-curl-come-to-windows.md](https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/live/virtualization/community/team-blog/2017/20171219-tar-and-curl-come-to-windows.md)
* Product: **windows**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by lunarot** [comment]
fuck you

**Comment by bnchannel** [comment]
On Tue, Feb 14, 2023 at 2:40 AM lunarot ***@***.***> wrote:

> Yeah i want fuck your Mother  & Sister's.
>
You know i like your mother  pussy fucking my Cock. Haa Haaaa 😁😁😁😁😁


Son of bitch.

**Comment by bnchannel** [comment]
On Tue, Feb 14, 2023 at 2:48 AM B&N Channel ***@***.***> wrote:

>
>
> On Tue, Feb 14, 2023 at 2:40 AM lunarot ***@***.***> wrote:
>
>> Yeah i want fuck your Mother  & Sister's.
>>
> You know i like your mother  pussy fucking my Cock. Haa Haaaa 😁😁😁😁😁
>
>
>
>
    Hay

> You can show  my disc to your mother and your sister, son of a bitch
>
> Son of a bitch.
>

Show my disc to your mother and your sister, son
