### ISSUE TITLE
Roadmap link broken

### ISSUE THREAD

**Issue by Froglet0** [MicrosoftDocs/Virtualization-Documentation#1936]
[Enter feedback here]
Link to roadmap broken

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 07b1cd55-0f91-e97c-06d3-afe54fb909d4
* Version Independent ID: db485580-9c27-da7d-26f9-a60449cb5773
* Content: [About Windows containers](https://learn.microsoft.com/en-us/virtualization/windowscontainers/about/)
* Content Source: [virtualization/windowscontainers/about/index.md](https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/live/virtualization/windowscontainers/about/index.md)
* Product: **windows-server**
* Technology: **windows-containers**
* GitHub Login: @vrapolinario
* Microsoft Alias: **viniap**

**Comment by vrapolinario** [comment]
Thanks for raising this. I'll fix the link as we're not using this roadmap on GitHub anymore.
