### ISSUE TITLE
PROP: `CMD` on base images

### ISSUE THREAD

**Issue by friism** [MicrosoftDocs/Virtualization-Documentation#197]
I was wondering if it might make sense for the base images (like `windowsservercore`) to define a default `CMD` like `CMD ["cmd"]`. It's not quite the same, but other similar images to it: https://github.com/tianon/docker-brew-ubuntu-core/blob/c390883f9aa4a069c48a16dc01d49dc2643eea25/trusty/Dockerfile#L30

/cc @jhowardmsft @jstarks @PatrickLang @taylorb-microsoft

**Comment by timotei** [comment]
IMO, as a user, I'd expect the *default* behaviour not to do anything special, especially since it's *the* default*. It's gonna be confusing the first time, seeing that the cmd is still open instead of having the SHA1 of the container that was started.

**Comment by enderb-ms** [comment]
Closing this issue since no changes were made.
