### ISSUE TITLE
Scripts to make a new vm container host do not work.

### ISSUE THREAD

**Issue by erichexter** [MicrosoftDocs/Virtualization-Documentation#224]
When I try to run the quick start code located here. The script errors out trying to validate versions of tp5. Sorry but I dont know where else to post this issue.

https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/quick_start/quick_start_configure_host.md#scripted---new-vm---1--

![image](https://cloud.githubusercontent.com/assets/114692/14933595/0cf11f16-0e59-11e6-9427-8dcb2440558a.png)

**Comment by erichexter** [comment]
@neilpeterson  ?  any update on this? is the package in the powershell gallery wrong?

**Comment by PatrickLang** [comment]
I ran this today, and it worked for me:
```
wget -uri https://aka.ms/tp5/New-ContainerHost -OutFile c:\New-ContainerHost.ps1
powershell.exe -NoProfile -ExecutionPolicy Bypass c:\New-ContainerHost.ps1 -VMName TP5Host_0505 -WindowsImage ServerDatacenterCore -Hyperv
```

My VM host is also running Windows Server 2016 TP5. Is your host running TP5 or another version?

**Comment by mebersol** [comment]
Please make sure you have the latest ContainerImage package provider

**Comment by erichexter** [comment]
I am running from a win10 host. it looks like I have ContainerProvider install, the containerImage package will not import, it needs powershell 5.1. I will just call it a day and create a azure vm from the image.

**Comment by enderb-ms** [comment]
We no longer support this script as the method to set up containers on your host. Please see this [quick start guide](https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-server) for the new method of doing this.
