### ISSUE TITLE
Could not install ContainerImage provider

### ISSUE THREAD

**Issue by justinhelgerson** [MicrosoftDocs/Virtualization-Documentation#235]
I'm following the [documentation](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_configure_host) to install Windows Server 2016 in a Virtual Machine on Windows 10 Enterprise.

I executed this command to create the VM:  `powershell.exe -NoProfile -ExecutionPolicy Bypass c:\New-ContainerHost.ps1 -VMName Server2016 -WindowsImage ServerDatacenterCore –Hyperv`

Unfortunately I'm getting an error and in the Hyper-V Manager I can see that the VM was not fully created:

> Dismounting VHD...
> C:\New-ContainerHost.ps1 : Could not install ContainerImage provider
> At line:1 char:1
> - c:\New-ContainerHost.ps1 -VMName Server2016 -WindowsImage ServerDatac ...
> - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   - CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>   - FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-ContainerHost.ps1

How can I install the "ContainerImage" provider?

**Comment by nayanshah** [comment]
Based on [this](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/deployment/deployment), does the following help ?

`Install-PackageProvider ContainerImage -Force`

**Comment by enderb-ms** [comment]
ContainerImage is no longer a supported command. Please read [this guide](https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-server) to see the new guidelines for setting up containers.
