### ISSUE TITLE
TP5: Get-EventLog not working anymore (worked fine on TP4)

### ISSUE THREAD

**Issue by mathiasconradt** [MicrosoftDocs/Virtualization-Documentation#238]
Inside a Windows container managed by Docker, I cannot get the Windows event logs anymore on TP5:

`Get-EventLog -LogName System -EntryType Error -After "Tuesday, May 3, 2016 6:00:06 PM" -newest 3 | Format-List`

Error:

```
PS C:\> Get-EventLog -LogName System -EntryType Error -After "Tuesday, May 3, 2016 6:00:06 PM" -newest 3 | Format-List
Get-EventLog : Cannot open log System on machine .. Windows has not provided an error code.
At line:1 char:1
+ Get-EventLog -LogName System -EntryType Error -After "Tuesday, May 3, ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-EventLog], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.GetEventLogCommand
```

Container is based on windowsservercore.
Docker version 1.12.0-dev, build 2b97201

It worked fine before on TP4.

**Comment by PatrickLang** [comment]
This is also on the forums: https://social.msdn.microsoft.com/Forums/en-US/1fcc023a-27fb-4575-a6d9-159e256243ad/geteventlog-inside-container-invalidoperationexception?forum=windowscontainers

I'm investigating a workaround

**Comment by mathiasconradt** [comment]
@PatrickLang Thanks for the info, adding the suggested line to the dockerfile solves the problem.

`RUN powershell.exe -command Set-ItemProperty HKLM:\SYSTEM\CurrentControlSet\Control\WMI\Autologger\EventLog-Application Start 1`

**Comment by PatrickLang** [comment]
@mathiasconradt thanks for letting us know! I'm talking with the developer here at Microsoft to track the fix.

**Comment by volak** [comment]
I think this is related to my bug for reading performance counters inside a container: https://github.com/docker/docker/issues/23225

Is there a similar workaround?

**Comment by enderb-ms** [comment]
Closing this issue since WS16 has GA'd. If you are still seeing this issue, please feel free to open this issue again.
