### ISSUE TITLE
The VMs created by New-ContainerHost.ps1 are missing the ContainerImage provider

### ISSUE THREAD

**Issue by PatrickLang** [MicrosoftDocs/Virtualization-Documentation#241]
@mebersol - Running New-ContainerHost.ps1 installs the ContainerImage provider on the VM host, but not in the created VM. I would expect it to automatically be added to the container host VM so that I could pull down the other base images. I think this should simplify setup quite a bit. Most users today want the Windows Server Core image, and they're having to find the [deployment page](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/deployment/deployment), rather than the quickstart in order to get it.

View from the container host VM:

```
PS C:\Users\Administrator> Get-PackageProvider -ListAvailable

Name                     Version          DynamicOptions
----                     -------          --------------
msi                      3.0.0.0          AdditionalArguments
msu                      3.0.0.0
PowerShellGet            1.0.0.1          PackageManagementProvider, Type, Scope, InstallUpdate, NoPathUpdate, Filte...
Programs                 3.0.0.0          IncludeWindowsInstaller, IncludeSystemComponent


PS C:\Users\Administrator> install-containerimage -Name WindowsServerCore
install-containerimage : The term 'install-containerimage' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At line:1 char:1
+ install-containerimage -Name WindowsServerCore
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (install-containerimage:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Here's the manual steps needed in the VM to get the expected Windows Server Core image:

```
Install-PackageProvider ContainerImage -Force
Install-ContainerImage -Name WindowsServerCore
Restart-Service  docker
docker tag windowsservercore:10.0.14300.1000 windowsservercore:latest
```

I think the steps should just be:

```
Install-ContainerImage -Name WindowsServerCore
```

Fixing the container provider gets us one step closer

**Comment by enderb-ms** [comment]
Closing this issue since this installer is no longer in use. Please use the [DockerMsftProvider](https://github.com/OneGet/MicrosoftDockerProvider) instead.
