### ISSUE TITLE
Integration services for Vista and 2008 are not available from Windows Update

### ISSUE THREAD

**Issue by 0xbadfca11** [MicrosoftDocs/Virtualization-Documentation#249]
In `/virtualization/hyperv_on_windows/user_guide/managing_ics`,
integration services installer for Vista/2008 does not exist on Windows Update.
Even if connected to Windows Update using legacy network adapter, clean installed Windows Vista on Windows 10 Hyper-V will not receive integration services.

**Comment by scooley** [comment]
We've seen that a few times.  What behavior impact is this having?

**Comment by 0xbadfca11** [comment]
I say document is incorrect.

**Comment by scooley** [comment]
We're in an awkward place with vista -- it's out of mainstream support but still in extended support.  I'll have to do more digging to see if this is a product bug or doc bug. [Link to support page](http://windows.microsoft.com/en-us/windows/lifecycle).  Either way, I'll update the doc.
