### ISSUE TITLE
The link in the documentation don't work.

### ISSUE THREAD

**Issue by paule96** [MicrosoftDocs/Virtualization-Documentation#257]
Hi everybody,

the link on the site https://github.com/Microsoft/Virtualization-Documentation/tree/master/hyperv-tools/Convert-WindowsImage in the ReadMe.md doesn't work.
It point to this: https://github.com/Microsoft/Convert-WindowsImage.
But this page doesn't exsists.

**Comment by neilpeterson** [comment]
@pronichkin - hey Artem, can you checkout this out?

**Comment by thebagel** [comment]
This link is still present and broken - does the script have a new home? The copy of the script in this repository does not match the one available on the TechNet gallery (https://gallery.technet.microsoft.com/scriptcenter/Convert-WindowsImageps1-0fe23a8f).

**Comment by Nirmal4G** [comment]
Anyone working on this script, I already published on [PowerShellGallery](https://www.powershellgallery.com/packages/Convert-WindowsImage). It's a version from this repo.

Although It's for me to install it from [PowerShellGet](https://www.powershellgallery.com/packages/PowerShellGet). If anyone wants to take ownership on the package, please let me know in the comments.

**Comment by scooley** [comment]
The version in the docs is the one we (Hyper-V) use for testing.  I'm updated the README to say as much.
