### ISSUE TITLE
Install-ContainerImage on TP5 fails after download with create vm utility error: The system cannot find the file specified.... Even though the container image exists

### ISSUE THREAD

**Issue by sflanders** [MicrosoftDocs/Virtualization-Documentation#259]
As you can see the image does exist but breaks at the end.

[192.168.137.102]: PS C:> Find-ContainerImage

Name Version Description

---

NanoServer 10.0.10586.0 Container OS Image of Windows Se...
WindowsServerCore 10.0.10586.0 Container OS Image of Windows Se...

[192.168.137.102]: PS C:> 
[192.168.137.102]: PS C:> Install-ContainerImage -Name NanoServer -Verbose
VERBOSE: Saving to C:\Users\ADMINI~1\AppData\Local\Temp\NanoServer.wim
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''className' = win32_operatingsystem,'namespaceName' = root\cimv2'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''className' = win32_operatingsystem,'namespaceName' = root\cimv2'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''className' = win32_operatingsystem,'namespaceName' = root\cimv2'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
VERBOSE: Downloading NanoServer. Version: 10.0.10586.0
VERBOSE: https://pshctnoncdn.blob.core.windows.net/pshctcontainer/CBaseOs_th2_release_10586.0.151029-1700_amd64fre_NanoServer_en-us.wim
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''className' = win32_operatingsystem,'namespaceName' = root\cimv2'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
VERBOSE: Importing function 'Invoke-HTTPClient'.
VERBOSE: Importing function 'Save-HTTPItem'.
VERBOSE: Importing function 'Save-RSTBlobItem'.
VERBOSE: Downloaded in 0 hours, 0 minutes, 12 seconds.
Failed to create utility VM image VHD with error: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
- CategoryInfo : OperationStopped: (:) [], Exception
- FullyQualifiedErrorId : Failed to create utility VM image VHD with error: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)

**Comment by queeg505** [comment]
Did you get this issue resolved, I'm getting the exact same message?

**Comment by xied75** [comment]
@sflanders No the image does not yet "exists" on your machine. It's only "find" from the repo.

From the verbose output one can figure out the download didn't happen, unless you have Internet3 connection to grab that file in 12 seconds.

According to this blog post: http://www.logitblog.com/downloading-issues-windows-container/
It is due to the checking of Certificates that failed the download, so you either disable the checking in policy, or just download it manually and then call install cmd.

**Comment by jayshah-msft** [comment]
@sflanders , @queeg505 
Thank you for reporting this issue. I am investigating this. 
Can you please provide further details about your machine? The Edition, Installation Option and Version?
Thanks.

Cheers,
Jay!

**Comment by sflanders** [comment]
@xied75 in regards to downloading i see it download a "wim" file.
@jayshah-msft Below is some info on the installed version.  let me know how to retrieve "Installation Option" info and i'll supply that also.

OS Version: Microsoft Windows Server 2016 Standard Technical Preview 5
Build Number: 14300

**Comment by queeg505** [comment]
@jayshah-msft My systems info:
Caption                 : Microsoft Windows Server 2016 Standard Technical Preview 5
InstallDate             : 27/05/2016 03:55:05
ServicePackMajorVersion : 0
OSArchitecture          : 64-bit
BootDevice              : \Device\HarddiskVolume2
BuildNumber             : 14300
CSName                 : Nano-srv1

**Comment by jayshah-msft** [comment]
@queeg505 & @sflanders ,
I just noticed you are looking at version 10.0.10586.0. This means that you are using ContainerProvider version 0.5.*.* 
Please upgrade your ContainerImage provider to version 0.6.4.0 and try again.

Let me know if you face any further issues.

**Comment by queeg505** [comment]
@jayshah-msft  @sflanders Thanks that sorted  the issue, its installed the container image just fine now after upgrading the provider to ver 0.6.4.0 (if anyone needs to know I ran Install-PackageProvider ContainerImage and then Import-PackageProvider ContainerImage to do this)

**Comment by richardjharding** [comment]
Just tried following the instructions on the [quick start ](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_10)

And get the same error

Windows 10 insider - 14367

provider version 0.6.4.0

```
PS C:\WINDOWS\system32> Install-PackageProvider ContainerImage -Force

Name                           Version          Source           Summary
----                           -------          ------           -------
ContainerImage                 0.6.4.0          PSGallery        This is a PackageManagement provider module which h..
```
verbose trace - from comments above downloading out of date image?

```
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' =
root\cimv2,'className' = win32_operatingsystem'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' =
root\cimv2,'className' = win32_operatingsystem'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' =
root\cimv2,'className' = win32_operatingsystem'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
VERBOSE: Downloading NanoServer. Version: 10.0.10586.0
VERBOSE:
https://pshctnoncdn.blob.core.windows.net/pshctcontainer/CBaseOs_th2_release_10586.0.151029-1700_amd64fre_NanoServer_en
-us.wim
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' =
root\cimv2,'className' = win32_operatingsystem'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
VERBOSE: Downloaded in 0 hours, 1 minutes, 54 seconds.
Failed to create utility VM image VHD with error: The system cannot find the file specified. (Exception from HRESULT:
0x80070002)
At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Containers\1.0.0.0\Containers.psm1:376 char:9
+         throw [exception]::new(
+         ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], Exception
    + FullyQualifiedErrorId : Failed to create utility VM image VHD with error: The system cannot find the file specif
   ied. (Exception from HRESULT: 0x80070002)

PS C:\WINDOWS\system32>
```


Any ideas on how to proceed?

**Comment by jayshah-msft** [comment]
@richardjharding 
Yes you have installed the latest version of ContainerImage. However you are still calling the older version of ContainerProvider. Please remove the older version of ContainerProvider, then run the following commands:

Import-packageprovider -requiredversion 0.6.4.0 -force -verbose -name ContainerImage
import-module ContainerImage -Verbose -force -requiredversion 0.6.4.0 

Now try running Find-ContainerImage.
You should see the versions like thus:
10.0.14300.1016 for Nano
10.0.14300.1000 for Windows Server

Then you should be able to download and install.

HTH!

Cheers,
Jay!

**Comment by enderb-ms** [comment]
Closing this issue since we no longer support ContainerImage. You can now use "docker pull" to get the base images.
