### ISSUE TITLE
remote_host_management.md - Manage a Hyper-V host outside your domain (or with no domain) incorrect process

### ISSUE THREAD

**Issue by muzzar78** [MicrosoftDocs/Virtualization-Documentation#261]
I tried following the instructions for non-domain access but they didn't work. I performed the following steps and it worked

On the **client** where I am running hyper-v manager I did the following
1) Set-Item WSMan:\localhost\Client\TrustedHosts -value "ip address of hyper-v host" -concatenate

```
Alternately, you can allow all hosts to be trusted to manage via:
Set-Item WSMan:\localhost\Client\TrustedHosts -value * -force
```

2) Enable-WSManCredSSP -Role client -DelegateComputer *

3) Computer Policy\Administrative Templates\System\Credentials Delegation\Allow Delegating Fresh Credentials with NTLM-only server authentication → Set to enabled and add WSMAN/\* to list of computers, check the box for Concatenate OS defaults with input above

On the **Hyper-v server** I had to enable credssp
1) Enable-WSManCredSSP -Role Server

I also found that the client needs to be able to resolve the hostname even though I was entering the ip address into hyper-v manager. As my client and hyper-v host are on the subnet I enabled this by allowing LLMNR on the hyper-v host firewall. (Get-NetFirewallRule -Name FPS-LLMNR-In-UDP | Set-NetFirewallRule -Enabled True)

**Comment by scooley** [comment]
@muzzar78 thanks for the feedback and instructions!  I'll validate and rev sometime late next week.

@edreed for heads up.
