### ISSUE TITLE
Cannot execute CMD [shell form] on path with spaces

### ISSUE THREAD

**Issue by timotei** [MicrosoftDocs/Virtualization-Documentation#266]
Hello,

First of all, not sure this is the right place for this issue. Please move it in the proper place if that's the case.

Now, my issue is about the CMD command, combined with a path with spaces. More specifically, I have this path: `C:\Program Files\Java\jdk1.8.0_65\bin\java.exe`

I can't find a way to use the SHELL form to execute the command, none of the below commands work:

```
CMD C:\Program Files\Java\jdk1.8.0_65\bin\java.exe
CMD C:/Program Files/Java/jdk1.8.0_65/bin/java.exe
CMD "C:\Program Files\Java\jdk1.8.0_65\bin\java.exe"
CMD ""C:\Program Files\Java\jdk1.8.0_65\bin\java.exe""
```

The last command, if executed as: `cmd /s /c ""CMD "C:\Program Files\Java\jdk1.8.0_65\bin\java.exe""` works, but the docker-based invocation not: `The network path was not found.`

However, the exec form works:

```
CMD ["C:\\Program Files\\Java\\jdk1.8.0_65\\bin\\java.exe", "-version"]
```

Am I missing something, or maybe it's a known issue?

**Comment by PatrickLang** [comment]
@jhowardmsft - would your path escaping PR address this as well?

**Comment by jhowardmsft** [comment]
Not sure, but doubt it - will investigate when I get a chance.

**Comment by jhowardmsft** [comment]
Can you share your dockerfile?

**Comment by jhowardmsft** [comment]
See https://github.com/docker/docker/pull/22868. While a fix has been submitted, all the time the hard-coded shell is `cmd /s /c`, the `/s` part makes life particularly difficult here when using a filename in quotes with a space in it. However, `/s` is needed by default for other reasons.

When combining the fix in 22868 with the PR to provide the ability to change the shell https://github.com/docker/docker/pull/22489, the following has been verified to work:

```
FROM windowsservercore
SHELL cmd /c
CMD "c:\program files\windows defender\mpcmdrun.exe" -ListAllDynamicSignatures
```

(I was just looking for a command which by default is in a directory with a space in it, and which also accepts parameters. Note this command will fail in a container though, but the parameter validation will be correct.)

**Comment by enderb-ms** [comment]
Closing this issue since the above PR has been merged. Please feel free to open this issue again if there is still something we can help with.

**Comment by dhirschfeld** [comment]
***Note:*** Paths with spaces still fail with `COPY --from`. Don't have time to open a new issue ATM so just noting it here now. Will see if I can create a repro and open a new issue when time allows...
