### ISSUE TITLE
Not clear where to report issues to (Docker or Microsoft Virtualization Docs repo)

### ISSUE THREAD

**Issue by mathiasconradt** [MicrosoftDocs/Virtualization-Documentation#268]
When I want to report an issue about Windows Containers using Docker, I am never sure where I should report the issue to: whether it should be this repo (https://github.com/Microsoft/Virtualization-Documentation), which is obviously (due to its title) meant to be about the documentation rather than the software itself, although it meanwhile holds many software related issues, or to the Docker repo https://github.com/docker/docker/ itself.

Would be great if the documentation would clarify this as well.

**Comment by shawngib** [comment]
@mathiasconradt, I would suggest your primary location for issues and research is the MSDN Forum for Containers. https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers This repo is specific to documentation that is posted there and should host issues related to the documentation, although I would suggest the forum is also a first stop for that as well.

**Comment by StefanScherer** [comment]
I've seen these links in a [Pluralsight play by play](https://app.pluralsight.com/player?course=play-by-play-application-platform-windows-server-2016&author=andrew-mason&name=play-by-play-application-platform-windows-server-2016-m1&clip=9&mode=live) in one of the last slides:

* Continue providing feedback and bug reports
  * http://aka.ms/containers/forum
  * https://github.com/Microsoft/Virtualization-Documentation
  * https://github.com/docker/docker

I personally prefer GitHub, but I'm biased using and loving Markdown.

**Comment by neilpeterson** [comment]
Thanks for the feedback. I totally get the confusion and am discussing with folk on my end how to best handle product vs. doc feedback and issues. I will update this issue once we have come to a conclusion.

**Comment by mathiasconradt** [comment]
Thanks for the responses. @shawngib Noted the info about the forum, I would argue though that a forum isn't really the best ways to report and track issues nowadays anymore. It's a bit unstructured and hard to search properly and follow up, besides often duplicate posts. Would be great if there would be a real issue tracker like github setup as well (i.e. https://github.com/Microsoft/Virtualization :).
Github or Jira is just the de-facto standard nowadays, definitely also my preference.

**Comment by enderb-ms** [comment]
Closing this issue since there has been no further progress. Feel free to open it again if there is still confusion about where to report issues.
