### ISSUE TITLE
Start Docker service failed in Azure TP5 build 

### ISSUE THREAD

**Issue by mrdotmoon** [MicrosoftDocs/Virtualization-Documentation#296]
Hi,

I am trying container in Azure Windows server TP5 build, following the steps in https://msdn.microsoft.com/en-us/virtualization/windowscontainers/deployment/deployment. But it always failed in "Start-Service Docker", the log is:

time="2016-06-07T04:37:31.792943700Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default network: HNS failed with error : Failed to create network".

The same steps work well in my local TP5 machine.

Thanks,
Pan

**Comment by mathiasconradt** [comment]
Duplicate to https://github.com/Microsoft/Virtualization-Documentation/issues/273

**Comment by StefanScherer** [comment]
@mrdotmoon So you tried the new way to run `dockerd.exe` as a native Windows service?

I did that in a Windows 10 VM with these steps https://github.com/StefanScherer/docker-windows-box/blob/master/windows10/Vagrantfile#L21-L25 by adding the steps described in the MSDN article into different ps1 scripts with a reload in between. It worked fine on Win10. I'll update this to my TP5 template as well in a few days.

**Comment by mrdotmoon** [comment]
@StefanScherer Yes. The same steps succeeded in both my onpremise Windows Server 2016 TP5 / Windows 10 machines, but failed in Azure.

**Comment by StefanScherer** [comment]
I did all the steps of https://msdn.microsoft.com/en-us/virtualization/windowscontainers/deployment/deployment in Azure with the Windows 2016 Datacenter TP5 VM available.
Everything works fine, no errors. I haven't found any errors, only info messages from docker in the event log viewer.

@mrdotmoon Have you seen that after installing the containers feature you have to reboot the server before proceeding the next commands?

```
Install-WindowsFeature containers
```

> When the feature installation has completed, reboot the computer.


Probably for copy-pasting the commands (like I do) it might be better to see an explicit command to reboot the machine:

```
Restart-Computer
```

Every step has to be done in an Administrator PowerShell terminal.


Here is the output of my Powershell terminal after the reboot doing the last steps:

```
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Users\vagrant> dockerd --register-service
PS C:\Users\vagrant> Start-Service Docker
WARNING: Waiting for service 'Docker Engine (Docker)' to start...
PS C:\Users\vagrant> Install-PackageProvider ContainerImage -Force

Name                           Version          Source           Summary
----                           -------          ------           -------
ContainerImage                 0.6.4.0          PSGallery        This is a PackageManagement provider module which h...


PS C:\Users\vagrant> Install-ContainerImage -Name WindowsServerCore
WARNING: Based on customer feedback, we are updating the Containers PowerShell module to better align with Docker. As
part of that some cmdlet and parameter names may change in future releases. To learn more about these changes as well
as to join in the design process or provide usage feedback please refer to http://aka.ms/windowscontainers/powershell
PS C:\Users\vagrant> Restart-Service docker
PS C:\Users\vagrant> docker version
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   8e92415
 Built:        Thu May 26 17:08:34 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   8e92415
 Built:        Thu May 26 17:08:34 2016
 OS/Arch:      windows/amd64
PS C:\Users\vagrant> docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
windowsservercore   10.0.14300.1000     dbfee88ee9fd        10 weeks ago        9.344 GB
PS C:\Users\vagrant> docker tag windowsservercore:10.0.14300.1000 windowsservercore:latest
PS C:\Users\vagrant> docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
windowsservercore   10.0.14300.1000     dbfee88ee9fd        10 weeks ago        9.344 GB
windowsservercore   latest              dbfee88ee9fd        10 weeks ago        9.344 GB
PS C:\Users\vagrant>

```

**Comment by StefanScherer** [comment]
Pulling images and running containers also work well. As mentioned, there is no log file in C:\ProgramData\docker any more, you can find the docker logs in the event viewer.

**Comment by neilpeterson** [comment]
@StefanScherer - I will add an explicit copy / paste friendly computer restart in the doc, thanks for the suggestion. 

@mrdotmoon - I also cannot repo the issue. Can you confirm that you are still experiencing the problem?

Thanks

**Comment by mabead** [comment]
I have the same error. Here is everything that I did starting from the birth of the docker host:

- On a machine running Windows Server 2012, I created a new VM with the Windows Server 2016 CTP 5 (Desktop Experience). This new VM will be my docker host.
- Started this VM
- Ran the following commands:

```
Install-WindowsFeature containers
Restart-Computer
# Wait...
New-Item -Type Directory -Path "$env:ProgramFiles\docker\" > $null
Invoke-WebRequest https://aka.ms/tp5/b/dockerd -OutFile $env:ProgramFiles\docker\dockerd.exe
Invoke-WebRequest https://aka.ms/tp5/b/docker -OutFile $env:ProgramFiles\docker\docker.exe
[Environment]::SetEnvironmentVariable("Path", $env:Path + ";$env:ProgramFiles\Docker", [EnvironmentVariableTarget]::Machine)
$env:path += ";$env:ProgramFiles\docker"
dockerd
```
And here is the error that I got:
```
PS C:\Users\Administrator> dockerd
time="2016-06-09T08:29:20.993654400-07:00" level=info msg="Windows default isolation mode: process"
time="2016-06-09T08:29:21.050681000-07:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2016-06-09T08:29:24.090650100-07:00" level=fatal msg="Error starting daemon: Error initializing network controller
: Error creating default network: HNS failed with error : Failed to create network"
```
Note that `Get-NetNat` returns nothing.

I remember that I once saw some notes about nested virtualizations. Could this be related? Are you installing CTP5 on bare metal or on a VM?

**Comment by mabead** [comment]
Note that my version of dockerd is the following:
```
PS C:\Users\Administrator> dockerd -v
Docker version 1.12.0-dev, build 8e92415
```

**Comment by StefanScherer** [comment]
I can't see that you register and start the service. It seems that you start just `dockerd`.

Try 
```
dockerd --register-service
Start-Service docker
docker version
```

I'm running TP5 in Azure and locally in VMware.

**Comment by mabead** [comment]
When I use the commands that you sent, I see the same errors but in the windows event log. Using dockerd simply prints them directly in the console.

Note that I am running under hyper-v.

**Comment by mabead** [comment]
@StefanScherer I confirm that I was also able to make it work on Azure. But on hyper-v, dockerd fails on startup. Am I at the good place to log this issue?

**Comment by pinkal-vansia** [comment]
I am facing the same issue.
```
PS C:\> dockerd --register-service
PS C:\> Start-Service Docker
WARNING: Waiting for service 'Docker Engine (Docker)' to start...
Start-Service : Failed to start service 'Docker Engine (Docker)'.
At line:1 char:1
+ Start-Service Docker
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : StartServiceFailed,Microsoft.PowerShell.Commands.StartServiceCommand
```
But if I run `dockerd` direct, I get this error,
```
PS C:\> dockerd
time="2016-06-10T09:13:39.299905900Z" level=info msg="Windows default isolation mode: process"
time="2016-06-10T09:13:39.423905000Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2016-06-10T09:13:40.844683100Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default network: HNS failed with error : Failed to create network"
```
Then I followed steps [here](https://github.com/Microsoft/Virtualization-Documentation/issues/273) and ran following command 
```
$ dockerd -H npipe:// -b "none"
$ docker network create -d nat --subnet=192.168.0.0/24 --gateway=192.168.0.1 MyNatNetwork
```
This helped me start docker daemon.
But then I could not installed the 'windowsservercore` images
```
PS C:\> Install-PackageProvider ContainerImage -Force

Name                           Version          Source           Summary
----                           -------          ------           -------
ContainerImage                 0.6.4.0          PSGallery        This is a PackageManagement provider module which h...


PS C:\> Install-ContainerImage -Name WindowsServerCore
WARNING: Save-HTTPItem: Bits Transfer failed. Job State: BG_JOB_STATE_ERROR ExitCode = 0
WARNING: Based on customer feedback, we are updating the Containers PowerShell module to better align with Docker. As
part of that some cmdlet and parameter names may change in future releases. To learn more about these changes as well
as to join in the design process or provide usage feedback please refer to http://aka.ms/windowscontainers/powershell
Get-WindowsImage : The system cannot find the file specified.
At C:\windows\system32\windowspowershell\v1.0\Modules\Containers\1.0.0.0\Containers.psm1:38 char:29
+ ... ageInfo = @(Get-WindowsImage -ImagePath $WimPath -LogPath ($env:temp+ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-WindowsImage], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.GetWindowsImageCommand
```

**Comment by mrdotmoon** [comment]
@neilpeterson It works now:-)

**Comment by pinkal-vansia** [comment]
Today, following command worked, which was not working earlier,
```
PS C:\> Install-ContainerImage -Name WindowsServerCore
```

**Comment by richardgavel** [comment]
I am seeing the same issue. I just created the Azure TP5 virtual machine in Azure. I can't even get the docker with the -b None call to work.

PS C:\Users\rgavel> dockerd -D -H npipe:// -b "None"
time="2016-08-05T15:58:37.507645600Z" level=debug msg="Listener created for HTTP on npipe (//./pipe/docker_engine)"
time="2016-08-05T15:58:37.518975000Z" level=info msg="Windows default isolation mode: process"
time="2016-08-05T15:58:37.518975000Z" level=debug msg="Using default logging driver json-file"
time="2016-08-05T15:58:37.518975000Z" level=debug msg="WindowsGraphDriver InitFilter at C:\\ProgramData\\docker\\windows
filter"
time="2016-08-05T15:58:37.518975000Z" level=info msg="[graphdriver] using prior storage driver \"windowsfilter\""
time="2016-08-05T15:58:37.518975000Z" level=debug msg="Using graph driver windowsfilter"
time="2016-08-05T15:58:37.518975000Z" level=debug msg="Max Concurrent Downloads: 3"
time="2016-08-05T15:58:37.518975000Z" level=debug msg="Max Concurrent Uploads: 5"
time="2016-08-05T15:58:37.550252500Z" level=debug msg="Stackdump - waiting signal at Global\\docker-daemon-648"
time="2016-08-05T15:58:37.612750300Z" level=debug msg="Calling proc"
time="2016-08-05T15:58:37.612750300Z" level=debug msg="hcsshim::GetSharedBaseImages  - succeeded output={\"Images\":[{\"
CreatedTime\":\"2016-05-13T22:59:13.9730000Z\",\"Path\":\"C:\\\\ProgramData\\\\Microsoft\\\\Windows\\\\Images\\\\CN=Micr
osoft_NanoServer_10.0.14300.1016\",\"Name\":\"NanoServer\",\"Version\":\"10.0.14300.1016\",\"Size\":810231121}\n,{\"Crea
tedTime\":\"2016-05-13T23:21:45.1160000Z\",\"Path\":\"C:\\\\ProgramData\\\\Microsoft\\\\Windows\\\\Images\\\\CN=Microsof
t_WindowsServerCore_10.0.14300.1000\",\"Name\":\"WindowsServerCore\",\"Version\":\"10.0.14300.1000\",\"Size\":9353920743
}\n]}"
time="2016-08-05T15:58:37.612750300Z" level=debug msg="hcsshim::CreateLayer Flavour 1 ID 54a2f0574fe634e4738d68ddace841b
d3cc3de5eb60e1a855d00b4dd9ea7050e parent "
time="2016-08-05T15:58:37.612750300Z" level=debug msg="hcsshim::CreateLayer  - succeeded id=54a2f0574fe634e4738d68ddace8
41bd3cc3de5eb60e1a855d00b4dd9ea7050e parent= flavour=1"
time="2016-08-05T15:58:37.612750300Z" level=debug msg="hcsshim::CreateLayer Flavour 1 ID 3c553f4caf50bf32226f3b69c37b45d
74b3a2e8727fa0c5cd500aaa7a996a71e parent "
time="2016-08-05T15:58:37.612750300Z" level=debug msg="hcsshim::CreateLayer  - succeeded id=3c553f4caf50bf32226f3b69c37b
45d74b3a2e8727fa0c5cd500aaa7a996a71e parent= flavour=1"
time="2016-08-05T15:58:37.612750300Z" level=debug msg="hcsshim::LayerExists Flavour 1 ID CN=Microsoft_NanoServer_10.0.14
300.1016"
time="2016-08-05T15:58:37.612750300Z" level=debug msg="hcsshim::LayerExists succeeded flavour=1 id=CN=Microsoft_NanoServ
er_10.0.14300.1016 exists=1"
time="2016-08-05T15:58:37.753385300Z" level=debug msg="Registered base layer nanoserver:10.0.14300.1016 as sha256:3f5112
ddd18577a0bb697abd97357964080848d77dba4baecf044c74ce8f25bb"
time="2016-08-05T15:58:37.753385300Z" level=debug msg="hcsshim::LayerExists Flavour 1 ID CN=Microsoft_WindowsServerCore_
10.0.14300.1000"
time="2016-08-05T15:58:37.753385300Z" level=debug msg="hcsshim::LayerExists succeeded flavour=1 id=CN=Microsoft_WindowsS
erverCore_10.0.14300.1000 exists=1"
time="2016-08-05T15:58:37.956521300Z" level=debug msg="Registered base layer windowsservercore:10.0.14300.1000 as sha256
:5bc36a3353449a04a0bba2e751a1293516adaa855bc2365a29f3f51caa9e90a6"
time="2016-08-05T15:58:37.956521300Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2016-08-05T15:58:37.956521300Z" level=debug msg="Option DefaultDriver: nat"
time="2016-08-05T15:58:37.956521300Z" level=debug msg="Option DefaultNetwork: nat"
time="2016-08-05T15:58:38.009571100Z" level=debug msg="Network Response : [  ]"
time="2016-08-05T15:58:38.020630000Z" level=debug msg="Allocating IPv4 pools for network nat (763d408aedd961eb842b6ba05d
00c380fd863176f6e725fee0aa2d884899392a)"
time="2016-08-05T15:58:38.020630000Z" level=debug msg="RequestPool(LocalDefault, 172.16.0.0/12, , map[], false)"
time="2016-08-05T15:58:38.020630000Z" level=debug msg="RequestAddress(172.16.0.0/12, <nil>, map[RequestAddressType:com.d
ocker.network.gateway])"
time="2016-08-05T15:58:38.020630000Z" level=debug msg="HNSNetwork Request ={\"Name\":\"nat\",\"Type\":\"nat\",\"Subnets\
":[{\"AddressPrefix\":\"172.16.0.0/12\",\"GatewayAddress\":\"172.16.0.0\"}]} Address Space=[{172.16.0.0/12 172.16.0.0}]"

time="2016-08-05T15:58:39.665687200Z" level=debug msg="releasing IPv4 pools from network nat (763d408aedd961eb842b6ba05d
00c380fd863176f6e725fee0aa2d884899392a)"
time="2016-08-05T15:58:39.675320900Z" level=debug msg="ReleaseAddress(172.16.0.0/12, 172.16.0.0)"
time="2016-08-05T15:58:39.675320900Z" level=debug msg="ReleasePool(172.16.0.0/12)"
time="2016-08-05T15:58:39.675320900Z" level=fatal msg="Error starting daemon: Error initializing network controller: Err
or creating default network: HNS failed with error : Failed to create network"

**Comment by masaeedu** [comment]
Same issue as @mabead here. @neilpeterson Is there some kind of additional networking hardware we need to attach to a the Windows Server 2016 VM that is already baked into the Azure template?

**Comment by enderb-ms** [comment]
Closing this issue since there has been no progress, and WS16 has already GA'd. Please feel free to open the issue again if there is something we can help with.
