### ISSUE TITLE
Build Command not able to download packages 

### ISSUE THREAD

**Issue by meta-vivek-jain** [MicrosoftDocs/Virtualization-Documentation#318]
Build command not able to download anything from the internet

Here are error details: 
PS C:\iisdemo> docker build -t iis2 .
Sending build context to Docker daemon 9.958 MB
Step 1 : FROM windowsservercore
 ---> 5bc36a335344
Step 2 : RUN powershell -Command wget -Uri http://chocolatey.org/install.ps1 -OutFile choco.ps1 -UseBasicParsin
g
 ---> Running in f926dbc14632
At line:1 char:10 name could not be resolved: 'chocolatey.org'
- sleep 1; wget -Uri http://chocolatey.org/install.ps1 -OutFile choco.p ...
-          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:Htt
    pWebRequest) [Invoke-WebRequest], WebException
  - FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShe
    ll.Commands.InvokeWebRequestCommand

The command 'cmd /S /C powershell -Command sleep 1; wget -Uri http://chocolatey.org/install.ps1 -OutFile choco.ps1 -UseB
asicParsing' returned a non-zero code: 1

Here is docker info: 
PS C:\iisdemo> docker info
Containers: 37
 Running: 0
 Paused: 0
 Stopped: 37
Images: 14
Server Version: 1.12.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: null nat
Kernel Version: 10.0 14300 (14300.1030.amd64fre.rs1_release_svc.160603-1734)
Operating System: Windows Server 2016 Datacenter Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 3.5 GiB
Name: Server2016
ID: XU2V:CWCS:HRAV:K3LG:2IRZ:WJYW:7J2J:W4GV:5YL6:JLBX:LZAX:2QYU
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

**Comment by timotei** [comment]
Are you using it behind a proxy server? Does that command work from a regular powershell/cmd?

**Comment by meta-vivek-jain** [comment]
Yes , it's working fine from a regular PowerShell/cmd.
I found workaround for this by changing DNS configuration inside docker container by following PowerShell command 
Set-DNSClientServerAddress -interfaceindex 27 -ServerAddresses ("8.8.8.8")

So I believe default DNS configuration is not correct for docker container.

**Comment by enderb-ms** [comment]
Closing this issue since WS16 has GA'd. Please feel free to open this issue again if there is still something we can help with.
