### ISSUE TITLE
docker search microsoft fails

### ISSUE THREAD

**Issue by ddobric** [MicrosoftDocs/Virtualization-Documentation#350]
When executing 'docker search microsoft', getting following error:

Warning: failed to get default registry endpoint from daemon (An error occurred trying to connect: Get http://%2F%2F.%2F
pipe%2Fdocker_engine/v1.24/info: open //./pipe/docker_engine: The system cannot find the file specified.). Using system
default: https://index.docker.io/v1/
An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/images/search?limit=25&term=microso
ft: open //./pipe/docker_engine: The system cannot find the file specified.

**Comment by ddobric** [comment]
I got this working. 
Was following this article: https://msdn.microsoft.com/virtualization/windowscontainers/quick_start/quick_start_windows_server

The issue is that docker service is not in running state after VM has started. According to article above  we should jump to step 4 if VM is provisioned by using ARM Azure Template.
 
This seems not to be correct. JUmping to step 4 is ok, bu we need to start docker service:

Start-Service docker

After that allworks fine.

**Comment by neilpeterson** [comment]
The service should start automatically however I am also seeing an issue with service start up. I will bring this up with the team.

**Comment by StefanScherer** [comment]
I've tried the "Deploy to Azure" link in https://msdn.microsoft.com/virtualization/windowscontainers/quick_start/quick_start_windows_server as I have problems using the "Windows Server 2016 Core with Containers Tech Preview 5" in Azure portal, but the Docker Engine service is not running. Even after running `Start-Service docker` I only get an error. Tried different regions (West US, North Europe), but always the same.

**Comment by kobayashilin** [comment]
Hi,
I have the same problem. 
This warning disappears after I type this command
`docker-machine env`
It will show some information, notice these : 
```
# Run this command to configure your shell:
# & "C:\Program Files\Docker Toolbox\docker-machine.exe" env | Invoke-Expression
```
Run this command and it works. Hope this solution works for you.

**Comment by enderb-ms** [comment]
Closing this issue since it has been resolved above.
