### ISSUE TITLE
Document how developers that use Windows 10 can run /create containers that are based on Server Core images

### ISSUE THREAD

**Issue by sherland** [MicrosoftDocs/Virtualization-Documentation#353]
We are planning to create containers for most of the components our company creates. Since the components currently require the full .net (not core) we have to use Server Core images. 

[.../windowscontainers/deployment/system_requirements.md#supported-os-images](https://github.com/Microsoft/Virtualization-Documentation/blob/master/virtualization/windowscontainers/deployment/system_requirements.md#supported-os-images) currently specifies that Windows Server container is not availabe on Windows 10

This is temporary? Seriously, say yes. ;-)

Please document how developers and build machines that use Windows 10 are expected to create containers that are based on Server Core images.

**Comment by erichexter** [comment]
​I was told that WindowsServerCore will work on windows 10 containers when
server 2016 is released. Which we expect to be in September, my guess is
 it will be during the Ignite conference, since they like to release stuff
at keynotes of conferences.

**Comment by PatrickLang** [comment]
Yes, Windows 10 Anniversary Edition is not able to run Windows Server Core 2016 Tech Preview containers. An updated `microsoft/windowsservercore` image will be released when Windows Server 2016 is released that will work on Win10

**Comment by sherland** [comment]
Great!
How about updating the table in system_requirements.md from `Not Available` to `Available when Windows Server 2016 RTM` ?

**Comment by enderb-ms** [comment]
Closing this issue as this now works in Windows 10. See [this guide](https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-10) for steps on how to set up containers on Windows 10.
