### ISSUE TITLE
example from Step 3 Windows Server quick start does not work

### ISSUE THREAD

**Issue by rs38** [MicrosoftDocs/Virtualization-Documentation#400]
`docker run -it -p 80:80 microsoft/iis cmd`

whoch loads image from repo and extracts but then stucks when running interactively by only showing "service w3svc started" instead of cmd.exe prompt.
Tried with different machines.
Entrypoint and running process seems to servicemonitor.exe

any idea?

exactly reproducable by quitting with ctrl-c and restarting with `docker start name -a`

**Comment by rs38** [comment]
meanwhile I can probably understand the sense of servicemonitor.exe (instead of ping to keep the IIS running) but there will be no interactive session possible as explained in the docs. probably docker images change too fast currently...

**Comment by cniweb** [comment]
I have the same issue!

**Comment by rs38** [comment]
as I understood: the microsoft/iis images is build with a docker file that uses  ENTRYPOINT ["C:\\ServiceMonitor.exe", "w3svc"] at the end. This is not overridable with the docker run, as it would be with dockerfile created with CMD instead of ENTRYPOINT. the exact purpose of choosing either way should be explained by more experienced experts.  I will put this as an issue/question in the repo of the docker image

**Comment by rs38** [comment]
to workout the next steps in the docs you can do it e.g. with `docker exec <iis-container-ID> cmd del C:\inetpub\wwwroot\iisstart.htm`

**Comment by ic3guy** [comment]
This entry covers another workaround http://stackoverflow.com/questions/40391896/cannot-launch-interactive-session-in-windows-iis-docker-container

docker run --entrypoint powershell -it -p 80:80 microsoft/iis

**Comment by ic3guy** [comment]
Yes @rs38 the documentation is still incorrect. I only found the solution at http://stackoverflow.com/questions/40391896/cannot-launch-interactive-session-in-windows-iis-docker-container
definitely not obvious for a docker newbie.

**Comment by rs38** [comment]
the according PR is open for many days and stuck for unknown reasons :(
https://github.com/Microsoft/Virtualization-Documentation/pull/458

**Comment by ic3guy** [comment]
Given that Docker containers for Server 2016 is still quite "bleeding edge", I don't mind the wait.

**Comment by enderb-ms** [comment]
Closing this issue as the PR mentioned above has been merged. Please reopen if there is still something we can help with.
