### ISSUE TITLE
the new container samples TOC linking in the live site is not up2date

### ISSUE THREAD

**Issue by rs38** [MicrosoftDocs/Virtualization-Documentation#407]
Virtualization-Documentation/virtualization/windowscontainers/TOC.md seems correct but live it show dead links like
https://github.com/Microsoft/Virtualization-Documentation/tree/master/windows-container-samples/windowsservercore

**Comment by PatrickLang** [comment]
Ping @taylorb-microsoft

**Comment by enderb-ms** [comment]
Closing this issue since the link has been removed from live.
