### ISSUE TITLE
I don't find the default host network

### ISSUE THREAD

**Issue by Shuliyey** [MicrosoftDocs/Virtualization-Documentation#409]
windows native docker doesn't provide default host network

If  I do **docker network ls**

I only see 2 network, I'm looking for the host network. It doesn't exist, so I can't create containers with the **"--net=host"** parameter (which specifies the same network settings as the host)

``` cmd
C:\Windows\system32>docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
eca9ac6f8b47        nat                 nat                 local
ff2a1b128dfb        none                null                local
```

**Comment by JMesser81** [comment]
Sorry for the delay on this. We do not support the **host** network driver on Windows today. Can you let me know why you want to connect your containers to a host network?

If you just need your containers to be on the same physical network as the host, you can use the **transparent** network driver.

**Comment by enderb-ms** [comment]
Closing this issue as it seems to have been answered above. Please feel free to open this issue again if there is still something we can help with.
