### ISSUE TITLE
Unable to ping containers created with transparent network from other hosts

### ISSUE THREAD

**Issue by sasiezilmadhavan** [MicrosoftDocs/Virtualization-Documentation#430]
Environment : Windows Server 2016 in Azure 

Docker Version : 1.12.2-cs2-ws-beta

Kernel Version: 10.0 14393 (14393.321.amd64fre.rs1_release_inmarket.161004-2338)

---

I have created a transparent network with

docker network create -d transparent trans

and created two containers say A and B in the same network.  I am able to ping A from B and vice versa.  But i am NOT able to ping the containers from its host and of course from any other machines.  Then i removed previous and created a network with subnet as

docker network create -d transparent --subnet=10.5.0.1/23 --gateway=10.5.0.4 trans

where the subnet & gateway are same as the container host.   Then created a container in the network as

docker run -d --network trans --ip 10.5.0.20 microsoft/iis

Now i am able to ping container's IP from the host machine.  But UNABLE to ping the containers from different host and also most importantly, from the container unable to ping the VM where SQL Server is running.  Note, all the VMs are in the same Azure Virtual network.  

Not sure if this is related to MacAddressSpoofing??  According to Windows Server Containers Article, MacAddressSpoofing should be enabled in VM host.  As this is Azure VM, its not possible to enable MacAddressProofing. 

Any help will be greatful.

kind regards,

Sasi

**Comment by friism** [comment]
ping @JMesser81

**Comment by JMesser81** [comment]
Hi Sasi - could you let me know why you want to create a transparent container network on Azure? What is your use-case?

Generally speaking, we only support the nat network / driver on WS2016 Azure VMs

**Comment by sasiezilmadhavan** [comment]
Thanks @JMesser81 for quick response,

Our use case is to containerise our existing enterprise platform and applications so that it seamlessly work in our customer's Enterprise data centres (private cloud) and in the long run should naturally fit-in when we evolve to Saas model of our products.  In our exploration, theoretically Docker with Swarm mode is promising for our needs.  That's our long story short and on this journey, we found the cool features of Swarm mode say, Service Discovery, Fault tolerance & mid-tier load balancing are not yet supported with Windows 2016 dockers.  We are doing our evaluation in the Windows 2016 server environment setup in Azure.

We did containerised our WCF services and Web tier of one of our product and necessary platform services (around 7 different container images).  We want all of  those containers to run in parallel, where each one of them should able to talk among themselves.  For now, we kept the database (Sql Server) in a separate Virtual Machine and the services in containers should be able to connect to them.

From the [documentation ](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/management/container_networking?f=255&MSPPError=-2147217396)  we thought transparent network is a intermediate step (until overlay network is available) to move ahead and facing challenges while accessing the database from the containers.

Thus we have the following questions:

With Transparent Network:

**- Accessing the database in a azure virtual machine from the containers in Azure Win 2016 host.
- Connectivity between the containers running across two Azure Win 2016 servers
- Any interim solution or workarounds to make Swarm mode work.**

kind regards,
Sasi

**Comment by kallie-b** [comment]
Hi Sasi, apologies for the delay. 
 
It's awesome to hear that you're interested in using Docker with Swarm mode and Windows/Azure to get your containerized applications running on the cloud. It's true that Swarm is promising for your scenario, and the issue that you're describing would be a classic use case for overlay networks with Service Discovery (as well as the other features that will be available when Swarm mode for Windows is fully supported). This is high priority, and certainly part of our plan for implementing full support for overlay networks and Swarm mode on Windows Server and Azure.
 
The short answer to your question is that your current workaround--to connect your container and database hosts using a transparent network--is not currently supported on Azure. **The virtual networking infrastructure on Azure is not configured to allow your Win 2016 hosts to discover each other or your Azure VM over a transparent network.** 

**However,** there is another workaround using NAT networking that you may be able to use until your scenario is fully supported.
 
You should be able to configure your endpoints to communicate container-to-container on a single host using the default NAT network, and across hosts (container-to-container or container-to-database service and vice-versa) using exposed ports. A clear downside to this solution is that Service Discovery will be local to each host, and not span across hosts; in other words, you will need to configure each host to "know" the IP address and exposed ports of the services that it needs to communicate with on  other hosts. However, Service Discovery is supported on NAT networks, so you will be able to take advantage of it internally on each host **(i.e. NAT network Service Discovery is currently supported on each host, but not across hosts).** 

For instance, you might expose your database on port 1433 of the SQL Server host and some containerized ‘web’ service on port 80 of one of your container hosts. In this case, you’d need to configure all of your host machines to access the database via its hosts’ external IP address and port 1433, and the web service via its hosts’ external IP address and port 80. 

You also mentioned being unable to ping containers from their host and from external machines. In the NAT workaround described above, you shouldn't have an issue pinging your containers from external machines--again, you'll just need to identify containers/services via an exposed port on the host, then you'll be able to access them using their ports and the host's external IP address. 

As far as pinging a container from its own host, to do that you need to use the container's internal IP. You can use 'docker inspect <container instance ID>' to determine a container's internal IP address.
 
Hopefully this helps, and thanks again for your interest in these services. Don't hesitate to let us know if you need any further clarity.

**Comment by rs38** [comment]
Can we get this worthy information somewhere in the right place in the right docs?

**Comment by sasiezilmadhavan** [comment]
@kallie-b Thank you for the update.  I have gone through the [article ](https://blogs.technet.microsoft.com/virtualization/2016/10/18/use-docker-compose-and-service-discovery-on-windows-to-scale-out-your-multi-service-container-application/)   by you and was able to successfully run multi-containers in single host using docker-compose.

**Comment by kallie-b** [comment]
Great, I'm glad I could help!

@rs38 For now our best sources are these:

- [Container networking doc](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/management/container_networking#multiple-nat-networks)

- [Docker Compose and Service Discovery blog post](https://blogs.technet.microsoft.com/virtualization/2016/10/18/use-docker-compose-and-service-discovery-on-windows-to-scale-out-your-multi-service-container-application/)

I'll take a look and see if there are more/better places that this information needs to be--thanks for the suggestion/heads-up :)

**Comment by StrongMonkey** [comment]
Will Docker Swarm support the following features for Windows Server 2016 in the **future**?
1. Service-discovery on multiple host for both nat and transparent network mode.
2. Overlay-Network

**Comment by kallie-b** [comment]
@StrongMonkey 

Apologies for the delayed reply--I missed your comment until now. 

We're unable to discuss our feature plans before they are officially announced, but certainly keep an eye on our announcements in the near future ;) 

We'll be using our new Twitter handle, @Microsoft_SDN, to make container networking/orchestration related announcements in the future so that's an easy place for you to keep an eye on our latest features.
