### ISSUE TITLE
Update to documentation to include (Import-PackageProvider DockerMsftProvider)

### ISSUE THREAD

**Issue by artisticcheese** [MicrosoftDocs/Virtualization-Documentation#431]
In documentation one step is missing for pulling images. Once you install package provider you need to import it which is missing.

**Comment by friism** [comment]
Are you thinking about the `docker run microsoft/sample-dotnet` step? Docker will pull the images automatically as part of the run.

**Comment by artisticcheese** [comment]
No. On this page
https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_server

**Comment by rs38** [comment]
Friism is perfectly right, but I also ran into that misunderstanding like cheese, some weeks ago.
Voting for close

**Comment by PatrickLang** [comment]
@enderb-ms can you take this?

**Comment by enderb-ms** [comment]
Closing this issue as it has been resolved above.
