### ISSUE TITLE
Document how memory settings and heuristics work for Windows containers

### ISSUE THREAD

**Issue by PatrickLang** [MicrosoftDocs/Virtualization-Documentation#477]
See https://github.com/docker/docker/issues/27892

Memory Settings 
- How to find available memory inside Windows Server Container
- How to find available memory inside Hyper-V Container
- How to set each

CPU Settings - what works / doesn't
- `--cpu-count`
- `--cpu-shares`
- `--memory`

If we can document on docker/docker, we should. Otherwise, document it here

**Comment by PatrickLang** [comment]
pinging myself as a test

**Comment by PatrickLang** [comment]
with right syntax this time @patricklang

**Comment by PatrickLang** [comment]
The current heuristic to calculate the size of the utility VM (--isolation=hyperv) is <configured memory for the container> + 256 MB, rounded up to the next full 512 MB. For a container setting of 512 MB this turns out to be 1 GB, which is also the default if you don’t specify a memory setting.

**Comment by shanselman** [comment]
Ping...hit the limit today @PatrickLang

**Comment by PatrickLang** [comment]
Fixed in Docker docs: https://github.com/moby/moby/pull/32724
