### ISSUE TITLE
Add Uservoice to container links

### ISSUE THREAD

**Issue by taylorb-microsoft** [MicrosoftDocs/Virtualization-Documentation#489]
https://windowsserver.uservoice.com/forums/304624-containers

**Comment by rs38** [comment]
This uservoice Container section is extremely outdated. Would be very useful to close or remove many of the uncommented voices that makes no sense after one year....

**Comment by taylorb-microsoft** [comment]
@rs38 I agree - I'll try to do that this week before we add it to the docs

**Comment by enderb-ms** [comment]
I've updated the "Community" section of the landing page to include a link to the uservoice: https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/live/virtualization/windowscontainers/index.md
