### ISSUE TITLE
Can Microsoft stop emphasizing using docker command line vs Powershell

### ISSUE THREAD

**Issue by artisticcheese** [MicrosoftDocs/Virtualization-Documentation#504]
Bearing in mind there is perfectly usable Powershell cmdlets in dealing with containers, why all Microsoft samples and tutorials are emphasizing using docker executable instead. Not sure what will be the advantages of using archaic interface compared to nicely built fully complaint powershell cmdlet. I understand underlying is just REST calls back to docker but powershell interface samples shall be provided along with docker or even better completly replace them.

**Comment by SleeperSmith** [comment]
+1

**Comment by artisticcheese** [comment]
Example below. How to delete all running containers? Searching Internet provides some examples how to do it from bash etc with bunch of obscure switches etc. Anybody knowing powershell will come up with answer below without even going to any documentation. Not only that but anybody who can basic computer skill will probably figure out what syntax doing below unlike docker based commands. We went on 10 year learning curve to embrace Powershell just to get be dumped back into dark ages of command line processors.

`get-container | Remove-Container -Force`

**Comment by friism** [comment]
This works fine in PowerShell and in Bash: `docker rm $(docker ps -aq)`.

**Comment by StefanScherer** [comment]
I just had an interesting discussion about Docker CLI vs. PowerShell bindings here at `#msts2016` - I think there will need for both. Windows admins using and having understood PowerShell, and others that really are used to the Docker CLI, coming from Mac/Linux (and Windows) and using it for all their platforms.

**Comment by artisticcheese** [comment]
Yes it works in both cases just fine. Question is why 90% of Microsoft documentation relies on docker.exe for container management instead of Powershell. This will be pretty steep dislearning curve for any Powershell programmer go back to try to figure out all the switches and parameters for docker.exe as opposed with essen

**Comment by PatrickLang** [comment]
I don't think we can move everything to PowerShell only because we also have people familiar with Docker but not PowerShell. Do you have any suggestions on how to balance both? Would having duplicate documents or samples be confusing?

**Comment by artisticcheese** [comment]
Well I don't know how to fix the issue but current setup where all samples/documentation/demos are almost entirely based on command line is detrimental in learning. MSDN frequently for .NET samples provide documentation in 3 different languages (VB.NET, C#, F#).  So probably providing examples in Powershell will fix the gap but as you said, but it will be more confusing. In genral I'd prefer really Microsoft to make a decision what they want Windows admins to use to administer Windows containers and stick with it. Current situation where there is no clear guidance can cause some deadend learning tracks (like when .NET programming had a choice of VB.NET vs C# and some people chose VB.NET and end up in dead end 10 years later).

**Comment by PatrickLang** [comment]
How do you feel about pages with language switchers like this? 

https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-deploy

**Comment by artisticcheese** [comment]
Yes, this will work or it can be done in tabs like MSDN does instead of line by line like below.


https://msdn.microsoft.com/en-us/library/windows/apps/system.io.windowsruntimestreamextensions(v=vs.105).aspx

**Comment by enderb-ms** [comment]
Since we have seen that users of containers in Windows 10 and Windows Server have focused on the Docker CLI, we do not currently have any plans to also add the PowerShell commands on the documentation.
