### ISSUE TITLE
Windows 10, translated docs still show 1.13.0-dev.zip

### ISSUE THREAD

**Issue by StefanScherer** [MicrosoftDocs/Virtualization-Documentation#510]
It seems that the translated docs are still lagging behind. For example the page

https://msdn.microsoft.com/de-de/virtualization/windowscontainers/quick_start/quick_start_windows_10

still shows the installation steps for 1.13.0-dev.zip which is no longer downloadable.

The original page

https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_10

already has 1.13.0-rc2.zip

Using the auto forward URL to the user's language 

https://msdn.microsoft.com/virtualization/windowscontainers/quick_start/quick_start_windows_10

it's hard to tell if the user gets the current installation steps.

**Comment by PatrickLang** [comment]
Unfortunately the localized docs will be out of date for a few more weeks. We're making some adjustments on the publishing backend and they'll start updating those docs once it's completed early next year.

**Comment by StefanScherer** [comment]
No problem. So if you are tracking this internally it's also fine to close this issue.

**Comment by scooley** [comment]
Updating to say we are working on this (keeping localized content in sync with en-us).

Thank you, @StefanScherer

**Comment by StefanScherer** [comment]
Translated docs still are behind. 👼 

https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-10 already suggests to use Docker4Windows

https://docs.microsoft.com/de-DE/virtualization/windowscontainers/quick-start/quick-start-windows-10 still installs the docker-17.03.0-ce.zip with PowerShell commands.

**Comment by PatrickLang** [comment]
@scooley any updates?

**Comment by enderb-ms** [comment]
Looks like https://docs.microsoft.com/de-DE/virtualization/windowscontainers/quick-start/quick-start-windows-10 now suggests D4W. I'll close this issue now, but feel free to open if there is still more for us to do.
