### ISSUE TITLE
Could not establish trust relationship for the SSL/TLS secure channel in windows container

### ISSUE THREAD

**Issue by renerchen** [MicrosoftDocs/Virtualization-Documentation#511]
I have got a windows image with Chocolatey. Because behind a proxy , so  firstly I set the proxy as following：
  choco config set proxy http://xxx:port
  choco config set proxyUser 'xxx'
  choco config set proxyPassword 'xxx'

Then I install winrar， it works！
When I install python， it has the error：
C:\>choco install python --force
Chocolatey v0.10.3
Installing the following packages:
python
By installing you accept licenses for the packages.

python3 v3.5.2.20161029 (forced) [Approved]
python3 package files install completed. Performing other installation steps.
Using explicit proxy server 'http://XXX:8080'.
Attempt to get headers for https://www.python.org/ftp/python/3.5.2/python-3.5.2-amd64.exe failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://www.python.org/ftp/python/3.5.2/python-3.5.2-amd64.exe'. Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."
Downloading python3 64 bit
  from 'https://www.python.org/ftp/python/3.5.2/python-3.5.2-amd64.exe'
Using explicit proxy server 'http://XXX:8080'.
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://www.python.org/ftp/python/3.5.2/python-3.5.2-amd64.exe'. Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."
This package is likely not broken for licensed users - see https://chocolatey.org/docs/features-private-cdn.
The install of python3 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\python3\tools\chocolateyInstall.ps1'.
 See log for details.

python v3.5.2.20161029 (forced) [Approved]
python package files install completed. Performing other installation steps.
 The install of python was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

Chocolatey installed 1/2 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - python3 (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\python3\tools\chocolateyInstall.ps1'.
 See log for details.

How to solve it with powershell commads.

**Comment by StefanScherer** [comment]
It seems you have a certificate installed on your host for that proxy. 
Adding a pfx cert in a VM I have used this code
```powershell
$pfx = new-object System.Security.Cryptography.X509Certificates.X509Certificate2
$pfx.import("C:\path-to-cert\ca.pfx","","Exportable,PersistKeySet")
$store = new-object System.Security.Cryptography.X509Certificates.X509Store(
    [System.Security.Cryptography.X509Certificates.StoreName]::Root,
    "localmachine"
)
$store.open("MaxAllowed")
$store.add($pfx)
$store.close()
```

Haven't tried this inside a container, but I thinks you need something like that to add the cert to the trusted store.

**Comment by renerchen** [comment]
@StefanScherer  I had import cer with the fowllowing commands：

 $file = (Get-ChildItem -Path C:\test\software\CER\AddTrust.cer)
 $file | Import-Certificate -CertStoreLocation cert:\localMachine\Root
 $file = (Get-ChildItem -Path C:\test\software\CER\goDaddyClass2.c
 $file | Import-Certificate -CertStoreLocation cert:\localMachine\Root

It doesn't work！

**Comment by mylesbkeating1993** [comment]
@renerchen is this still an issue?  Let me know how I can help :)

**Comment by enderb-ms** [comment]
Looks like there has been no more progress on this, so I'll go ahead and close this issue. Please open the issue again if there is something we can help with.
