### ISSUE TITLE
credentialspec.psm1 module shall respect "graph" settings in docker

### ISSUE THREAD

**Issue by artisticcheese** [MicrosoftDocs/Virtualization-Documentation#547]
If docker is configured to store images in alternative location via "graph" settings. For example ` "graph": "d:\\images",` then CredentialSpec module shall respect that and put resulting credentialspec file in proper location. Right now it puts it in default location of `C:\ProgramData\Docker\CredentialSpecs`

**Comment by mylesbkeating1993** [comment]
Hi @artisticcheese ,

There is faster and better support in the docker forums: forums.docker.com

I'm a little confused - is this a problem you have?  

Or is this a suggestion for how you would like the Credentialspec module to work?

**Comment by PatrickLang** [comment]
Sorry about the delay here – this is definitely one I need to fix. I’m working on another push to this area of the docs and samples after Dockercon

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
