### ISSUE TITLE
CleanupContainerHostNetworking.ps1 is outdated

### ISSUE THREAD

**Issue by dermeister0** [MicrosoftDocs/Virtualization-Documentation#606]
I think CleanupContainerHostNetworking.ps1 needs to be updated.

## Readme is not correct.

This command is wrong:
```
.\CleanupContainerHostNetworking.ps1 -ForceCleanup
```

Correct commands:
```
.\CleanupContainerHostNetworking.ps1 -Cleanup
.\CleanupContainerHostNetworking.ps1 -Cleanup -ForceDeleteAllSwitches
```

## Service name is not correct.

```
Get-Service : Cannot find any service with service name 'docker'.
At C:\Users\anton\Desktop\CleanupContainerHostNetworking.ps1:227 char:15
+     $docker = Get-Service docker
+               ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (docker:String) [Get-Service], ServiceCommandException
    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand
```

Need to handle both **docker** and **com.docker.service** names.

## Cmdlet name is outdated.

I noticed that script tries to find **Get-ContainerNetwork** cmdlet. I guess the new name is **Get-ContainerNet**.

----

Also I noticed warnings on my PC:

> Error response from daemon: nat is a pre-defined network and cannot be removed
> Error response from daemon: none is a pre-defined network and cannot be removed

I guess it's not possible to delete **nat** in recent Docker versions.

**Comment by JMesser81** [comment]
Yes, we're working to update. Still working on PR https://github.com/Microsoft/Virtualization-Documentation/pull/597 to update and make sure this works with Windows 10 Anniversary Edition, Windows 10 Creators Update, and Windows Server 2016. 
ping @kallie-b

**Comment by kallie-b** [comment]
Thanks for the notes here, and apologies for the delay. I'll devote time to updating the script and README file *this week.*
