### ISSUE TITLE
Add Base Container Comparison doc

### ISSUE THREAD

**Issue by kendrahavens** [MicrosoftDocs/Virtualization-Documentation#633]
### Base Container Comparison doc
Could we add a doc that compares the supported features of Windows Server, Windows Server Core, the WindowsServerCore base image, and Windows Nano Server base image? I always seem to be looking for a complete list, but have yet to find one. This might be a good thing to add to the README on DockerHub for these images. Something similar to this [doc](https://msdn.microsoft.com/en-us/library/dd184075.aspx), but extended.

**Comment by cwilhit** [comment]
Hi Kendra, a clarifying question: are you asking for feature comparison for the container _host OS_ or the container _runtime OS_? The supported runtimes for containers are nanoserver and servercore (and Linux). The supported Host OS is Server w/ UI, Server core, Pro/Enterprise. The doc you linked to would be describing difference between two Host OS flavors.

**Comment by kendrahavens** [comment]
I am requesting for the container OSes _and_ the host OSes to be compared. Many users are trying to figure out if their app running on Windows Server can be containerized with out changing their code, but they aren't sure what processes can be containerized seamlessly and what conditions would make containerization more difficult.

**Comment by cwilhit** [comment]
Okay, this is something I can look into.

**Comment by cwilhit** [comment]
Added a blurb on nano server vs server core in commit 9d38a9e94227d19df2777b279adf0a8b2ff9a9ea to give a little guidance on the differences between the two container runtimes. The number of removed dependencies in nano was extremely long so we've instead opted to call out a couple of top changes.
