### ISSUE TITLE
Where is current Convert-WindowsImage tools?

### ISSUE THREAD

**Issue by Nirmal4G** [MicrosoftDocs/Virtualization-Documentation#651]
In the [ReadMe](/MicrosoftDocs/Virtualization-Documentation/blob/live/hyperv-tools/Convert-WindowsImage/README.md), the link for the [Convert-WindowsImage](/Microsoft/Convert-WindowsImage) is broken! GitHub says the repo does not exist!

So, If the repo is either private or doesn't exist, where can I look for the updated `Convert-WindowsImage` tools?

I still use these to tools to preview Windows (Server, client, nano server, iot) insider editions without corrupting my existing installations, but lately there have been problems with latest insider images!

**Comment by scooley** [comment]
Updated the README.  I don't know which script is the most up-to-date but the one here is the one we use in Hyper-V as needed.
