### ISSUE TITLE
What's the right way to install/enable/add Hyper-V?

### ISSUE THREAD

**Issue by kallie-b** [MicrosoftDocs/Virtualization-Documentation#695]
This is a point of confusion that has crossed my path several times recently, including with customers/partners. **What's the right way to install/enable/add Hyper-V?**

**ADD**
The way that I personally use is:  `Add-WindowsFeature Hyper-V`
And if I want PowerShell Cmdlets with it: `Add-WindowsFeature Hyper-V -IncludeManagementTools`

**INSTALL**
But [our documentation](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/get-started/install-the-hyper-v-role-on-windows-server) currently recommends: `Install-WindowsFeature -Name Hyper-V -ComputerName <computer_name> -IncludeManagementTools -Restart`

**ENABLE**
And [elsewhere](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v) I've seen: `Enable-WindowsOptionalFeature -Online -FeatureName:Microsoft-Hyper-V -All`

### **Which one?**
What's the correct way? What are the differences between these three ways? Does the recommended way differ between Windows 10 and Windows Server?

(And of course I'll be happy to create a PR for any updates needed to the docs on this, I just want to clarify my own understanding first)

@scooley @PatrickLang

**Comment by syalachigere** [comment]
The following two commands seem to work for me but I am not sure if this is the correct way.

```
Enable-WindowsOptionalFeature -Online -FeatureName:Microsoft-Hyper-V -All
Install-WindowsFeature -Name Hyper-V-Powershell

```

**Comment by taylorb-microsoft** [comment]
Install-WindowsFeature is only on Server, where "Enable-WindowsOptionalFeature" is part of DISM and on client and server.  Personally I use that as it works on both.  You can also use DISM.exe if you wanted something outside of PowerShell (DISM.exe /Online /Enable-Feature /FeatureName:Microsoft-Hyper-V-All /All)
