### ISSUE TITLE
Great instructions!

### ISSUE THREAD

**Issue by chrisbalzat** [MicrosoftDocs/Virtualization-Documentation#764]
These were very helpful (and up to date!) which made it so simple for me to follow them, thank you ❤

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10344c5d-274e-de75-ecb6-11d53a377986
* Version Independent ID: 4cea53b8-1864-f12b-f0d9-f208743475c8
* Content: [Create a Virtual Machine with Hyper-V](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/quick-create-virtual-machine)
* Content Source: [virtualization/hyper-v-on-windows/quick-start/quick-create-virtual-machine.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/hyper-v-on-windows/quick-start/quick-create-virtual-machine.md)
* Service: **unspecified**
* Product: **windows-10-hyperv**
* GitHub Login: @scooley

**Comment by scooley** [comment]
Thank you :)
