### ISSUE TITLE
AMD support

### ISSUE THREAD

**Issue by saywhut2** [MicrosoftDocs/Virtualization-Documentation#770]
When will this be available for AMD processors, particularly Ryzen and EPYC chips?  I really want to get an S2D lab going but I can't because the virtualization extensions are not supposed on AMD yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a13cf32-4be1-94d9-b764-0faf79372065
* Version Independent ID: 6787036e-5a30-bd17-e87a-54f61b0ba47f
* Content: [Nested Virtualization](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/nested-virtualization)
* Content Source: [virtualization/hyper-v-on-windows/user-guide/nested-virtualization.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/hyper-v-on-windows/user-guide/nested-virtualization.md)
* Service: **windows-10-hyperv**
* Product: **windows-10-hyperv**
* GitHub Login: @johncslack

**Comment by johncslack** [comment]
We'd love to support nested virtualization on AMD -- it's definitely something we want to do in a future release.  

That said, it isn't supported today, and I can't commit to any timeline.  Please check back later!

**Comment by saywhut2** [comment]
This was released a year and a half ago... Is there even an ETA?

**Comment by johncslack** [comment]
There are no updates at this point in time.

**Comment by rossuhrig** [comment]
Any updates on this? We are currently in the process of evaluating responses to replace our virtual hosts. I keep pushing AMD for price/security reasons and yet I still see this is a no show. There would likely be more requests for this if you actually put a timeframe on support. People like ourselves that are going through these processes are being kept from choosing AMD. That and MS pushing to go to core count really makes me think that Intel is back at their old games and keeping AMD at bay. Competition is a good thing everyone, I'm sure everyone but Intel would not want to go back to no server competition, including Microsoft.

**Comment by hrkrx** [comment]
Any Updates on this?

**Comment by Dresel** [comment]
> 
> 
> We'd love to support nested virtualization on AMD -- it's definitely something we want to do in a future release. That said, it isn't supported today, and I can't commit to any timeline. Please check back later!
> 
> In general, to help with prioritization, please file feedback like this in the Windows 10 feedback hub.

More than a year has passed and still no AMD support? This is really frustrating...
