### ISSUE TITLE
The information is outdated

### ISSUE THREAD

**Issue by lostmsu** [MicrosoftDocs/Virtualization-Documentation#773]
At the very least, "Virtualizing GPUs using RemoteFX" is now available on the client Hyper-V, and has been for a while.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 223b9ea7-e2c0-4c6b-6d55-9125274d26ce
* Version Independent ID: 85c7005e-33b2-ae0b-a919-f056d14cf0ac
* Content: [Introduction to Hyper-V on Windows 10](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/about/#differences-between-hyper-v-on-windows-and-hyper-v-on-windows-server)
* Content Source: [virtualization/hyper-v-on-windows/about/index.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/hyper-v-on-windows/about/index.md)
* Product: **windows-10-hyperv**
* GitHub Login: @scooley

**Comment by scooley** [comment]
Fixed.
