### ISSUE TITLE
Get-VMSwitch cmdlet not present

### ISSUE THREAD

**Issue by pjh** [MicrosoftDocs/Virtualization-Documentation#775]
One of the screenshots above shows the Get-VMSwitch cmdlet for viewing vSwitch information. Get-VMSwitch does not seem to be present in Windows Server version 1803 by default. What is the recommended way to obtain this cmdlet?

My environment does not permit a full Hyper-V installation (running in a VM without nested virtualization) but by invoking the Enable-WindowsOptionalFeature and Install-WindowsFeature commands repeatedly / in the right order, I was eventually able to get access to the cmdlet. I'd like to know Microsoft's recommended way to obtain the Get-VMSwitch cmdlet for containers without a full Hyper-V installation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3be8120-7fc1-9818-53d4-61e7d3f36175
* Version Independent ID: 38825f46-278d-7da0-d538-a1c7d1d96557
* Content: [Windows Container Networking](https://docs.microsoft.com/en-us/virtualization/windowscontainers/container-networking/architecture#container-network-management-with-host-network-service)
* Content Source: [virtualization/windowscontainers/container-networking/architecture.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/container-networking/architecture.md)
* Service: **windows-containers**
* Product: **windows-containers**
* GitHub Login: @JMesser81

**Comment by doctordns** [comment]
Get-VMSwitch is a cmdlet in the Hyper-V module. You can install the Hyper-V RSAT tools in a variety of ways (depending on the edition of  Windows 10). The recommended method of getting this command is to install the RSAT tools for Hyper-V.  See: https://support.microsoft.com/en-us/help/2693643/remote-server-administration-tools-rsat-for-windows-operating-systems

**Comment by daschott** [comment]
Can't this be done via `dism /Online /Enable-Feature /FeatureName:Microsoft-Hyper-V /All /NoRestart` ?

**Comment by doctordns** [comment]
You can certainly use DISM. I find using native PowerShell cmdlets to be superior. And if you are going to add Hyper-V, presumably you want to manage VMs later. All the more reason to install PowerShell cmdlets and move on.

Oh - and just a small comment. If you enable Hyper-V on a host, you have to reboot the machine. The reason for this is that when you are running Hyper-V on a host, the parent Partition is actually running in a separate VM. You have to reboot the host to put the hypervisor into the software stack. Your code did do the reboot.

**Comment by lanoxx** [comment]
Is there a way to install these tools on Window Server Core? I used the above `dism` command but `Get-VMSwitch was still not available.

**Comment by daschott** [comment]
AFAIK this works without issues on Windows Server 1809 after hyper-v is installed. 1803 is going out of support in a week:
https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet

so I am closing this issue.

**Comment by MichaelMc64** [comment]
I'm looking at a Server 2019 Core install build version 17763 which is version 1809, Hyper-v with several running hosts. Get-vmswitch is not a recognized cmdlet, so that blows that theory.
And Doctordns, I would also prefer using Powershell over dism to install the RSAT feature. Too bad the linked article does not provide instructions for how to do that.

**Comment by rsadix** [comment]
I installed the hyper-v role on Server Core 2022 using `dism /Online /Enable-Feature /FeatureName:Microsoft-Hyper-V /All` and could not run Get-VMSwitch from PowerShell. Running this command in PowerShell enabled the Get-VMSwitch command (without restarting) `Install-WindowsFeature -Name Hyper-V -IncludeManagementTools`
