### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by samyyvaldez2515** [MicrosoftDocs/Virtualization-Documentation#782]
Help me open

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 604d834f-6f94-0a37-12b6-a10dcf7c9fa3
* Version Independent ID: 4bd4ce05-bdde-f450-ee68-9fcd2cbca48e
* Content: [Windows 10 Hyper-V System Requirements](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/reference/hyper-v-requirements#verify-hardware-compatibility)
* Content Source: [virtualization/hyper-v-on-windows/reference/hyper-v-requirements.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/hyper-v-on-windows/reference/hyper-v-requirements.md)
* Service: **windows-10-hyperv**
* Product: **windows-10-hyperv**
* GitHub Login: @scooley

**Comment by scooley** [comment]
Not enough info.
