### ISSUE TITLE
It is awful that you prevent Home users from enabling hyper v

### ISSUE THREAD

**Issue by liamkennedy89** [MicrosoftDocs/Virtualization-Documentation#787]
Please just enable hyper v for Home users. I don't want to fork out £120 just to get Docker working properly on your platform
Thanks

Liam

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 223b9ea7-e2c0-4c6b-6d55-9125274d26ce
* Version Independent ID: 85c7005e-33b2-ae0b-a919-f056d14cf0ac
* Content: [Introduction to Hyper-V on Windows 10](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/about/)
* Content Source: [virtualization/hyper-v-on-windows/about/index.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/hyper-v-on-windows/about/index.md)
* Product: **windows-10-hyperv**
* GitHub Login: @scooley

**Comment by scooley** [comment]
Closing since this isn't a doc bug but here is a [link](https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/17284472-enable-hyper-v-on-all-version-of-windows) to upvote on UserVoice

**Comment by QUIPQUOPRO** [comment]
You could at least explain why home licenses are excluded.
