### ISSUE TITLE
there is no mention of windows 10 1803 and whether it supports docker containers

### ISSUE THREAD

**Issue by ctgarvey** [MicrosoftDocs/Virtualization-Documentation#797]
please update the docs. can i run docker windows containers on win 10 enterprise 1803 yes or no

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66894009-bd4f-3fa6-6e03-a8485686bea5
* Version Independent ID: 9d081837-7987-eeb5-1abf-37ebc2e3c7f6
* Content: [Windows Container on Windows 10](https://docs.microsoft.com/en-gb/virtualization/windowscontainers/quick-start/quick-start-windows-10#feedback)
* Content Source: [virtualization/windowscontainers/quick-start/quick-start-windows-10.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/quick-start/quick-start-windows-10.md)
* Service: **windows-containers**
* Product: **windows-containers**
* GitHub Login: @enderb-ms

**Comment by maxwellb** [comment]
The relevant text from this article is

> Make sure you have 14393.222 or later before continuing

Windows build 14393.2430 corresponds with Windows 10 version 1607. Windows 10 version 1803 is a later version, so it is supported.
