### ISSUE TITLE
A step is missing

### ISSUE THREAD

**Issue by royeectu** [MicrosoftDocs/Virtualization-Documentation#798]
When you install Docker on Windows, it is set to run Linux containers on Windows (LCOW).
In order to run the .Net hello example mentioned above, first you should switch to Windows containers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44a44120-01fd-11ca-9d51-21ac35609f11
* Version Independent ID: 75a53123-64be-1caf-fd67-7e7bef3b0aa0
* Content: [Windows Containers on Windows Server](https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-server)
* Content Source: [virtualization/windowscontainers/quick-start/quick-start-windows-server.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/quick-start/quick-start-windows-server.md)
* Service: **windows-containers**
* Product: **windows-containers**
* GitHub Login: @enderb-ms

**Comment by rleigh-codelibre** [comment]
Is this still the case?  I just followed the instructions on a vanilla Server 2016 CLI-only install, and it was using Windows containers by default.  This wasn't true on Windows 10 though, where you needed to explicitly switch over.

**Comment by royeectu** [comment]
I had this issue with Windows 10

**Comment by NatMarchand** [comment]
For Windows 10, the documentation is on a different page (and is accurate).
See https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-10
