### ISSUE TITLE
Command does not work on Ubunto 18.04

### ISSUE THREAD

**Issue by stgraves** [MicrosoftDocs/Virtualization-Documentation#800]
sudo apt-get install curl git build-essential docker.io conntrack python2.7
"Unable to locate package docker.io"
"Couldn't find any package by glob 'docker.io'"
"Couldn't find any package by regex 'docker.io'"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2e01fc9-32d1-7154-c3c0-0ab3981f01ff
* Version Independent ID: d05ec2d5-d4dc-477b-05b5-6316af7fe1ff
* Content: [Kubernetes Master From Scratch](https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/creating-a-linux-master)
* Content Source: [virtualization/windowscontainers/kubernetes/creating-a-linux-master.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/kubernetes/creating-a-linux-master.md)
* Product: **containers**
* GitHub Login: @gkudra-msft
* Microsoft Alias: **gekudray**

**Comment by stgraves** [comment]
I was able to get around this issue by installing all the updates for Ubuntu 18.04, which the article mentions should be done but doesn't provide any steps.

The article makes assumptions the person following the steps knows how to use Ubuntu. But it would be a good idea to include the commands to install all the updates for those that are not familiar with Ubuntu.

**Comment by TomicaKaniski** [comment]
- ifconfig will show a new interface cbr0 with the chosen cluster CIDR.
For me, interface is called docker0, not cbr0 (Ubuntu 18.04).

**Comment by TomicaKaniski** [comment]
- Under docker ps, there will be ~23 worker and pod containers.
This should be run with sudo (otherwise you'll get permission denied).

**Comment by daschott** [comment]
@stgraves yes, we are actively updating this documentation and hope to have this out soon in September. I added update instructions there.

@TomicaKaniski docker0 is the docker network, separate from Kubernetes. Depending on Kubernetes distribution the `cbr0` network could be called `cni0`. If there is no cbr0 network created something probably went wrong. Feel free to use [this guide](https://1drv.ms/w/s!AgH65RVQdrbiglNr7P7P4VrO8Rxr) until we update this documentation.

**Comment by rockfordlhotka** [comment]
I am encountering the same issue as the OP. I installed a fresh Ubuntu 18.04 server (64 bit), did an `apt-get update` and `apt-get upgrade -y`. Then I tried `apt-get install docker.io` with the same result as OP.

Is there a workaround or known way to get docker installed on Ubuntu server 18.04?

**Comment by daschott** [comment]
@rockfordlhotka can you use the following:
https://docs.docker.com/install/linux/docker-ce/ubuntu/

**Comment by gszecsenyi** [comment]
For me only a `sudo apt-get update` was missing.

**Comment by daschott** [comment]
This issue can be avoided by updating your Linux master machine. This is added in the instructions here: https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/creating-a-linux-master#initialization-using-kubeadm thank you!
