### ISSUE TITLE
Add Supportability content for Transparent Networks on Azure VM

### ISSUE THREAD

**Issue by stgraves** [MicrosoftDocs/Virtualization-Documentation#802]
We are seeing a lot of customers using this documentation when using Containers on Azure VMs. It would be good idea to add a note to the transparent network description stating that MAC Address Spoofing is not supported on Azure VMs.

transparent – containers attached to a network created with the 'transparent' driver will be directly connected to the physical network through an external Hyper-V switch. IPs from the physical network can be assigned statically (requires user-specified --subnet option) or dynamically using an external DHCP server. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 556473c3-3630-dc56-caad-a3d72d34e9e1
* Version Independent ID: 560ad6ca-e017-db71-4605-a73e9f1b8aed
* Content: [Windows Container Networking](https://docs.microsoft.com/en-us/virtualization/windowscontainers/container-networking/network-drivers-topologies)
* Content Source: [virtualization/windowscontainers/container-networking/network-drivers-topologies.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/container-networking/network-drivers-topologies.md)
* Service: **windows-containers**
* Product: **windows-containers**
* GitHub Login: @JMesser81

**Comment by RHaest** [comment]
Hi, I totally agree with you. One question that comes up immediately and would be a nice addition: is there a workaround to achieve the same result (multiple containers on multiple IP's accessible externally) for transparent networks with Azure VM's? Thanks!
