### ISSUE TITLE
Looks like that pull request is merged

### ISSUE THREAD

**Issue by ACoderLife** [MicrosoftDocs/Virtualization-Documentation#820]
You have the following in this doc:
Note: This behavior is changing on Windows 10, Creators Update as the platform now supports "hot-add". This capability will light-up E2E after this outstanding Docker pull request is merged

Looks closed:
https://github.com/docker/libnetwork/pull/1661

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac23c73f-8e2c-f108-ab8c-e002a40f00cf
* Version Independent ID: 72b179c0-35a6-fcc0-10ae-7764fb8edb19
* Content: [Windows Container Networking](https://docs.microsoft.com/en-us/virtualization/windowscontainers/container-networking/advanced)
* Content Source: [virtualization/windowscontainers/container-networking/advanced.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/container-networking/advanced.md)
* Service: **windows-containers**
* Product: **windows-containers**
* GitHub Login: @JMesser81

**Comment by daschott** [comment]
Yes, thank you
