### ISSUE TITLE
Waitng Routing mesh coming soon so long time

### ISSUE THREAD

**Issue by kkbruce** [MicrosoftDocs/Virtualization-Documentation#824]
We waiting this "coming soon" so long time.
「Currently, DNS Round-Robin is the only load balancing strategy supported on Windows.Routing mesh for Windows docker hosts is not yet supported, but will be coming soon.」

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16eeefcb-95dc-952a-18b9-2c00d190a995
* Version Independent ID: 5becd139-9e1d-4e41-04a4-9c96cf8f9f72
* Content: [Getting Started with Swarm Mode](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/swarm-mode)
* Content Source: [virtualization/windowscontainers/manage-containers/swarm-mode.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/manage-containers/swarm-mode.md)
* Service: **windows-containers**
* Product: **windows-containers**
* GitHub Login: @kallie-b

**Comment by carlfischer1** [comment]
Routing mesh and VIP service discovery are supported in Docker engine EE 18.03.1. https://github.com/docker/docker.github.io/pull/7176 clarifies the release notes

**Comment by kkbruce** [comment]
@carlfischer1 Thanks.

**Comment by sowsan** [comment]
It would be great if we can update the same on the documentation for this issue originally reported. Doc is not calling out this fix and docker version.  Also 3 part training series calling out the same issue which is kind of outdated. Would be great to see to a nginx integration as well with this.

**Comment by foulong** [comment]
Hello,

is it planned soon to docker CE ? Indeed docker toolbox ?
