### ISSUE TITLE
Is this blog outdated with respect to windows server 1803?

### ISSUE THREAD

**Issue by amolsh** [MicrosoftDocs/Virtualization-Documentation#825]
Does this blog works with windows 1803? I think blog should be updated with latest changes. I was following this blog with 1803, it is not working as aspected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89f7c443-179d-e46a-7ea7-07271e4c775b
* Version Independent ID: da220df4-81c1-3557-354e-7a8f1d2ef029
* Content: [Kubernetes on Windows](https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/getting-started-kubernetes-windows)
* Content Source: [virtualization/windowscontainers/kubernetes/getting-started-kubernetes-windows.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/kubernetes/getting-started-kubernetes-windows.md)
* Product: **containers**
* GitHub Login: @gkudra-msft
* Microsoft Alias: **gekudray**

**Comment by daschott** [comment]
@amolsh we will update this documentation in September. In the meanwhile, please use [this guide](https://1drv.ms/w/s!AgH65RVQdrbiglNr7P7P4VrO8Rxr) for deploying Kubernetes on Windows.

**Comment by mgroux520** [comment]
Link 'this guide' broken :/  And some updated documentation is sorely needed at this point...

**Comment by daschott** [comment]
@mgroux520 are you saying you cannot access the guide through the provided link? A number of people have used it successfully and I just checked that it's still accessible. Can you check again?

**Comment by mgroux520** [comment]
Looks like a Corp rule issue - was able to access via home pc.  Appreciate the follow-up, and will be reviewing asap.
