### ISSUE TITLE
Docker Hub page (windowsservercore) missing 1803

### ISSUE THREAD

**Issue by jmajoor** [MicrosoftDocs/Virtualization-Documentation#835]
Not sure this is the right place, but there isn't a link to provide feedback on the docker hub page.
As of this moment the docker hub page does not mention Server 1803. It does have 1803 ready for a docker pull, but it makes no mention of it. The page also doesn't have a short description.
Docker Hub: https://hub.docker.com/r/microsoft/windowsservercore/

**Comment by cwilhit** [comment]
Thank you for catching this. I will update the repository readme.

**Comment by cwilhit** [comment]
Readmes have been updated.
