### ISSUE TITLE
How to adjust disk size in container?

### ISSUE THREAD

**Issue by MSLaojun** [MicrosoftDocs/Virtualization-Documentation#837]
In my first practice, the disk of C: has a nearly 20GB volume. It is actually not the size of any disk on my host, and I don't know how to config it.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9682caf3-5fc4-54e6-d841-8cb6c16bbc4f
* Version Independent ID: 6c99e2e3-eafe-a91e-9c26-8d5845cc0b7f
* Content: [Windows Container Requirements](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/system-requirements)
* Content Source: [virtualization/windowscontainers/deploy-containers/system-requirements.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/deploy-containers/system-requirements.md)
* Product: **windows-containers**
* GitHub Login: @enderb-ms

**Comment by taylorb-microsoft** [comment]
Take a look at https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-storage#image-size

_sorry for the delayed reply_
