### ISSUE TITLE
DNS resolving issue

### ISSUE THREAD

**Issue by calebpalmer** [MicrosoftDocs/Virtualization-Documentation#855]
In reference to "Pods stop resolving DNS queries successfully after some time alive", it is stated that "it is being fast-tracked through Windows servicing.".  What does this mean?  I'm running into this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d162332-10db-b9f2-92cc-19475ca448ed
* Version Independent ID: 82e7e978-51d0-e563-87bf-e0c82c2bb04a
* Content: [Troubleshooting Kubernetes](https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/common-problems#pods-stop-resolving-dns-queries-successfully-after-some-time-alive)
* Content Source: [virtualization/windowscontainers/kubernetes/common-problems.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/kubernetes/common-problems.md)
* Product: **containers**
* GitHub Login: @gkudra-msft
* Microsoft Alias: **gekudray**

**Comment by BowlingX** [comment]
In my case I was using windows server 2019 and I had to adjust the Dockerfile to use the `1809` tag. Otherwise creating pods would throw `The container operating system does not match the host operating system. kubernetes windows` errors.

**Comment by daschott** [comment]
Which Windows version is being used? This shouldn't be an issue after WS1803.
