### ISSUE TITLE
Update for Windows Server 2019

### ISSUE THREAD

**Issue by shahiddev** [MicrosoftDocs/Virtualization-Documentation#863]
This guide is almost exactly the same except for the name of the sample image.
To run the correct sample you need to use the command:
docker run microsoft/dotnet-samples:dotnetapp-nanoserver-1809

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44a44120-01fd-11ca-9d51-21ac35609f11
* Version Independent ID: 75a53123-64be-1caf-fd67-7e7bef3b0aa0
* Content: [Windows Containers on Windows Server](https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-server)
* Content Source: [virtualization/windowscontainers/quick-start/quick-start-windows-server.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/quick-start/quick-start-windows-server.md)
* Service: **windows-containers**
* Product: **windows-containers**
* GitHub Login: @enderb-ms

**Comment by jocooler** [comment]
It's nice to support 2019, but knowing what the 2016 instructions are is also still useful for those of us who are working on this with current VMs. 

The error I got was: `a windows version 10.0.xxxxx-based image is incompatible with a 10.0.xxxxx host.`

I think it's just `microsoft/dotnet-samples:dotnetapp-nanoserver` for Windows 2016 deploy.
