### ISSUE TITLE
Hyper-V host?

### ISSUE THREAD

**Issue by pmahend1** [MicrosoftDocs/Virtualization-Documentation#870]
What is meant by "Hyper-V Requirements: A hypervisor has been detected. Features required for Hyper-V are not be displayed." Does it mean Hyper-V is still enabled and working. 
I have this message. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 604d834f-6f94-0a37-12b6-a10dcf7c9fa3
* Version Independent ID: 4bd4ce05-bdde-f450-ee68-9fcd2cbca48e
* Content: [Windows 10 Hyper-V System Requirements](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/reference/hyper-v-requirements)
* Content Source: [virtualization/hyper-v-on-windows/reference/hyper-v-requirements.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/hyper-v-on-windows/reference/hyper-v-requirements.md)
* Service: **windows-10-hyperv**
* Product: **windows-10-hyperv**
* GitHub Login: @scooley

**Comment by bjd2385** [comment]
I am curious as well. I have the same message.

**Comment by pmahend1** [comment]
It turned out my system dint support `Hyper-V` , I had to search a lot in in the haystack for this. 
The message it shows is misleading. We need to have some hyper-v tools on the device; if the PC is compatible it downloads that when we turn on this feature. Apperently docs havent mentioned it clearly I suppose. Only when we have 

![image](https://user-images.githubusercontent.com/21352870/50646764-e6730080-0f44-11e9-8d5e-5e5cfd8b7203.png)


In the right it doesnt show Hyper-V tools , and thats the hint that my machine wont support this

**Comment by pmahend1** [comment]
@scooley or someone else at Microsoft take care of this. Its unassigned after 2 months still.

**Comment by armujahid** [comment]
This message is really ambiguous

**Comment by artemious7** [comment]
the message is unclear. what is that supposed to mean?!

**Comment by pronichkin** [comment]
It is supposed to mean exactly what it says. A hyperviosr has been detected, based on the information provided by [CPU ID function. ](https://en.wikipedia.org/wiki/CPUID)This most commonly means that you're running inside a virtual machine. It's typically not possible to provide more details—e.g. to know for sure what hyperviosr it is, how it's configured, etc. Hence the message is intentionally vague.

If you believe there should be no hypervisor, i.e. you're running on a bare metal PC, then chances are there's some bug or misconfiguration. This can be troubleshoot on case by case basis, but more info would be needed. Anyhow, this would not be a documentation issue. A recommended approach is to open a support case.

**Comment by pmahend1** [comment]
Submitted PR #1311 with clearer documentation and screenshot. Hope it gets approved

**Comment by pmahend1** [comment]
#1311 merged . Changes are available
