### ISSUE TITLE
Step 1: Broken Download Link

### ISSUE THREAD

**Issue by huzzeytech** [MicrosoftDocs/Virtualization-Documentation#871]
https://download.docker.com/win/stable/InstallDocker.msi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66894009-bd4f-3fa6-6e03-a8485686bea5
* Version Independent ID: 9d081837-7987-eeb5-1abf-37ebc2e3c7f6
* Content: [Windows Container on Windows 10](https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-10)
* Content Source: [virtualization/windowscontainers/quick-start/quick-start-windows-10.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/quick-start/quick-start-windows-10.md)
* Service: **windows-containers**
* Product: **windows-containers**
* GitHub Login: @enderb-ms

**Comment by huzzeytech** [comment]
Looks like a downloads require sign in now :eyeroll:

**Comment by huzzeytech** [comment]
https://store.docker.com/editions/community/docker-ce-desktop-windows

**Comment by Mera-Gangapersaud** [comment]
Yep you need to sign in to be able to download docker.

**Comment by scooley** [comment]
Thanks folks, I'll pass that feedback back to Docker.
