### ISSUE TITLE
Confused by untrusted package source

### ISSUE THREAD

**Issue by jagarrison** [MicrosoftDocs/Virtualization-Documentation#885]
So Microsoft's method for preparing Windows to run containers is to add a third party repository to pull software from and then to install software that is not trusted? I'm very confused by this and a little irritated as well. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03053de3-22f9-2320-42c4-4bfdcec11840
* Version Independent ID: 70f19263-9c17-61a6-03eb-af0cf33ca932
* Content: [Deploy Windows Containers on Windows Server](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/deploy-containers-on-server)
* Content Source: [virtualization/windowscontainers/deploy-containers/deploy-containers-on-server.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/deploy-containers/deploy-containers-on-server.md)
* Service: **windows-containers**
* Product: **windows-containers**
* GitHub Login: @enderb-ms

**Comment by scooley** [comment]
Can you share more details about your concern?  mcr is the microsoft container registry.

**Comment by jagarrison** [comment]
Just stepped through this again and again was prompted that I'm installing from an untrusted source. This is fine, I've made up my mind to focus on Linux for containers and leave all Windows dependent apps on VMs while I find suitable alternatives.
