### ISSUE TITLE
Getting join cluster information from cli

### ISSUE THREAD

**Issue by kiljoy001** [MicrosoftDocs/Virtualization-Documentation#916]
this can be done with the following command: 
 sudo kubeadm token create --print-join-command

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2e01fc9-32d1-7154-c3c0-0ab3981f01ff
* Version Independent ID: d05ec2d5-d4dc-477b-05b5-6316af7fe1ff
* Content: [Kubernetes Master From Scratch](https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/creating-a-linux-master)
* Content Source: [virtualization/windowscontainers/kubernetes/creating-a-linux-master.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/kubernetes/creating-a-linux-master.md)
* Product: **containers**
* GitHub Login: @daschott
* Microsoft Alias: **daschott**

**Comment by daschott** [comment]
Added, thank you!
