### ISSUE TITLE
Server 2019 Guest

### ISSUE THREAD

**Issue by pmwestervelt** [MicrosoftDocs/Virtualization-Documentation#927]
Can Server 2019 be added as a supported guest OS on a Windows 10 Hyper-V Client system? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86bb1ed3-7346-acf7-2a7f-414bb6c09a4d
* Version Independent ID: b3bfcc86-a15c-a951-a6d2-b1446d0f6efa
* Content: [Supported Windows guests](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/about/supported-guest-os#feedback)
* Content Source: [virtualization/hyper-v-on-windows/about/supported-guest-os.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/hyper-v-on-windows/about/supported-guest-os.md)
* Product: **windows-10-hyperv**
* GitHub Login: @scooley

**Comment by scooley** [comment]
Fixed :)
