### ISSUE TITLE
How one specifies those parameters during `build` phase and not `run` of container

### ISSUE THREAD

**Issue by artisticcheese** [MicrosoftDocs/Virtualization-Documentation#928]
Currently seems containers being built on Hyper-V isolation are limited to 2 vCPUs with not supported way to control number of vCPUs available during build stage. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd671d15-cd2f-d3a0-298a-83b3b5375589
* Version Independent ID: bff76cf7-b868-e30c-bc1a-fa6e4d06a11f
* Content: [Implementing resource controls](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/resource-controls)
* Content Source: [virtualization/windowscontainers/manage-containers/resource-controls.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/manage-containers/resource-controls.md)
* Service: **windows-containers**
* Product: **windows-containers**
* GitHub Login: @taylorb-microsoft

**Comment by taylorb-microsoft** [comment]
Currently there isn't "docker build" does accept --cpu-period/quota/shares but seems we/others missed plumbing in --cpu-count/percent.

I have created an issue at on the Moby project to track/request these be added: https://github.com/moby/moby/issues/38387
