### ISSUE TITLE
MKDIR example

### ISSUE THREAD

**Issue by ta32** [MicrosoftDocs/Virtualization-Documentation#929]
What about the mkdir example - when we use forward slashes 
Step 9/20 : RUN MKDIR "Server/Configuration"
 ---&gt; Running in 69684d9c7847
'onfiguration"' is not recognized as an internal or external command,
operable program or batch file.

I dont want to switch between using forward slashes for copy statements and back slashes for mkdir

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af1a6bea-cfcc-f9d3-25ee-f95f567378cf
* Version Independent ID: 91a0dfac-9427-6999-e7b5-a1005a04395e
* Content: [Dockerfile and Windows Containers](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/manage-windows-dockerfile)
* Content Source: [virtualization/windowscontainers/manage-docker/manage-windows-dockerfile.md](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/manage-docker/manage-windows-dockerfile.md)
* Service: **windows-containers**
* Product: **windows-containers**
* GitHub Login: @PatrickLang

**Comment by ezzkht** [comment]
You can change the escape character and use backslashes in your paths.
