### ISSUE TITLE
Problem with start.ps1

### ISSUE THREAD

**Issue by tjackprime** [MicrosoftDocs/Virtualization-Documentation#944]
When running the start.ps1 script, it appears that flanneld fails to start up.  I get this error spew...

I1224 19:01:06.246467    1088 main.go:450] Searching for interface using 10.142.0.3
I1224 19:01:06.389548    1088 main.go:527] Using interface with name vEthernet (Ethernet) and address 10.142.0.3
I1224 19:01:06.389548    1088 main.go:544] Defaulting external address to interface address (10.142.0.3)
I1224 19:01:06.397327    1088 kube.go:126] Waiting 10m0s for node controller to sync
I1224 19:01:06.397327    1088 kube.go:309] Starting kube subnet manager
I1224 19:01:07.399204    1088 kube.go:133] Node controller sync successful
I1224 19:01:07.399459    1088 main.go:244] Created subnet manager: Kubernetes Subnet Manager - windows-worker-instance-1
I1224 19:01:07.402113    1088 main.go:247] Installing signal handlers
I1224 19:01:07.403099    1088 main.go:386] Found network config - Backend type: host-gw
I1224 19:01:07.404067    1088 hostgw_windows.go:73] HOST-GW config: {Name:cbr0 DNSServerList:}
I1224 19:01:07.423619    1088 hostgw_windows.go:157] Attempting to create HNSNetwork {"Name":"cbr0","Type":"L2Bridge","Subnets":[{"AddressPrefix":"10.244.1.0/24","GatewayAddress":"10.244.1.1"}]}
I1224 19:01:07.431408    1088 hostgw_windows.go:164] Waiting to get ManagementIP from HNSNetwork cbr0
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x10e43ea]

goroutine 1 [running]:
main.main()
        /home/kasubra/repo/gopath/src/github.com/coreos/flannel/main.go:297 +0xbfa

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 206db1f3-8451-0171-e103-fea3ab7b3f72
* Version Independent ID: 87d7ab1c-1617-44a9-a77c-bf0443109e35
* Content: [Joining Windows nodes](https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/joining-windows-workers)
* Content Source: [virtualization/windowscontainers/kubernetes/joining-windows-workers.md](https://github.com/Microsoft/Virtualization-Documentation/blob/master/virtualization/windowscontainers/kubernetes/joining-windows-workers.md)
* Product: **containers**
* GitHub Login: @daschott
* Microsoft Alias: **daschott**

**Comment by daschott** [comment]
@ksubrmnn FYI

**Comment by daschott** [comment]
@tjackprime can you use flannel version v1.11 ?

**Comment by daschott** [comment]
This issue is resolved with flannel v0.11. Please re-open this issue if you are still seeing problems.
