### ISSUE TITLE
Docker not work in Windows Hyper V 2019

### ISSUE THREAD

**Issue by viniciusxyz** [MicrosoftDocs/Virtualization-Documentation#945]
Good afternoon everyone,

I am using Windows Server Hyper V 2019 and I am not able to install docker as I did in Hyper V 2016.

I tried installing version 18.09.0, 18.03.1-ee-5 and 17.06.2-ee-16 Docker EE windows

System:
Windows Server Hyper V 2019 build 17763

When you try to run the net start docker command the 1067 error is returned.

When attempting to run dockerd.exe the following error is returned:
 Error starting daemon: failed to load vmcompute.dll, ensure that the containers feature is installed

Apparently Windows Server Hyper V 2019 does not have the Feature container, will this be added later, or should we declare the Windows Server Hyper V 2019 version as a compatible version with docker containers?

Att

Now we can start the docker, following the steps described by @andrewleech , but when trying to start any container an error message is returned, it follows:

C: \ Program Files \ Docker \ docker.exe: Error response from daemon: container 32903a90a5cc2e7d38960c3f71495cde5cc89971ed5b529ae2ebf00106267a00 encountered an error during CreateContainer: failure in a Windows system call: The request is not supported. (0x32) Extra info: {"SystemType": "Container", "Name": "32903a90a5cc2e7d38960c3f71495cde5cc89971ed5b529ae2ebf00106267a00", "Owner": "docker", "IsDummy": false, "VolumePath": "\\? \ Volume {e701a246- "C: \ ProgramData \ docker \ windowsfilter \ 32903a90a5cc2e7d38960c3f71495cde5cc89971ed5b529ae2ebf00106267a00", "Layers": [{"ID": "285eb07a-0fde-510e-55ff-4bbb-aa2c-6d8f84c8f69f}", "IgnoreFlushesDuringBoot" "C: \ ProgramData \ docker \ windowsfilter \ 0fbad36ee403deabb2ea647688f5a5bba7d8a7520f2b4c3d10b9940e4d6139f5"}, {"ID": "b6002d83-1209-5d03-ac03-c51522e7f54c", "Path": "C: \ ProgramData \ , "HostName": "32903a90a5cc", "MappedDirectories": [], "HvPartition": false, "EndpointList": ["D4700D2F-12EA-42F2-A264-1CF8BF7A5AF3"], "Servicing ": false," AllowUnqualifiedDNSQuery ": true}.

 - Docker Version
Client:
 Version: 18.09.1
 API version: 1.39
 Go version: go1.10.6
 Git commit: 20b67756d0
 Built: unknown-buildtime
 OS / Arch: windows / amd64
 Experimental: false

Server:
 Engine:
  Version: 18.09.1
  API version: 1.39 (minimum version 1.24)
  Go version: go1.10.6
  Git commit: 20b67756d0
  Built: 09/01/2019 17:09:57
  OS / Arch: windows / amd64
  Experimental: false

 - Docker Info
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 3
Server Version: 18.09.1
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
Operating System: Hyper-V Server 2019 Version 1809 (OS Build 17763.1)
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 4GiB
Name: WIN-908B729AIV4
ID: WVTS: DEHC: UP7O: TXED: KBTO: Q52P: MEBL: 6IB2: 2RNV: 472G: 7H76: XV6P
Docker Root Dir: C: \ ProgramData \ docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

### Install docker
 - Install Docker:
 - Install-Module DockerMsftProvider -Force
 - Install-Package Docker -ProviderName DockerMsftProvider -Force

### Install the required Features
 - Enable features required (HNS Service)
 - Enable-WindowsOptionalFeature -Online -FeatureName HypervisorPlatform
 - Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform
### Will reboot
 - Set-Service -Name hns -StartupType Automatic
 - Set-Service -Name docker -StartupType Automatic
 - cmd / c "sc config docker depend = hns"
 - Start-Service docker

### Try to run any container:
 - docker run -ti mcr.microsoft.com/windows/servercore powershell

**Comment by viniciusxyz** [comment]
I tried to perform the installation on a Windows Server 2019 Essentials and got the same problem.

**Comment by viniciusxyz** [comment]
I tried on Docker 17.06.2-ee-16 and get this error:

C:\Program Files\Docker\docker.exe: Error response from daemon: container 32903a90a5cc2e7d38960c3f71495cde5cc89971ed5b529ae2ebf00106267a00 encountered an error during CreateContainer: failure in a Windows system call: The request is not supported. (0x32) extra info: {"SystemType":"Container","Name":"32903a90a5cc2e7d38960c3f71495cde5cc89971ed5b529ae2ebf00106267a00","Owner":"docker","IsDummy":false,"VolumePath":"\\\\?\\Volume{e701a246-55ff-4bbb-aa2c-6d8f84c8f69f}","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\32903a90a5cc2e7d38960c3f71495cde5cc89971ed5b529ae2ebf00106267a00","Layers":[{"ID":"284eb07a-0fde-510e-a81b-50c702d48976","Path":"C:\\ProgramData\\docker\\windowsfilter\\0fbad36ee403deabb2ea647688f5a5bba7d8a7520f2b4c3d10b9940e4d6139f5"},{"ID":"b6002d83-1209-5d03-ac03-c51522e7f54c","Path":"C:\\ProgramData\\docker\\windowsfilter\\32233b4ea9318e4c89155316e5ee17348d2caacb2662142fe047802d2fab012d"}],"HostName":"32903a90a5cc","MappedDirectories":[],"HvPartition":false,"EndpointList":["D4700D2F-12EA-42F2-A264-1CF8BF7A5AF3"],"Servicing":false,"AllowUnqualifiedDNSQuery":true}.

**Comment by viniciusxyz** [comment]
I ran out of ideas on how to work around the problem.
I think we'll need the help of someone closer to the core of docker windows.
@StefanScherer sorry mark you here, but I feel that this discussion is important and I always follow your work and I know you are an authorized figure in the subject, I would like your opinion on this problem, if it is not for your area, pardon me.

**Comment by viniciusxyz** [comment]
I just tested with Windows Server Standard Evaluation, when I run the command docker run -ti mcr.microsoft.com/windows/nanoserver cmd or docker run -ti mcr.microsoft.com/windows/nanoserver powershell the below error is displayed:

C: \ Program Files \ Docker \ docker.exe: Error response from daemon: CreateComputeSystem 1fb7a0f964f35092a7650bbf560375686db62951ae906eb37682ec038eab3bcd: The operating system container does not match the host operating system.
("SystemType": "Container", "Name": "1fb7a0f964f35092a7650bbf560375686db62951ae906eb37682ec038eab3bcd", "Owner": "docker", "VolumePath": "\\\\? \\ Volume {68e3229d-6925-47b4-9ee1 -229b9c928749} "," IgnoreFlushesDuringBoot ": true," LayerFolderPath ":" C: \\ ProgramData \\ docker \\ windowsfilter \\ 1fb7a0f964f35092a7650bbf560375686db62951ae906eb37682ec038eab3bcd "," Layers ": [{" ID ":" ffdbdb92-86dd-5534-a88c -748ec30af638 "," Path ":" C: \ ProgramData \\ docker \\ windowsfilter \\ cad7031fe21f7a3fb8a8bd84a84f427a4ef00bb1ec07633ffa835948e7277ee8 "}, {" ID ":" f0d8441d-9aef-59b6-8d54-d8683d3b5ef7 "," Path ":" C: \\ ProgramData \\ dock \\ windowsfilter \\ a17aa49822df1a45c2f9720b0f788252257b7bec90f67609d3ffb57169c17b77 "}]," HostName ":" 1fb7a0f964f3 "," HvPartition ": false," EndpointList ": [" FF8F91B8-275C-432E-AC00-0F50821DFF58 "]," AllowUnqualifiedDNSQuery ": true}).

### Docker info
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 2
Server Version: 18.09.1
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
Operating System: Windows Server 2019 Standard Evaluation Version 1809 (OS Build 17763.253)
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 4GiB
Name: WIN-R76R0A6EDBE
ID: AZE2: OUXK: OCQJ: AXH5: M4KX: CGKE: N7YJ: ACEW: NPUS: D3SW: 5J6Y: XO6H
Docker Root Dir: C: \ ProgramData \ docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by cwilhit** [comment]
@viniciusxyz Hyper-V Server 2019 is a free product that contains the Windows hypervisor, a Windows Server driver model, and core virtualization components. If you would like to run containers, we recommend upgrading to one of our Windows Server products to leverage that feature.

Regarding your latest comment where you're running Windows Server Eval, you need to make sure the container image tag matches your host version. If this is WS2019 Eval, then that would be:

`docker run -ti mcr.microsoft.com/windows/nanoserver:1809`

@andrewleech Are you running Windows Server 2019 on the metal or in a VM? Hyper-V isolation for containers should not be broken.

**Comment by andrewleech** [comment]
Hi @cwilhit, I am running 1809 in a separate vm, on a KVM system with nested virtualisation enabled.
Hyperv server 2016 works perfectly well in a separate vm alongside it.

**Comment by cwilhit** [comment]
Ah, therein lies the issue. We do not support running Hyper-V on top of KVM--you may be able to get it partially working, but it can lead to undefined behavior. Just want to be clear that this is a configuration that we do not support.

**Comment by viniciusxyz** [comment]
What are the versions that actually contain containers? I will test the execution by explicit tag 1809 to see what happens

**Comment by cwilhit** [comment]
All versions of Windows Server since Windows Server 2016 are capable of running containers. You can find the full tag-listing for containers on [Docker Hub](https://hub.docker.com/_/microsoft-windows-nanoserver)

**Comment by StefanScherer** [comment]
@viniciusxyz I'm already watching this repo and especially this thread ;-)

I tried it running the Windows Server Datacenter 2019 Eval in VMware Fusion and it works with both process and hyperv isolation. I haven't tried the 2019 Hyper-V ISO.

**Comment by andrewleech** [comment]
Looking into my copy of Windows Server Datacenter 2019 Eval further, I didn't realise it installs with the hyper-v feature disabled. Enabling that has fixed the hyperv isolation for me too.

**Comment by viniciusxyz** [comment]
It's a shame that there is no support for Hyper V Server 2019, I figured as a virtualization platform this functionality would also be deployed, I'll test again with Windows Server 2019 Standart using the correct images and warning me if hyper v is active. Can you tell me if containers are also supported on Windows server 2019 essentials? I ask this question because it is separate from the other versions in the installation and this version probably has fewer features. Would be nice if there was a place with all this information with easier access (if there is already can please inform me because I did not find it?)

**Comment by viniciusxyz** [comment]
Testing with Standard and everything happened as expected when using the 1809 tag, I did not know that there was a breach of compatibility with previous versions, I also tested with Essentials and I came to the conclusion that it does not really work in this version, I will continue closing the issue, but again containers in Hyper V Server 2019 would be warmly welcomed.

**Comment by cwilhit** [comment]
> but again containers in Hyper V Server 2019 would be warmly welcomed.

Appreciate the feedback--thanks!

**Comment by db4** [comment]
> Ah, therein lies the issue. We do not support running Hyper-V on top of KVM--you may be able to get it partially working, but it can lead to undefined behavior. Just want to be clear that this is a configuration that we do not support.

@cwilhit Can you clarify again, is Hyper-V Server 2019 expected to be capable to run containers or this feature has been lost completely since Hyper-V Server 2016? Unlike @andrewleech  I'm trying to run Hyper-V Server 2019 on the bare metal but `docker` fails just the same way (both `isolation=process` and `isolation=hyperv`)

**Comment by cwilhit** [comment]
> @viniciusxyz Hyper-V Server 2019 is a free product that contains the Windows hypervisor, a Windows Server driver model, and core virtualization components. If you would like to run containers, we recommend upgrading to one of our Windows Server products to leverage that feature.

@db4, see above. Hyper-V Server 2019 **does not** support running containers.

**Comment by cwilhit** [comment]
No, it's not a bug.

**Comment by soumen1102** [comment]
Have been working with Windows Container using nano server images and we find the running behavior very unstable at times taking the machine down and causing other server stability issues . So does that mean that With Windows Server 2019 Hyper V enabled VM running on VMWare Windows Container are not supported. Are there any plans to support this in near future through a patch or an upgrade.

**Comment by dhirschfeld** [comment]
IIUC nested virtualization with Hyper-V running under VMWare is problematic. At a minimum you need to enable MAC address spoofing on the virtual switch, probably also promiscuous mode and maybe forged transmits. Haven't tried the fixes so YMMV. 

* https://www.virtualizationhowto.com/2018/07/vmware-vs-hyper-v-nested-virtualization/
* https://www.virtuallyghetto.com/2018/04/native-mac-learning-in-vsphere-6-7-removes-the-need-for-promiscuous-mode-for-nested-esxi.html

**Comment by soumen1102** [comment]
Thanks @dhirschfeld will try this out and let you know . @cwilhit any plans to get this working in near future..

**Comment by pchettri3** [comment]
what about licensed or eval windows 2019. Container is not working on fully installed windows 2019 server.
cwilhit reponses are stuck with presumption of free hypervisor which is not the case for most of us

**Comment by yamac-kurtulus** [comment]
@cwilhit I don't understand one thing. If I am running 2 WS19 VMs on Hyper-V Host with WS19, will I not be able to use docker on either of them with Hyper-V isolation? Swarm also has some problems in such set up i think, am i right?

**Comment by cwilhit** [comment]
> . If I am running 2 WS19 VMs on Hyper-V Host with WS19 (All licensed), will I not be able to use docker on either of them with Hyper-V isolation? 

You can certainly run Windows containers via Docker in such a setup. Running them as process-isolated containers will just work, and if you want to run them as Hyper-V isolated containers, then you need to [enable nested virtualization](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/nested-virtualization), assuming you're running on Intel hardware. AMD nested virtualization is not supported.

**Comment by yamac-kurtulus** [comment]
@cwilhit  Thank you for the answer. In theory this seems reasonable. However we cannot get Swarm to working with vip mode on these mentioned servers. Should we have extensive networking setup on docker for it to work? I was unable to find any info on this, many people seemed to have got it working outside Hyper-v so we thought it is a problem with Hyper-v, am I correct or are you aware of a networking problem on virtual machines?

**Comment by DumboJet** [comment]
I wanted to install Docker on Hyper-V Server 2019 as well, but I see the licensing issues involved...
I guess Microsoft cannot do everything for charity.
Thanks for the free hypervisor. There are other free alternatives to it, but it is nice anyway.

It is also unfortunate (or bad) that running Nano Server inside paid Windows Server versions cause issues. I hope MS fixes that.

**Comment by diegobill** [comment]
@viniciusxyz , did you find any solution to install docker on windows server 2019 essentials? any update on your conclusion https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/945#issuecomment-460319108?

**Comment by HananMohammed** [comment]
545

> 45

1. 
2. 5

- [ ] ##

@# 
@45
   ####4**45**

**Comment by viniciusxyz** [comment]
> @viniciusxyz , did you find any solution to install docker on windows server 2019 essentials? any update on your conclusion [#945 (comment)](https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/945#issuecomment-460319108)?

Sorry for the delay in response, we gave up on Windows and switched to Linux, we've had no problems for years thanks to this decision :)
