### ISSUE TITLE
Images should be pulled from new MCR

### ISSUE THREAD

**Issue by iesen** [MicrosoftDocs/Virtualization-Documentation#960]
After trying commands on Windows Server 2019, images from docker hub gave error while running conainer.
```
docker run microsoft/nanoserver:latest
C:\Program Files\Docker\docker.exe: Error response from daemon: CreateComputeSystem 9f173abc20f5cda63c0851597d7870c1e73ac26fd810d9c83e7a506f758ba584: The container operating system does not match the host operating system.
(extra info: {"SystemType":"Container","Name":"9f173abc20f5cda63c0851597d7870c1e73ac26fd810d9c83e7a506f758ba584","Owner":"docker","VolumePath":"\\\\?\\Volume{ed1235f9-7aaf-450d-b6fb-2346ae6b312f}","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\9f173abc20f5cda63c0851597d7870c1e73ac26fd810d9c83e7a506f758ba584","Layers":[{"ID":"f04cc9bc-9652-5ca4-824f-d97821b925c5","Path":"C:\\ProgramData\\docker\\windowsfilter\\7e41b14f9759c5d402aa37588cb87b3b4f0781c5f9157aee7d9cef885c042360"},{"ID":"129589dc-fce8-5ead-95be-38be3db6acac","Path":"C:\\ProgramData\\docker\\windowsfilter\\7d5cd9a82c08e7adf8cd0e7896dc8d5b5f5345061cbfd5a042098c9e4f847f2e"}],"HostName":"9f173abc20f5","HvPartition":false,"EndpointList":["8A705DEC-0D9F-47A3-864B-6D3AA6BDD5A2"],"AllowUnqualifiedDNSQuery":true}).
```
Changing the registry to MCR (mcr.microsoft.com) fixed the problem.
```
docker pull mcr.microsoft.com/windows/servercore:1809
docker pull mcr.microsoft.com/windows/servercore:ltsc2019
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 206db1f3-8451-0171-e103-fea3ab7b3f72
* Version Independent ID: 87d7ab1c-1617-44a9-a77c-bf0443109e35
* Content: [Joining Windows nodes](https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/joining-windows-workers#joining-a-flannel-cluster)
* Content Source: [virtualization/windowscontainers/kubernetes/joining-windows-workers.md](https://github.com/Microsoft/Virtualization-Documentation/blob/master/virtualization/windowscontainers/kubernetes/joining-windows-workers.md)
* Product: **containers**
* GitHub Login: @daschott
* Microsoft Alias: **daschott**

**Comment by StefanScherer** [comment]
@iesen I've sent #961 with a fix for the example which was confusing or at least outdated.

**Comment by daschott** [comment]
added, thanks.
