### ISSUE TITLE
Instructions for Flannel are outdated

### ISSUE THREAD

**Issue by zevanreg** [MicrosoftDocs/Virtualization-Documentation#968]
The most recent Flannel manifest does not contain kube-flannel-ds DaemonSet. Instead, it contains kube-flannel-ds-amd64, kube-flannel-ds-arm, kube-flannel-ds-arm64, kube-flannel-ds-ppc64le and kube-flannel-ds-s390x.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 444389cf-f12d-0144-6651-95b874fae2dd
* Version Independent ID: d64bda27-6f4a-e2c3-7e7c-6a8ab1bc4b5e
* Content: [Network Topologies](https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/network-topologies)
* Content Source: [virtualization/windowscontainers/kubernetes/network-topologies.md](https://github.com/Microsoft/Virtualization-Documentation/blob/master/virtualization/windowscontainers/kubernetes/network-topologies.md)
* Product: **containers**
* GitHub Login: @daschott
* Microsoft Alias: **daschott**

**Comment by daschott** [comment]
@zevanreg The relevant section has been updated.  A new sample .yaml manifest has also been uploaded for v0.11 that is patched for `-amd64`. You can always use this sample .yaml when the upstream flannel version becomes incompatible with the docs.
