### ISSUE TITLE
grammar and typo

### ISSUE THREAD

**Issue by ShortyCM** [MicrosoftDocs/Virtualization-Documentation#975]
Most computers will run Hyper-V however each virtual machine is a completely seperate operating system.

Most computers will run Hyper-V.  However, each virtual machine is a completely separate operating system.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 223b9ea7-e2c0-4c6b-6d55-9125274d26ce
* Version Independent ID: 85c7005e-33b2-ae0b-a919-f056d14cf0ac
* Content: [Introduction to Hyper-V on Windows 10](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/about/)
* Content Source: [virtualization/hyper-v-on-windows/about/index.md](https://github.com/Microsoft/Virtualization-Documentation/blob/master/virtualization/hyper-v-on-windows/about/index.md)
* Product: **windows-10-hyperv**
* GitHub Login: @scooley

**Comment by doctordns** [comment]
resolved in #1001

**Comment by SphinxKnight** [comment]
After reading the doc today, I can confirm this can be closed.
