### ISSUE TITLE
Windows Server 1809 - Kubernetes Tutorial does not work

### ISSUE THREAD

**Issue by viniciusxyz** [MicrosoftDocs/Virtualization-Documentation#984]
I'm trying to create a Hybrid Kubernetes cluster based on the document: https://docs.microsoft.com/virtualization/windowscontainers/kubernetes/getting-started-kubernetes-windows, I can create the cluster and when I use kubectl get nodes my windows node is there with "Ready" state, however when trying to perform the first deploy through the example described in the manual the created pods are running for a few seconds and after that they begin to infinitely restart, the error that is being presented to me The following is:

`5f12982c884c9b0379bd39c3a): There was an operation attempted on a degraded object.
E0207 10:44:57.688817    4056 cni_windows.go:49] error while adding to cni network: error while ProvisionEndpoint(4a4f877ba9ab2df850e88b818242fdb370370895f12982c884c9b0379bd39c3a_cbr0,F04C3879-F2E5-44A8-96BC-D2B53661BF2A,4a4f877ba9ab2df850e88b818242fdb370370895f12982c884c9b0379bd39c3a): There was an operation attempted on a degraded object.
E0207 10:44:57.693812    4056 pod_workers.go:186] Error syncing pod 04975646-2ad5-11e9-80da-00155dfc0924 ("win-webserver-578967f9d4-wkn56_default(04975646-2ad5-11e9-80da-00155dfc0924)"), skipping: failed to "StartContainer" for "windowswebserver" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=windowswebserver pod=win-webserver-578967f9d4-wkn56_default(04975646-2ad5-11e9-80da-00155dfc0924)"
E0207 10:45:00.016714    4056 docker_sandbox.go:688] ResolvConfPath is empty.`

`E0207 10:37:38.507245    4056 kuberuntime_manager.go:852] PodSandboxStatus of sandbox "cce9414648144751d7930578dccfb20304eecf020698ffc1ade18aa91f70c26d" for pod "win-webserver-578967f9d4-mtmfm_default(049598f9-2ad5-11e9-80da-00155dfc0924)" error: rpc error: code = Unknown desc = Error: No such container: cce9414648144751d7930578dccfb20304eecf020698ffc1ade18aa91f70c26d.`

## Can you help me, please?

# !Important Note

I just needed to change the step that makes marking the:

    kubectl flannel patch ds / kube-flannel-ds --patch "$ (cat node-selector-patch.yml)" -n = kube-system

for:

    kubectl patch ds / kube-flannel-ds-amd64 --patch "$ (cat node-selector-patch.yml)" -n = kube-system
    kubectl patch ds / kube-flannel-ds-arm --patch "$ (cat node-selector-patch.yml)" -n = kube-system
    kubectl patch ds / kube-flannel-ds-arm64 --patch "$ (cat node-selector-patch.yml)" -n = kube-system
    kubectl patch ds / kube-flannel-ds-ppc64le --patch "$ (cat node-selector-patch.yml)" -n = kube-system

# Details

## Describe of one pod

root@fm-dyn-140-0-254-159:/# kubectl describe pods 

win-webserver-578967f9d4-mtmfm

Name:               win-webserver-578967f9d4-mtmfm

Namespace:          default

Priority:           0

PriorityClassName:  <none>

Node:               win-r76r0a6edbe/10.244.1.2

Start Time:         Thu, 07 Feb 2019 10:36:40 -0200

Labels:             app=win-webserver

                    pod-template-hash=578967f9d4

Annotations:        <none>

Status:             Running

IP:
Controlled By:      ReplicaSet/win-webserver-578967f9d4

Containers:

  windowswebserver:

    Container ID:  
    docker://7a6e18f6bb5ee66f76f520c65c95c094c4868e87dc45423c7ed1e
    821c8d5fc3a
    Image:         mcr.microsoft.com/windows/servercore:1809
    Image ID:      docker-pullable://mcr.microsoft.com/windows/servercore@sha256:312e52776493d2789992f2231e6b9d17ac4303ceed2598d6ee2739061fb5cf1f
    Port:          <none>
    Host Port:     <none>
    Command:
      powershell.exe
      -command
      <#code used from https://gist.github.com/wagnerandrade/5424431#> ; $$listener = New-Object System.Net.HttpListener ; $$listener.Prefixes.Add('http://*:80/') ; $$listener.Start() ; $$callerCounts = @{} ; Write-Host('Listening at http://*:80/') ; while ($$listener.IsListening) { ;$$context = $$listener.GetContext() ;$$requestUrl = $$context.Request.Url ;$$clientIP = $$context.Request.RemoteEndPoint.Address ;$$response = $$context.Response ;Write-Host '' ;Write-Host('> {0}' -f $$requestUrl) ;  ;$$count = 1 ;$$k=$$callerCounts.Get_Item($$clientIP) ;if ($$k -ne $$null) { $$count += $$k } ;$$callerCounts.Set_Item($$clientIP, $$count) ;$$ip=(Get-NetAdapter | Get-NetIpAddress); $$header='<html><body><H1>Windows Container Web Server</H1>' ;$$callerCountsString='' ;$$callerCounts.Keys | % { $$callerCountsString+='<p>IP {0} callerCount {1} ' -f $$ip[1].IPAddress,$$callerCounts.Item($$_) } ;$$footer='</body></html>' ;$$content='{0}{1}{2}' -f $$header,$$callerCountsString,$$footer ;Write-Output $$content ;$$buffer = [System.Text.Encoding]::UTF8.GetBytes($$content) ;$$response.ContentLength64 = $$buffer.Length ;$$response.OutputStream.Write($$buffer, 0, $$buffer.Length) ;$$response.Close() ;$$responseStatus = $$response.StatusCode ;Write-Host('< {0}' -f $$responseStatus)  } ;
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    -1073741510
      Started:      Thu, 07 Feb 2019 11:19:53 -0200
      Finished:     Thu, 07 Feb 2019 11:19:57 -0200
    Ready:          False
    Restart Count:  21
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-jvhvl (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  default-token-jvhvl:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-jvhvl
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  beta.kubernetes.io/os=windows
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                  From                      Message
  ----     ------                  ----                 ----                      -------
  Normal   Scheduled               45m                  default-scheduler         Successfully assigned default/win-webserver-578967f9d4-mtmfm to win-r76r0a6edbe
  Warning  FailedCreatePodSandBox  45m                  kubelet, win-r76r0a6edbe  Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "ac48ccb4cbeae566f431bb7f1a91b1b063758513a08e78942411331deff1130f" network for pod "win-webserver-578967f9d4-mtmfm": NetworkPlugin cni failed to set up pod "win-webserver-578967f9d4-mtmfm_default" network: error while ProvisionEndpoint(ac48ccb4cbeae566f431bb7f1a91b1b063758513a08e78942411331deff1130f_cbr0,F04C3879-F2E5-44A8-96BC-D2B53661BF2A,ac48ccb4cbeae566f431bb7f1a91b1b063758513a08e78942411331deff1130f): failed to create the new HNSEndpoint: hnsCall failed in Win32: The object already exists. (0x1392), failed to clean up sandbox container "ac48ccb4cbeae566f431bb7f1a91b1b063758513a08e78942411331deff1130f" network for pod "win-webserver-578967f9d4-mtmfm": NetworkPlugin cni failed to teardown pod "win-webserver-578967f9d4-mtmfm_default" network: failed to find HNSEndpoint ac48ccb4cbeae566f431bb7f1a91b1b063758513a08e78942411331deff1130f_cbr0: Endpoint ac48ccb4cbeae566f431bb7f1a91b1b063758513a08e78942411331deff1130f_cbr0 not found]
  Normal   Pulled                  44m (x4 over 45m)    kubelet, win-r76r0a6edbe  Container image "mcr.microsoft.com/windows/servercore:1809" already present on machine
  Normal   Created                 44m (x4 over 45m)    kubelet, win-r76r0a6edbe  Created container
  Normal   Started                 44m (x4 over 45m)    kubelet, win-r76r0a6edbe  Started container
  Normal   Killing                 44m (x4 over 45m)    kubelet, win-r76r0a6edbe  Killing container with id docker://windowswebserver:Need to kill Pod
  Normal   SandboxChanged          44m (x6 over 45m)    kubelet, win-r76r0a6edbe  Pod sandbox changed, it will be killed and re-created.
  Warning  BackOff                 23s (x501 over 44m)  kubelet, win-r76r0a6edbe  Back-off restarting failed container

## Describe nodes

root@fm-dyn-140-0-254-159:/# kubectl describe node

Name:               fm-dyn-140-0-254-159

Roles:              master

Labels:             beta.kubernetes.io/arch=amd64

                    beta.kubernetes.io/os=linux
                    kubernetes.io/hostname=fm-dyn-140-0-254-159
                    node-role.kubernetes.io/master=
                
Annotations:        

                    flannel.alpha.coreos.com/backend-data: null
                    flannel.alpha.coreos.com/backend-type: host-gw
                    flannel.alpha.coreos.com/kube-subnet-manager: true
                    flannel.alpha.coreos.com/public-ip: 140.0.254.159
                    kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true

CreationTimestamp:  Thu, 07 Feb 2019 10:20:37 -0200

Taints:             node-role.kubernetes.io/master:NoSchedule

Unschedulable:      false

Conditions:

  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  OutOfDisk        False   Thu, 07 Feb 2019 11:23:45 -0200   Thu, 07 Feb 2019 10:20:29 -0200   KubeletHasSufficientDisk     kubelet has sufficient disk space available
  MemoryPressure   False   Thu, 07 Feb 2019 11:23:45 -0200   Thu, 07 Feb 2019 10:20:29 -0200   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Thu, 07 Feb 2019 11:23:45 -0200   Thu, 07 Feb 2019 10:20:29 -0200   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Thu, 07 Feb 2019 11:23:45 -0200   Thu, 07 Feb 2019 10:20:29 -0200   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Thu, 07 Feb 2019 11:23:45 -0200   Thu, 07 Feb 2019 10:20:29 -0200   KubeletReady                 kubelet is posting ready status. AppArmor enabled

Addresses:

  InternalIP:  140.0.254.159

  Hostname:    fm-dyn-140-0-254-159

Capacity:

 cpu:                1

 ephemeral-storage:  129961564Ki

 hugepages-1Gi:      0

 hugepages-2Mi:      0

 memory:             4037428Ki

 pods:               110

Allocatable:

 cpu:                1

 ephemeral-storage:  119772577185

 hugepages-1Gi:      0

 hugepages-2Mi:      0

 memory:             3935028Ki

 pods:               110

System Info:
 Machine ID:                 6d7edb313c07cb64a56dac4a5c5b332c

 System UUID:                EC225194-9123-624A-AA42-CB7F3222BB7D

 Boot ID:                    6ff43984-483b-4d6c-8ccd-e63af1e7a265

 Kernel Version:             4.4.0-131-generic

 OS Image:                   Ubuntu 16.04.5 LTS

 Operating System:           linux

 Architecture:               amd64

 Container Runtime Version:  docker://18.9.1

 Kubelet Version:            v1.12.5

 Kube-Proxy Version:         v1.12.5

PodCIDR:                     10.244.0.0/24

Non-terminated Pods:         (8 in total)

  Namespace                  Name                                            CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ---------                  ----                                            ------------  ----------  ---------------  -------------
  kube-system                coredns-576cbf47c7-d8ztr                        100m (10%)    0 (0%)      70Mi (1%)        170Mi (4%)
  kube-system                coredns-576cbf47c7-jdc6j                        100m (10%)    0 (0%)      70Mi (1%)        170Mi (4%)
  kube-system                etcd-fm-dyn-140-0-254-159                       0 (0%)        0 (0%)      0 (0%)           0 (0%)
  kube-system                kube-apiserver-fm-dyn-140-0-254-159             250m (25%)    0 (0%)      0 (0%)           0 (0%)
  kube-system                kube-controller-manager-fm-dyn-140-0-254-159    200m (20%)    0 (0%)      0 (0%)           0 (0%)
  kube-system                kube-flannel-ds-amd64-fk5ch                     100m (10%)    100m (10%)  50Mi (1%)        50Mi (1%)
  kube-system                kube-proxy-4hpzf                                0 (0%)        0 (0%)      0 (0%)           0 (0%)
  kube-system                kube-scheduler-fm-dyn-140-0-254-159             100m (10%)    0 (0%)      0 (0%)           0 (0%)

Allocated resources:

  (Total limits may be over 100 percent, i.e., overcommitted.)

  Resource  Requests    Limits

  --------  --------    ------

  cpu       850m (85%)  100m (10%)

  memory    190Mi (4%)  390Mi (10%)

Events:     <none>

Name:               win-r76r0a6edbe

Roles:              <none>

Labels:             

                    beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=windows
                    kubernetes.io/hostname=win-r76r0a6edbe

Annotations:       

                    flannel.alpha.coreos.com/backend-data: null
                    flannel.alpha.coreos.com/backend-type: host-gw
                    flannel.alpha.coreos.com/kube-subnet-manager: true
                    flannel.alpha.coreos.com/public-ip: 140.0.254.158
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true

CreationTimestamp:  Thu, 07 Feb 2019 10:35:17 -0200

Taints:             <none>

Unschedulable:      false

Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  OutOfDisk        False   Thu, 07 Feb 2019 11:23:39 -0200   Thu, 07 Feb 2019 10:35:17 -0200   KubeletHasSufficientDisk     kubelet has sufficient disk space available
  MemoryPressure   False   Thu, 07 Feb 2019 11:23:39 -0200   Thu, 07 Feb 2019 10:35:17 -0200   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Thu, 07 Feb 2019 11:23:39 -0200   Thu, 07 Feb 2019 10:35:17 -0200   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Thu, 07 Feb 2019 11:23:39 -0200   Thu, 07 Feb 2019 10:35:17 -0200   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Thu, 07 Feb 2019 11:23:39 -0200   Thu, 07 Feb 2019 10:35:17 -0200   KubeletReady                 kubelet is posting ready status

Addresses:

  InternalIP:  10.244.1.2

  Hostname:    win-r76r0a6edbe

Capacity:

    cpu:                8

    ephemeral-storage:  0

    memory:             4193844Ki

    pods:               110

Allocatable:

        cpu:                8
        ephemeral-storage:  0
        memory:             4193844Ki
        pods:               110
System Info:

 Machine ID:      WIN-R76R0A6EDBE

 System UUID:

 Boot ID:

 Kernel Version:  10.0.17763.253

 OS Image:                   Windows Server 2019 Standard Evaluation

 Operating System:           windows

 Architecture:               amd64

 Container Runtime Version:  docker://18.9.1

 Kubelet Version:            v1.12.5

 Kube-Proxy Version:         v1.12.5

PodCIDR:                     10.244.1.0/24

Non-terminated Pods:         (2 in total)

  Namespace                  Name                              CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ---------                  ----                              ------------  ----------  ---------------  -------------
  default                    win-webserver-578967f9d4-mtmfm    0 (0%)        0 (0%)      0 (0%)           0 (0%)
  default                    win-webserver-578967f9d4-wkn56    0 (0%)        0 (0%)      0 (0%)           0 (0%)

Allocated resources:

  (Total limits may be over 100 percent, i.e., overcommitted.)

  Resource  Requests  Limits

  --------  --------  ------

  cpu       0 (0%)    0 (0%)

  memory    0 (0%)    0 (0%)

Events:

  Type    Reason                   Age                From                         Message
  ----    ------                   ----               ----                         -------
  Normal  Starting                 48m                kubelet, win-r76r0a6edbe     Starting kubelet.
  Normal  NodeHasSufficientDisk    48m (x2 over 48m)  kubelet, win-r76r0a6edbe     Node win-r76r0a6edbe status is now: NodeHasNoDiskPressure
  Normal  Starting                 48m                kubelet, win-r76r0a6edbe     Starting kubelet.
  Normal  NodeHasSufficientMemory  48m                kubelet, win-r76r0a6edbe     Node win-r76r0a6edbe status is now: NodeHasSufficientMemory
  Normal  Starting                 48m                kube-proxy, win-r76r0a6edbe  Starting kube-proxy.

## Docker info Master

Containers: 17

 Running: 16

 Paused: 0

 Stopped: 1

Images: 22

Server Version: 18.09.1

Storage Driver: overlay2

 Backing Filesystem: extfs

 Supports d_type: true

 Native Overlay Diff: true

Logging Driver: json-file

Cgroup Driver: cgroupfs

Plugins:

 Volume: local

 Network: bridge host macvlan null overlay

 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog

Swarm: inactive

Runtimes: runc

Default Runtime: runc

Init Binary: docker-init

containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce

runc version: 96ec2177ae841256168fcf76954f7177af9446eb

init version: fec3683

Security Options:

    apparmor
    seccomp
    Profile: default

Kernel Version: 4.4.0-131-generic

Operating System: Ubuntu 16.04.5 LTS

OSType: linux

Architecture: x86_64

CPUs: 1

Total Memory: 3.85GiB

Name: fm-dyn-140-0-254-159

ID: DB3X:ZEWT:UJCN:AAOG:62ZO:5WWF:QETF:MGRM:62GW:7T6U:MRZB:P3IK

Docker Root Dir: /var/lib/docker

Debug Mode (client): false

Debug Mode (server): false

Registry: https://index.docker.io/v1/

Labels:

Experimental: false

Insecure Registries:

 127.0.0.0/8

Live Restore Enabled: false

Product License: Community Engine

## Docker info Slave Windows

Containers: 16

 Running: 4

 Paused: 0

 Stopped: 12

Images: 26

Server Version: 18.09.1

Storage Driver: windowsfilter (windows) lcow (linux)

 Windows:

 LCOW:

Logging Driver: json-file

Plugins:

 Volume: local

 Network: ics l2bridge l2tunnel nat null overlay transparent

 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog

Swarm: inactive

Default Isolation: process

Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
Operating System: Windows Server 2019 Standard Evaluation Version 
1809 (OS Build 17763.253)

OSType: windows

Architecture: x86_64

CPUs: 8

Total Memory: 4GiB

Name: WIN-R76R0A6EDBE

ID: AZE2:OUXK:OCQJ:AXH5:M4KX:CGKE:N7YJ:ACEW:NPUS:D3SW:5J6Y:XO6H

Docker Root Dir: C:\ProgramData\docker

Debug Mode (client): false

Debug Mode (server): false

Registry: https://index.docker.io/v1/

Labels:

Experimental: true

Insecure Registries:

 140.0.252.1:5000

 127.0.0.0/8

Live Restore Enabled: false

WARNING: API is accessible on http://0.0.0.0:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface

**Comment by wangrong2012** [comment]
Did you resolved the problem?
I have the similar problem :
E1012 15:04:12.222732    1580 kuberuntime_manager.go:710] createPodSandbox for pod "win-webserver-blfzf_default(4f009c6c-e195-41d7-9b12-47d8be0f240b)" failed: rpc error: code = Unknown desc = failed to create a sandbox for pod "win-webserver-blfzf": Error response from daemon: Conflict. The container name "/k8s_POD_win-webserver-blfzf_default_4f009c6c-e195-41d7-9b12-47d8be0f240b_0" is already in use by container "9af4c411f7d70f4dfd9157c069628cb925e5c9bb27c711be92ffc2055922ac48". You have to remove (or rename) that container to be able to reuse that name.
E1012 15:04:12.224733    1580 pod_workers.go:191] Error syncing pod 4f009c6c-e195-41d7-9b12-47d8be0f240b ("win-webserver-blfzf_default(4f009c6c-e195-41d7-9b12-47d8be0f240b)"), skipping: failed to "CreatePodSandbox" for "win-webserver-blfzf_default(4f009c6c-e195-41d7-9b12-47d8be0f240b)" with CreatePodSandboxError: "CreatePodSandbox for pod \"win-webserver-blfzf_default(4f009c6c-e195-41d7-9b12-47d8be0f240b)\" failed: rpc error: code = Unknown desc = failed to create a sandbox for pod \"win-webserver-blfzf\": Error response from daemon: Conflict. The container name \"/k8s_POD_win-webserver-blfzf_default_4f009c6c-e195-41d7-9b12-47d8be0f240b_0\" is already in use by container \"9af4c411f7d70f4dfd9157c069628cb925e5c9bb27c711be92ffc2055922ac48\". You have to remove (or rename) that container to be able to reuse that name."
E1012 15:04:25.073331    1580 docker_sandbox.go:726] ResolvConfPath is empty.

**Comment by viniciusxyz** [comment]
I will close the issue because it has been over a year and a lot has changed in that time.
