### ISSUE TITLE
Networking differences between MobyVM and LCOW with Hyper-V containers

### ISSUE THREAD

**Issue by ggirard07** [MicrosoftDocs/Virtualization-Documentation#986]
EDIT: Not sure this is on the right article...

I started to tinkle a bit with LCOW and I am having an hard time to understand the differences in networking between LCOW running with Hyper-V isolation and default MobyVM.

MobyVM used to take advantage of WinNAT to expose a single bridge network between the host and the containers. But when switching to LCOW, running command `Get-NetNat` doesn't return any NAT related switch (Win 10 1809 here).

Is WinNAT still used by HNS? ie Does WinNAT limitations still applies to Docker for Windows running LCOW?
Can you explain how Docker for Windows interact with Hyper-V `Default Switch` and what `nat` switch is used for?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44aeb504-236b-28fd-bd33-13ebafecaec4
* Version Independent ID: eb33ef93-6440-eb5d-e6cb-b1de47d4c211
* Content: [Hyper-V Containers](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/hyperv-container)
* Content Source: [virtualization/windowscontainers/manage-containers/hyperv-container.md](https://github.com/Microsoft/Virtualization-Documentation/blob/master/virtualization/windowscontainers/manage-containers/hyperv-container.md)
* Service: **windows-containers**
* Product: **windows-containers**
* GitHub Login: @scooley

**Comment by MythreyaK** [comment]
I'm not sure, but [this](https://blogs.technet.microsoft.com/virtualization/2016/05/25/windows-nat-winnat-capabilities-and-limitations/) might help shed some light as it talks about HNS and Docker a little.

**Comment by ggirard07** [comment]
@MythreyaK Thanks for the link, I saw it but it didn't help at the time.
As I mentioned in my post, `Get-NetNat` returns nothing when using LCOW, which means to me all of the article no longer seem to apply when using LCOW...
