### ISSUE TITLE
Hypervisor Platform API documentation

### ISSUE THREAD

**Issue by virtxx** [MicrosoftDocs/Virtualization-Documentation#994]
** Description**
It is really great the HyperV Platform API is now available. However, I think the description of the error codes and pre-conditions for the functions could be improved. For instance, I am right now facing a problem with the WHvRequestInterrupt() function. My intention is to use this function to inject a interrupt into the guest (not via APIC but just the "raw" interruption of the CPU)but I should note that there's not any documentation for the function so it could even have a different purpose. It consistently returns "0xc0350008 : The operation is not allowed in the current state.". I have of course verified the guest is ready to receive the interrupt (has interrupt flag set etc.). There is no documentation what may cause this error code or what state is expected. Indeed, the function makes no mention of the pre-conditions. The parameters to the function are hardly documented. I have tried calling the function "in-between" calls to WHvRunVirtualProcessor (which I expect to be the most likely intended usage) or from another thread while the guest is running but it doesn't make any difference. I have literally tried all combinations of parameters to the function, so I am at a loss to explain why it doesn't work. It would be good if the function purpose was documented as well as a description of the required configuration/state of the guest, along with a list of possible error codes and what error might conditions might cause them.

Link to doc:

https://docs.microsoft.com/en-us/virtualization/api/hypervisor-platform/hypervisor-platform

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  We recently started discussing improvements for the WHP documentation and documenting the interrupt behavior is on the list.

In the meantime, can you enable apic emulation through WHvPartitionPropertyCodeLocalApicEmulationMode and retry your code - https://docs.microsoft.com/en-us/virtualization/api/hypervisor-platform/funcs/whvpartitionpropertydatatypes?  Today WHvRequestInterrupt requires apic emulation and we will make sure to clarify that in the documents and add samples.

**Comment by virtxx** [comment]
Hi thanks yes this solves it - at least I no longer get an error when calling the function. I still don't see the interrupt being delivered but I have not investigated the reason for that yet (probably APIC issue). I think it would be useful if the documentation could state how to use the function in case one wishes to simulate a "good old 8259A PIC-based CPU" (which is necessary to support older operating systems). My guess is you have to request interrupt delivery with type ExtINT, but there must be other preconditions necessary. Maybe better configuration of the APIC. I am looking into it, thanks for now :)

**Comment by virtxx** [comment]
Just one more note: I actually figured out how to do this using the PendingInterrupt registers (thus bypassing the APIC completely) but it took a lot of guess-work to figure out. So maybe you could document those as well :-)

**Comment by stehufntdev** [comment]
Thanks for the follow-up.  Yes, we are planning on documenting injecting interrupts with and without WHvRequestInterrupt.  Please let us know if you hit any other issues.

**Comment by 2bitsin** [comment]
Wow 4 years and still no documentation, very dissapointing
